TextureGroup/Texture

Source/ASNetworkImageNode.mm
This can eventually cause the rendering queue to get stalled https://jira.pinadmin.com/browse/BUG-54113
=> Fix Case where Network Image Node Stays Locked

Source/Private/ASCollectionLayout.mm
(Ported from https://github.com/facebook/AsyncDisplayKit/pull/3262)
Currently, ASDataController sets the calculated size of a cell node right after measuring it (here). This behavior dates all the way back to the first implementation of ASDataController. This is to ensure that by the time the cell needs to display, it has a valid size and the needsLayout flag of its layer is on. Failing to do so will cause it to skip its display pass entirely.
ASCollectionLayout currently doesn't do this which causes some cells to be missing. This PR updates ASCollectionLayout to set the frame whenever a node's layout attributes is asked.
There are 2 other places we can fix this:
When the cell node applies its layout attributes. This event is driven by UICollectionView and is often too late. We want all …
=> [ASCollectionLayout] Manually set size to measured cells

Source/ASDisplayNode.mm
canClearContentsOfLayer now turned off for views with CAEAGLLayer
more:
https://github.com/TextureGroup/Texture/issues/53
=> GLKit workaround #trivial

plans/LayoutDebugger/Overview.md
=> Layout debugger proposal

CHANGELOG.md, Source/Base/ASLog.h
@nguyenhuy recreating pull request as you asked
=> Fix __has_include check in ASLog.h #trivial

Source/ASCollectionView.mm
Some apps explicitly enable this, which is counterproductive with ASDK. This can also worsen data inconsistency issues as it creates additional traffic from UIKit.
=> [ASCollectionView] Prevent prefetching from being enabled to eliminate overhead.

Source/ASDisplayNode.h, Source/Details/UIView+ASConvenience.h, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASPendingState.mm
Although apps could handle this before by setting the view's property in didLoad, it's
useful to bridge this property for setting during off-main initialization.
This change is required in order to finalize and land https://github.com/TextureGroup/Texture/pull/59/files - or otherwise I can do a followup PR to merge the small amount of code in +UIViewBridge that gives an opportunity to update other state when this attribute changes.
=> [RTL] Bridge the UISemanticContentAttribute property for more convenient RTL support.

Source/Details/ASTraitCollection.h, Source/Layout/ASLayoutElementPrivate.h, Source/Layout/ASLayoutSpec.mm
So I was trying to implement a dummy object that conforms to `ASLayoutElement` protocol and found out that there are already a bunch of helpful default implementations, some of them can be used directly in  `ASLayoutSpec`.  So I updated `ASLayoutSpec` to do just that.
=> ASLayoutSpec to use more default implementations #trivial

Source/ASDisplayNode+Beta.h, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.mm
This is a simple additional fix to the last Yoga patch. I was going to
upload it into the same diff, but fell behind for a couple days and 
didn't realize it was of interest to converge this area.
I have no other immediate plans to submit more changes here. However
I am planning to re-work the yoga integration to reduce its footprint
and improve its reliability. 
It would be awesome if there's any way I can keep up on plans in this area,
so that my design to improve the integration and make it more clean are
as applicable as possible. Let me know if I can help!
=> [Yoga] Ensure that calculated layout is nil'd in invalidate*Layout

Source/ASTableView.mm
Ensure superclass scroll view delegate methods are called when the scroll view parameter is not the current ASTableView.
Fixes #38
=> Fix issue with swipe to delete cell gesture. #trivial

Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/ASDisplayNodeInternal.h
Although Objective-C atomics are equally fast, or better that std::atomic when
access through method calls, for the most intense use cases it is best to avoid
method calls entirely.
In ASDisplayNode, we could benefit significantly from avoiding both method calls
(already true today) but also avoid locking the mutex, for both CPU and contention
gains.
There will still be many methods that need locking for transactional
consistency - however, there are currently dozens of accessor methods that could
avoid frequent lock / unlock cycles with use of atomics, and other usages of the
ivars directly where locking could be delayed until after early-return conditions
are checked and passed.
=> [ASDisplayNode] Implement a std::atomic-based flag system for superb performance

CHANGELOG.md, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h
- Remove ASDisplayNode's conformance to NSFastEnumeration
- We were creating a new copy of subnodes for each chunk of enumeration.
- The enumerated collection wasn't stable – technically nodes could be deallocated during enumeration under the right circumstances.
- Instead of making a new copy of subnodes each time, just store a cached copy.
- Remove silly `dealloc` line that explicitly nils the ivar.
=> Improve Our Handling of Subnodes

AsyncDisplayKit.xcodeproj/project.pbxproj
Whenever I make any change to the Xcode project, Xcode removes these references. These files must have been moved in a recent PR and the old references were left hanging around, or something.
=> Fix Issues in the Project File #trivial

docs/_docs/text-node.md
There are multiple reports about using `lineSpacing` and `maximumNumberOfLines` with `ASTextNode` will result in the wrong number of lines. As this issues comes up frequently let's add something to the docs for now. 
Issues addressed:
- https://github.com/facebook/AsyncDisplayKit/issues/2105
- https://github.com/facebook/AsyncDisplayKit/issues/3128
- https://github.com/facebook/AsyncDisplayKit/issues/3174
=> [Docs] Add workaround for setting a custom lineSpacing and maxNumberOfLines to ASTextNode docs

CHANGELOG.md, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Details/ASDataController.mm, Source/Layout/ASLayoutElementPrivate.h, Source/Layout/ASLayoutSpec+Subclasses.h, Source/Layout/ASLayoutSpec+Subclasses.mm, Source/Layout/ASLayoutSpec.h, Source/Layout/ASLayoutSpec.mm
`finalLayoutElement` is not used within the frameworks as well as in Pinterest. It was never documented probably either or made public. As we don't rely on it anymore and further refactoring will go on in this area I would propose to remove it.
=> [Layout] Remove finalLayoutElement

Source/Private/ASTwoDimensionalArrayUtils.m
In some build environments, this causes an error. It seems to be a change since 2.2.
=> [ASTwoDimensionalArrayUtils] Fix extern C function definition to fix compiler issue.

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/Details/ASCollectionFlowLayoutDelegate.h, Source/Details/ASCollectionFlowLayoutDelegate.m, Source/Details/ASCollectionLayoutDelegate.h, Source/Details/ASCollectionLayoutState.h, Source/Details/ASCollectionLayoutState.m, Source/Details/ASPageTable.h, Source/Details/ASPageTable.m, Source/Details/ASPageTable.mm, Source/Private/ASCollectionLayout.mm
- It is a screen page table that can be used to quickly filter out objects in a certain rect without checking each and every one of them.
- ASCollectionLayoutState generates and keeps a table that maps page to layout attributes within that page.
- ASCollectionLayout (and later, ASCollectionGalleryLayoutDelegate) consults its layout state for `layoutAttributesForElementsInRect:`. This ensures the method can return as quickly as possible, especially on a large data set (I heard some people have galleries with thousands of photos!).
This PR was extracted from https://github.com/TextureGroup/Texture/pull/76. Tickets: facebook/AsyncDisplayKit#2979 and facebook/AsyncDisplayKit#3219
=> Implement ASPageTable

Source/ASImageNode.mm
To be able to switch to a more transaction based drawing and therefore using the class drawing methods this is a small change to reduce the reliance on self in the drawing method by moving the debug label setup code as well as the will- / didDisplayNodeContentWithRenderingContext in the drawing parameters.
=> [ASImageNode] Move debug label and will- / didDisplayNodeContentWithRenderingContext out of drawing method #trivial

Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h
No idea why this was implemented this way in the first place, but let's get rid of it.
=> Don't Use Associated Objects for Drawing Priority #trivial

Source/ASNetworkImageNode.mm
We need this in case someone is setting the URL to nil before setting
the image directly. I.e. they have a node which has been used as a network
node or an image node but now they want it to be an image node.
They should then set the URL to nil and then set the image.
*if* it was used as a network node previously, this would work.
If it was previously used as an image node it would historically assert.
This addresses that.
=> Assert only once we know URL has changed

Source/Layout/ASDimension.h
Remove the warning which appears when we build framework.
We were trying to build a static CGFloat assigning a Double.
=> [ASDimension] Remove warning about float precision using CGFloat and … #trivial

CHANGELOG.md, Source/ASDisplayNode.h, Source/ASImageNode.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm, examples/LayoutSpecExamples-Swift/Sample/LayoutExampleNode.swift, examples/LayoutSpecExamples/Sample/LayoutExampleNodes.m
The reasoning for this change is that developers came up with all kinds of interesting ideas how to use properties in the `ASDisplayNodeContextModifier` blocks as it's running on non main properties like `backgroundColor` is not accessible. It is possible to access this properties on the main thread though and as we know `drawParametersForAsyncLayer` is called on main, developers can store this kind of properties within the draw parameters and use this in the `ASDisplayNodeContextModifier` blocks. To be able to do that we actually have to pass them in what this PR is planning to do.
This is basically an API breakage change and I'm happy to change if we would like to deprecate the old API and move over to this one, but as `willDisplayNodeContentWithRenderingContext` and …
=> [ASDisplayNode] Pass drawParameter in rendering context callbacks

CHANGELOG.md, Source/ASDisplayNode.mm, Source/ASImageNode.mm, Source/Details/_ASDisplayLayer.h, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/Private/ASDisplayNode+FrameworkPrivate.h, Source/Private/ASDisplayNodeInternal.h
In our effort going forward to make the framework safer to work with and to enable future optimizations like lifting up caching into a generalized way out of ASImageNode and ASTextNode specific ways this PR will remove the instance version of displayWithParameters:isCancelled: in favor of using the class method.
=> [ASImageNode] Move to class method of displayWithParameters:isCancelled: for drawing

CHANGELOG.md, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode.mm, Source/ASTextNode.mm, Source/Details/_ASDisplayLayer.h, Source/Private/ASDefaultPlayButton.m, Source/Private/ASDefaultPlaybackButton.m, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/Private/ASDisplayNode+FrameworkPrivate.h, Source/Private/ASDisplayNodeInternal.h
In our effort going forward to make the framework safer to work with and to enable future optimizations like lifting up caching into a generalized way out of `ASImageNode` and `ASTextNode` specific ways this PR will remove the instance version of `drawRect:withParameters:isCancelled:isRasterizing:` in favor of using the class method.
=> [ASTextNode] Move to class method of drawRect:withParameters:isCancelled:isRasterizing: for drawing

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASDisplayNode.mm, Source/ASDisplayNodeExtras.h, Source/ASDisplayNodeExtras.mm, Source/AsyncDisplayKit.h, Source/Base/ASDisplayNode+Ancestry.h, Source/Base/ASDisplayNode+Ancestry.m
This is a more complete fix for #240 and supersedes #241 .
- The assertion failure is only due to _loading_ the layer during upward traversal, which we shouldn't do. This diff prevents that from happening.
- Add public category methods `supernodes` `supernodesIncludingSelf` and `supernodeOfClass:includingSelf:`.
- I thought about these names a lot. The word `ancestry` is more precise but I think these names are more user-friendly.
- Deprecate `ASDisplayNodeFindFirstSupernode()` and `ASDisplayNodeFindFirstSupernodeOfClass()` in favor of the new category methods.
- Remove a redundant/silly code path in `ASDisplayNode.layer` that checks `self.view.layer`. No! We either have `_layer` or we need to load it, end of story.
- Renames `-_locked_loadViewOrLayerIsLayerBacked:` to simply …
=> Improve Ancestry Handling, Avoid Assertion Failure

CHANGELOG.md, Source/TextKit/ASTextKitFontSizeAdjuster.mm
`boundingRectWithSize:options:context:`  started returning different values for the same strings between iOS 10.2 and iOS 10.3. Switching to using `NSLayoutManager`’s `boundingRectForGlyphRange: inTextContainer:` fixed this. It also makes sure we are consistent with what `ASTextKitTailTruncater` uses.
=> [ASTextKitFontSizeAdjuster] Replace use of boundingRectWithSize:options:context: with boundingRectForGlyphRange: inTextContainer:

CHANGELOG.md, Source/ASVideoNode.h, Source/ASVideoNode.mm
here is a simple implementation of error reporter to ASVideoNodeDelegate. Once asset is failed to load an item - it reports to it's delegate that the error has occured
(huy: Closes https://github.com/TextureGroup/Texture/issues/252)
=> added error reporting callback to ASVideoNode

CHANGELOG.md, Source/ASCollectionView.mm
We were attempting to convert in the wrong order!
=> Fix Collection Item Index Path Conversion

Source/ASDisplayNode.mm, Source/Private/ASInternalHelpers.m
A quickie.
- Remove call to `[super initialize]`. The runtime will traverse the class hierarchy for us.
- Only run the override checking code when assertions are enabled.
- Check `Method != Method` rather than `IMP != IMP` because it's faster and simpler.
=> Simplify Override Checking, Only Do It When Assertions Are Enabled #trivial

Source/Layout/ASLayoutElement.mm
It's more direct to store this info in TLS than to use a lock and a map.
=> Store ASLayoutElementContext in Thread-Local Storage #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASTextNode+Beta.h, Source/ASTextNode.mm, Source/Private/ASTextNode2.h, Source/Private/ASTextNode2.mm, Source/Private/TextExperiment/Component/ASTextDebugOption.h, Source/Private/TextExperiment/Component/ASTextDebugOption.m, Source/Private/TextExperiment/Component/ASTextInput.h, Source/Private/TextExperiment/Component/ASTextInput.m, Source/Private/TextExperiment/Component/ASTextLayout.h, Source/Private/TextExperiment/Component/ASTextLayout.m, Source/Private/TextExperiment/Component/ASTextLine.h, Source/Private/TextExperiment/Component/ASTextLine.m, Source/Private/TextExperiment/String/ASTextAttribute.h, Source/Private/TextExperiment/String/ASTextAttribute.m, Source/Private/TextExperiment/String/ASTextRunDelegate.h, Source/Private/TextExperiment/String/ASTextRunDelegate.m, Source/Private/TextExperiment/Utility/ASTextUtilities.h, Source/Private/TextExperiment/Utility/ASTextUtilities.m, Source/Private/TextExperiment/Utility/NSAttributedString+ASText.h, Source/Private/TextExperiment/Utility/NSAttributedString+ASText.m, Source/Private/TextExperiment/Utility/NSParagraphStyle+ASText.h, Source/Private/TextExperiment/Utility/NSParagraphStyle+ASText.m, examples/Kittens/Sample/AppDelegate.m, examples/Kittens/Sample/KittenNode.mm
https://paper.dropbox.com/doc/ASTextNode-Experimental-Replacement-bswIlZJjmjDj1fJjwegzH
I'd like to get this reviewed and merged so that we can start experimenting with it in Pinterest and YouTube, even though the experimental implementation is missing some features.
@garrettmoon @nguyenhuy @maicki @appleguy
cc #221 & #227
=> Add Experimental Text Node Implementation

Source/ASDisplayNode.mm
There was a regression in #253. Most of the code in `+initialize` is only needed if assertions are enabled, but not all of it.
This diff makes a clear dilineation between code that is required to be run in all configs, and code that is only used to make assertions.
=> Fix Release Builds #trivial

Source/Private/TextExperiment/Component/ASTextLayout.h, Source/Private/TextExperiment/Utility/ASTextUtilities.h, Source/Private/TextExperiment/Utility/NSAttributedString+ASText.h
These documentation warnings are killing our CI (in the `pod spec lint` phase). Strangely, they didn't show up when this code was initially landed. Anyway this fixes em.
=> Fix Documentation Warnings #trivial

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm, Source/Private/ASDisplayNode+FrameworkPrivate.h, Source/Private/ASDisplayNodeInternal.h
- Create a formal `asdispalynode_iscancelled_block_t` for tracking cancellation of layout transitions.
- Use atomic variables for `transitionID` and `pendingTransitionID`, and take them out from under `__instanceLock__`.
- Remove the `BOOL transitionInProgress` field. Instead, we reset `transitionID` to `Invalid` if there is no transition in progress.
- Use a global autoincrementing int for transition IDs, rather than a separate autoincrement per-node.
- Could this cause overflow? No, not any time soon. We support up to 2.1 million transitions which should be plenty. We can change the data-type for our transitions in a separate diff if we want to.
=> Simplify Layout Transition State #trivial

Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Private/ASCellNode+Internal.h
This method is never called and is a leftover from a previous implementation of our collection/table-node-resize-observing system. It's been replaced by `nodeDidInvalidateSize:`.
=> Remove Unused Node Code #trivial

CHANGELOG.md, Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASDataController.h, Source/Details/ASDataController.mm
Resolves #277 
As the data controller, it's fine to skip the layout. The cell node will either be deallocated, or it'll be hosted somewhere else and it'll get a new layout pass.
=> Ignore Relayout Requests for Deleted Cell Nodes

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASCollectionNode+Beta.h, Source/ASCollectionNode.mm, Source/ASCollectionView.mm, Source/ASTableNode+Beta.h, Source/ASTableNode.mm, Source/ASTableView.mm, Source/Details/ASBatchFetchingDelegate.h, Source/Private/ASBatchFetching.h, Source/Private/ASBatchFetching.m, Tests/ASBatchFetchingTests.m
- In addition to checking remaining leading screens, `ASBatchFetching` now also calculates a remaining time and consults its delegate if needed.
- The delegate can override the decision of `ASBatchFetching`, for example based on remaining time and average time of past batch requests.
=> [Batch Fetching] Add ASBatchFetchingDelegate

CHANGELOG.md, Source/ASImageNode.mm, Source/ASTextNode.mm, Source/Private/ASHashing.h, Source/TextKit/ASTextKitAttributes.mm
- We initialize our structs using `{ 7, 5, 3 }`. When you do this, if the struct has padding, the memory contained in the padding bytes contains garbage.
- Our ASImageNodeContentsKey hashes a struct that has padding bytes.
- So that hash wasn't reliable, and our cache hit rate plummeted.
The solution is:
- Enable the `-Wpadded` warning around structs that we use `{}` and subsequently hash.
- Update the ASImageNodeContentsKey struct to be aligned (change BOOL to NSInteger).
- Update the documentation on ASHashBytes to point out this warning.
We could enable `-Wpadded` globally but usually we don't care too much about padding so let's not do it for now.
This patch is extremely important and should be released in a hotfix. The image cache hit rate before this patch is extremely low, at least …
=> Fix Alignment of Hashed Structs

CHANGELOG.md, Source/ASVideoNode.mm
=> [ASVideoNodeDelegate] fix for #291 crash 

CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h
After https://github.com/facebookarchive/AsyncDisplayKit/pull/3263, a layout pass can be triggered even before a node is loaded. This is to ensure the node has valid bounds to fetch its content as soon as it enters preload state, regardless of its backing store.
However, the API contracts of `-layout` and `-layoutDidFinish` state that those methods are triggered by the view's `layoutSubviews`. That means the node must be loaded by the time they are called.
This PR adds a node loaded check to `__layout` that ensures those 2 methods are called only if the condition meets.
=> Only call -layout and -layoutDidFinish if the node is already loaded

Source/Private/ASBatchFetching.m
- Doing so causes remaining time to be slightly inaccurate.
=> ASBatchFetching to not round scroll velocity #trivial

Source/AsyncDisplayKit.h
Apparently due to the change in #286 we broke some more stuff building the framework. For some reason the tests as well as the build script finished and was fine in this PR, now it's failing though. So let's fix it.
I tested it with our test suite, building all the examples as well as building the ASDKListKit project.
Resolves #298
=> IGListKit related headers need to be in the module all time now #trivial

Source/ASDisplayNode.mm
Based on discussion in #242 we remove the assertion in `-[ASDisplayNode calculateSizeThatFits:]` and log an event
Resolves #296
=> [ASDisplayNode] Remove assertion in calculateSizeThatFits: and log an event #trivial

Source/Base/ASAssert.h, Source/Details/_ASDisplayLayer.mm
- Modify `ASDisplayNodeAssertNonFatal` to return YES/NO based on whether assertion passed.
- Add a nonfatal in `_ASDisplayLayer setBounds:` to ensure the bounds are valid and ignore-with-nonfatal otherwise.
The motivation for this diff is, in Pinterest we're seeing cases where UIScrollView's own gesture-recognizer is causing `nan` positions to be set on scroll views' layers. It's extremely unlikely that framework code is responsible for it but we can help catch the problem.
=> Catch Invalid Layer Bounds in a Nonfatal Assertion #trivial

CHANGELOG.md, Source/Private/ASDisplayNode+UIViewBridge.mm
Lock released between add to pend controller and modifying pend state
The existing design is pretty fraught with error. We should probably
rethink this but in the meantime, this fixes a bug where calling
setNeedsLayout can start failing for nodes.
Essentially the method ASDisplayNodeShouldApplyBridgedWriteToView has
a side effect of registering a node to apply it's pending state *if*
it doesn't currently need the pending state applied. My guess is this
was to avoid continually registering the node and this behavior actually
helped expose this bug.
The bug: after the node is registered for flushing it's state, several
code paths released the lock before applying that state to the pending
state object. Before it could re-obtain the lock to apply it to the pending
state, the pending state …
=> Fix non layout

docs/_docs/installation.md
Fixed typo in carthage project name that's supposed to point to the master branch
=> [Docs] Fixed typo in carthage project name 

Source/ASDisplayNode.mm
For apps that include pre-existing calls to reloadData, this assertion has made
development difficult on all recent versions of Texture.
Since triggering it can't be reliably used as signal by the app developer, and
halts a development session (sometimes immediately on app start), it should be
disabled until it is reliable again.
See issue #145 for details. cc @Adlai-Holler, @garrettmoon 
Ideally we'd push a release shortly after taking this change, as the issue has been widely reported in the community. There's no known workaround besides modifying the local copy of Texture with a change like this, and local diffs discourage updating.
=> [ASDisplayNode] Revise assertion to log until Issue #145 is addressed. #trivial

Source/ASCollectionNode.mm
Hi guys,
Some `ASCollectionView` properties have recently been deprecated in favour of their `ASCollectionNode` counterparts, but it turns out that they're not fully functional yet:
- The `layoutInspector` from the `_pendingState` is not forwarded to the view in `didLoad`, which means that setting it only works *after* the view has been loaded, which kinda defeats the purpose of having the property at the node level.
- The `scrollDirection` and `scrollableDirections` properties are not implemented, which means that we never get the actual value from the underlying view.
These two problems are demonstrated in this sample project (along with a waterfall layout that could be useful to some Texture users :-)): https://github.com/flovouin/Texture-CollectionNodeProperties
The `layoutInspector` …
=> [ASCollectionNode] Fix missing properties and layoutInspector #trivial

Source/Details/_ASDisplayLayer.h, Source/Details/_ASDisplayLayer.mm
- Make `asyncDelegate` an atomic property, rather than using a mutex.
- The weird `NS_VALID_UNTIL_END_OF_SCOPE` code has been there since the original version of this file in 2014. Originally, the async delegate was accessed using a block, so I guess this was extra safety since they didn't know what you would do in the block. Anyway, ARC will retain the delegate throughout the method call so there's no behavior change here.
- Make `displaySuspended` main-thread-only. This isn't actually a behavior/API change, since changing the value off-main in the past would trigger an assertion failure downstream (in `-setNeedsDisplay` or `-cancelAsyncDisplay`) anyway. Better to just bite the bullet.
- Other miscellaneous cleanup.
=> Clean Up ASDisplayLayer #trivial

Source/Details/Transactions/_ASAsyncTransaction.h, Source/Details/Transactions/_ASAsyncTransaction.mm, Source/Details/Transactions/_ASAsyncTransactionContainer.m, Source/Details/Transactions/_ASAsyncTransactionGroup.m
- Make operation values simply `id` rather than `id<NSObject>`. `id<NSObject>` can be a pain to deal with since it can't be implicitly cast, plus it's ugly.
- Make transactions always call back on the main thread, rather than parameterized `callbackQueue`.
- Previously, you couldn't pass any queue for callback other than the main queue anyway.
- Code was inconsistent. Some places directly used main thread, other places used parameterized `callbackQueue`.
- Make operation value `atomic` since it's set from background thread, but read from main thread.
- Other misc cleanup.
=> Clean Up ASAsyncTransaction #trivial

Source/ASCollectionView.mm, Source/ASDisplayNode.mm, Source/ASTableView.mm, Source/Details/ASRangeController.mm, Source/Details/_ASCollectionReusableView.h, Source/Details/_ASCollectionReusableView.m, Source/Details/_ASCollectionViewCell.h, Source/Details/_ASCollectionViewCell.m
cc #145  . I never had a reliable repro for it, so I'm counting on the community to test this patch.
`willDisplayCell` and `didEndDisplayingCell` are the authoritative sources for what elements are visible. Elements may be visible in multiple cells e.g. during animations, so we use a counted set.
- Replace `(weak)_ASCollectionViewCell.node` with `(strong)_ASCollectionViewCell.element`.
- Add an `NSCountedSet<ASCollectionElement *> *_visibleElements` to collection view.
- In `willDisplayCell:` and `didEndDisplayingCell:`, add/remove the cell's element from the visible set.
- Modify `visibleElementsForRangeController:` to just return a copy of this set.
- Put back the dealloc-while-visible assertion.
=> Rejigger Cell Visibility Tracking

Source/ASCollectionView.mm, Source/ASDisplayNode.mm, Source/ASTableView.mm, Source/Base/ASBaseDefines.h, Source/Details/ASAbstractLayoutController.h, Source/Details/ASAbstractLayoutController.mm, Source/Details/ASCollectionViewLayoutController.m, Source/Details/ASLayoutController.h, Source/Details/ASRangeController.h, Source/Details/ASRangeController.mm, Source/Details/ASTableLayoutController.m, Source/Layout/ASLayoutSpec.mm, Source/Private/Layout/ASLayoutSpecPrivate.h
Resolves #312 and improves performance by replacing `-hash` and `-isEqual:` with pointer work.
=> Replace NSMutableSet with NSHashTable when Appropriate #trivial

CHANGELOG.md, Source/ASDisplayNode+Layout.mm
It is rare that this code has any effect, but I've discovered a case in which it occurs.
This task tracks moving this code to a DEBUG-only assertion: https://github.com/TextureGroup/Texture/issues/335
=> [ASDisplayNode+Layout] Add check for orphaned nodes after layout transition to clean up.

CHANGELOG.md, Source/ASCollectionNode+Beta.h, Source/ASCollectionNode.mm, Source/ASCollectionView.mm, Source/Details/ASCollectionInternal.h, Source/Details/ASDataController.h, Source/Details/ASDataController.mm
Adds a `usesSynchronousDataLoading` mode to `ASCollectionView`. When this mode is enabled, `ASCollectionView` matches the timing of `UICollectionView` as closely as possible, ensuring that all reload and edit operations are performed on the main thread as blocking calls. 
This mode is useful for applications that are debugging issues with their collection view implementation. In particular, some applications do not correctly conform to the `UICollectionView` API, and these apps may experience difficulties with `ASCollectionView`. Providing this mode allows for developers to work on resolving their issues with the collection view data source, while ramping up on asynchronous collection layout.
=> [ASCollectionView] synchronous mode

Source/ASDisplayNode+Beta.h, Source/Base/ASAvailability.h
Fixes https://github.com/TextureGroup/Texture/issues/25
=> [Yoga] Refer to proper path name and use module import

Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode.h, Source/Details/ASImageProtocols.h, Source/Layout/ASLayoutElement.h
Our internal Linter caught a couple of warnings that this PR will fix. Thanks for @jerrymarino for discovering it:
```
...
In file included from /Users/jerry/Projects/ios/Platform/include/AsyncDisplayKit/ASDisplayNode.h:27:
/Users/jerry/Projects/ios/Platform/include/AsyncDisplayKit/ASLayoutElement.h:75:1: warning: Using assign for an ObjC pointer type is not valid. Either use strong or weak for a zeroing reference in this case.
@property (nonatomic, assign, readonly) ASLayoutElementStyle *style;
^
...
In file included from /Users/jerry/Projects/ios/Platform/include/AsyncDisplayKit/AsyncDisplayKit.h:19:
/Users/jerry/Projects/ios/Platform/include/AsyncDisplayKit/ASDisplayNode.h:649:1: warning: Using a pointer for a scalar type is invalid.
@property (nonatomic, assign, nullable) CGColorRef …
```
=> Fix internal Linter warnings #trivial

CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASDisplayNodeExtras.h, Source/Layout/ASLayout.h, Source/Layout/ASLayout.mm, Source/Private/ASDisplayNodeInternal.h
- `ASDisplayNode` can be told to not flatten its layout immediately but later on. The unflattened layout is also stored in a separate property. It's needed for inspecting not only display nodes but also layout specs used to compute a layout tree.
- `ASLayout` can be told to always retain its sublayout elements. This is needed especially for layout specs since they are usually not retained after an `ASLayout` is computed.
=> Small changes required by the coming layout debugger

Source/ASDisplayNode+Layout.mm, Source/Layout/ASLayoutElement.mm, Source/Layout/ASLayoutElementPrivate.h
This gives us a ton more flexibility for the future.
I'm on vacation so this was a little bit thrown-together, but I'm excited about it! Please give it a thorough review.
The GitHub diff got a little confused, so some lines that didn't change at all appear to have changed, like:
```
CGFloat const ASLayoutElementParentDimensionUndefined = NAN;
CGSize const ASLayoutElementParentSizeUndefined = {ASLayoutElementParentDimensionUndefined, ASLayoutElementParentDimensionUndefined};
```
=> Upgrade ASLayoutElementContext to an Object #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Podfile, Tests/ASCALayerTests.m, Tests/ASMultiplexImageNodeTests.m, Tests/ASUICollectionViewTests.m, Tests/ASViewControllerTests.m, Tests/NSInvocation+ASTestHelpers.h, Tests/NSInvocation+ASTestHelpers.m
Unit tests are great! tl;dr: This diff migrates us from OCMock 2.2 to 3.4, and migrates ASMultiplexImageNodeTests to the latest syntax as a demonstration.
- The new version of OCMock supports a great new syntax, and prints much better error messages.
- There's no urgency to migrate the rest of our existing test cases. I migrated the multiplex image node tests only to provide a better reference for future test development.
- Recommend you use split diff for the multiplex image node tests file since it's changed a lot. The spirit/intention of each test method is preserved.
- The migration of the multiplex image node tests revealed a minor bug.
- Namely that we call `imageForImageIdentifier:` twice if the first time it returns nil. Now #346.
- Bug itself isn't interesting, but the total …
=> Migrate to Latest OCMock, Demonstrate Improved Unit Testing

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASDisplayNode.mm, Source/Base/ASAssert.h, Source/Base/ASAssert.m, Tests/ASDisplayNodeTests.mm
This way we can get valuable information (and not exceptions!) when debugging and also enforce constraints on public API. cc #342
=> Add a Flag to Disable Main Thread Assertions #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASCollectionView.mm, Tests/ASCollectionModernDataSourceTests.m, Tests/ASTestCase.h, Tests/ASTestCase.m, Tests/OCMockObject+ASAdditions.h, Tests/OCMockObject+ASAdditions.m
I was building some new API for collection node, and I decided to create a new, leaner, better test harness and it revealed a major issue (#351) so I'm opening this diff now to get it in the bank.
- New test case superclass `ASTestCase`. Subclass this for new test cases. In its `tearDown` method, it clears all the test case ivars and clears all UIWindows. This majorly helps reduce pollution between test methods.
- New category on `OCMockObject` that lets you specify which optional protocol methods should exist. This is extremely useful because the default behavior is to assume they all exist, which violates framework invariants and makes most testing of complex data sources impossible.
- New test case `ASCollectionModernDataSourceTests.m`.
- Was intended to test some new data source API …
=> Improve collection node testing, reveal double-load issue. #trivial

Source/ASCellNode.h, Source/ASCollectionNode.h, Source/ASCollectionNode.mm, Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASCollectionElement.h, Source/Details/ASCollectionElement.mm, Source/Details/ASDataController.h, Source/Details/ASDataController.mm, Tests/ASCollectionModernDataSourceTests.m, examples/CatDealsCollectionView/Sample/ItemNode.h, examples/CatDealsCollectionView/Sample/ItemNode.m
This is the first of a series of diffs I intend to land over the next couple of days, adding support for view-model backed cell nodes, and eventually optional view-model diffing to drive updates.
There's not much to this first pass. You can provide view models, and they'll get assigned to the cell node and made available by the collection node.
The next pass will add the idea of `-canUpdateToViewModel:` and skip fetching a new node block on `reloadItemsAtIndexPaths:` if the existing cell node can update.
I'll update the CHANGELOG when something more significant happens.
=> Add first-pass view model support to collection node. #trivial

Source/Layout/ASLayoutElement.mm
=> [Performance] Convert ASLayoutElementSize to atomic #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASCellNode.h, Source/ASCellNode.mm, Source/Details/ASDataController.mm, Source/Private/_ASHierarchyChangeSet.h, Source/Private/_ASHierarchyChangeSet.mm, Tests/ASCollectionModernDataSourceTests.m, Tests/ASDisplayNode+OCMock.m
- Add `-(BOOL)[ASCellNode canUpdateToViewModel:]`.
- This, plus the view-model mechanism, may be moved up to ASDisplayNode in the future.
- If we reload an item, and its existing cell node returns `YES` from that, we keep using the same node, and update the view model on a background thread, same as we'd allocate a new node.
- View model change could easily be moved to the main thread in the future.
- Right now we still forward a `reloadItemsAtIndexPaths:` call to the UICollectionView, which may mean a flash for animated updates. Suppressing this call is something we do later.
- Beef up the tests for the new feature.
- Add a workaround for an issue where you cannot make a partial mock out of ASDisplayNodes due to an OCMock bug.
=> Add support for keeping letting cell nodes update to new view models when reloaded. #trivial

CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/Details/ASTraitCollection.h, Source/Layout/ASLayoutSpec.mm, Source/Private/ASDisplayNodeInternal.h, Source/Private/Layout/ASLayoutSpecPrivate.h
This resolves a deadlock case, which might be more common with Yoga (unsure): https://github.com/TextureGroup/Texture/issues/353 .  Fortunately it also simplifies the code.
We should think carefully if there are any transactional locking cases that could cause this to be unsafe. However, I think it has fairly limited usage and is probably appropriate for an atomic.
=> [ASTraitCollection] Convert ASPrimitiveTraitCollection from lock to atomic.

Source/ASTableView.mm
We are accessing the `tableNode` property in `ASTableView` in the batch fetching mechanism on a background thread. The problem is that we overwrite the `tableNode` accessor and calling `ASViewToDisplayNode` what will access the `ASTableView` on a background thread.
With Xcode 9 Apple added the Main Thread Checker and it will catch this issue. You can try it out within the Kittens example.
Fixes the report from @WymzeeLabs in #345
=> [ASTableView] Use ASTableView tableNode property instead of calling ASViewToDisplayNode #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm, Source/Details/ASWeakSet.m, Tests/ASCollectionModernDataSourceTests.m, Tests/ASTestCase.h, Tests/ASTestCase.m, Tests/OCMockObject+ASAdditions.h, Tests/OCMockObject+ASAdditions.m
- Fix unit testing memory leaks caused by mock objects retaining their invocations, which retain their arguments, which may retain the mocks.
- Automatically verify all mocks during `[ASTestCase tearDown]`.
- Add section-object testing to the new collection tests file.
- Better encapsulate unit tests:
- Ensure the autorelease pool is drained, and the dealloc queue is drained, inside of `invokeTest:`.
- Ensure that view controllers aren't retained by windows after test ends (system may retain windows).
- Break retain cycles: `(mockObject -> invocations -> owner -> mockObject)` by automatically registering all mocks created during tests, verifying them, then removing their saved invocations.
- Manually verify that, as of now, no transient objects survive between test cases. No easy way to …
=> Add section-object support to new tests, improve test confinement. #trivial

ASDKListKit/Podfile, Texture.podspec, examples/ASDKgram/Sample/ASCollectionSectionController.m, examples/ASDKgram/Sample/PhotoFeedListKitViewController.m, examples/ASDKgram/Sample/PhotoFeedSectionController.h, examples/ASDKgram/Sample/RefreshingSectionControllerType.h
Spotted #364 asking for an update to support IGListKit 3.0.0. This simply gets ASDKGram updated to use IGListKit 3.0.0, it doesn't make any drastic changes to make use of any of the new stuff added in IGListKit.
We've been using 3.0.0 within Buffer alongside Texture for a couple of releases without any issues.
Worth noting I tweaked the podspec and podfile. Wasn't sure how best to handle that & can totally adjust if needed until a future release of Texture.
=> Updates ASDKGram to use IGListKit 3.0.0

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm, Source/Layout/ASLayoutElement.h, Source/Layout/ASLayoutSpec.mm, Source/Layout/ASYogaUtilities.h, Source/Layout/ASYogaUtilities.mm, Source/Private/ASDisplayNodeInternal.h, examples/ASDKgram/Sample/PhotoCellNode.m
NOTE: Yoga support is still highly experimental and is not
planned to become a supported / documented mode of the framework.
We recommend that most apps use ASStackLayoutSpec and the other
specs: http://texturegroup.org/docs/layout2-layoutspec-types.html
This has one important benefit: fixing the stretching behavior of spacer nodes. In addition, it should help efficiency of Yoga and certainly minimize calls to layoutThatFits:.
In the Yoga layout mode of ASDKgram, note how the timestamp is now correctly at the right-hand side of the screen, as allowed by a flexible spacer node placed in the photo header's horizontal stack:
=> [Yoga] Minimize number of nodes that have MeasureFunc set on them.

Source/ASDisplayNode+Beta.h, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.mm, Source/Base/ASAvailability.h, Source/Layout/ASYogaLayoutSpec.h, Source/Layout/ASYogaLayoutSpec.mm, Source/Private/ASDisplayNodeInternal.h
NOTE: Yoga support is still highly experimental and is not
planned to become a supported / documented mode of the framework.
We recommend that most apps use ASStackLayoutSpec and the other
specs: http://texturegroup.org/docs/layout2-layoutspec-types.html
This reduces complexity of the Yoga integration points, and is
a first step towards further minimization and formalization of
the Yoga footprint in the framework.
=> [Yoga] Delete YOGA_TREE_CONTIGOUS gating and permanently enable. #trivial

docs/_docs/layout-transition-api.md
Fixed typo Contet -> Context when calling `super.animateLayoutTransition`
=> FIXED Typo in Layout Transition Documentation

CHANGELOG.md, Source/ASCollectionNode.mm, Source/ASCollectionView.h, Source/ASCollectionView.mm, Source/Details/ASCollectionInternal.h, Source/Private/ASCollectionView+Undeprecated.h, Tests/ASCollectionModernDataSourceTests.m, Tests/ASCollectionViewTests.mm, Tests/ASDisplayNodeLayoutTests.mm
Resolves #351 
- Make `[ASCollectionView reloadData*]` unavailable, not deprecated. This is breaking API but the methods have been deprecated for going on 7 months.
- We can't reliably tell the difference between clients calling this method, and UICollectionView itself calling this method, so we can't safely override it and change its behavior.
- We now unconditionally forward this call to super. 
- It's OK for clients to blindly call `reloadData` on a view that has been cast to `(UICollectionView *)` but it just won't do what they expect. Nothing will actually change.
- Modify `[ASCollectionNode reloadData*]` to do the real work.
- Update unit tests.
=> Fix double-load issue with ASCollectionNode

Source/Details/ASDataController.mm
One of the most common performance problems in a Texture app occurs when a developer makes multiple edit transactions to a collection / table right after each other, before the processing of the previous operation is finished. In this case, Texture blocks on the completion of the current edit operation, even though it would have been asynchronous if the second / subsequent operation had not been started.
The ASEventLog provides the ability to capture the information on this subtle perf issue. In the -ASDataController updateWithChangeSet: method, we can time the duration of the dispatch group wait of the editing transaction queue and log both the time as well as the stack trace so the developer can see which edit operations are triggering performance issues.
=> [ASDataController] Add event logging for transaction queue flush duration #trivial

Source/ASDisplayNode.mm
Since we're shying away from assertions in favor of event log, let's log the ASM flag in subnode modifications.
=> [Event Log] Log ASM flag when modify subnodes #trivial

Source/ASDisplayNode+Layout.mm
This is causing breaking behaviors for non-Yoga users (aka. Pin). Let's gate it now and roll out later.
=> Gate orphaned node detector behind YOGA flag #trivial

Source/Layout/ASDimension.mm, Tests/ASDimensionTests.mm
Using the layout debugger, users can frequently input an invalid dimension string. Instead of throwing assertion, let's be more lenient and fall back to Auto.
=> ASDimensionMake to be more lenient #trivial

Texture.podspec
=> Horrible spelling mistake #trivial

examples_extra/VideoTableView/Sample/NicCageNode.mm
Should fix up the Video Table Example where size is not found. Reported in Slack.
=> Fix for Video Table Example Building

Source/ASCellNode.mm
The same thing is (and should be) done in [`-layout`](https://github.com/TextureGroup/Texture/pull/387/files#diff-bf3128e7e068b8e2a4e939d402792365R110).
=> [ASCellNode] Remove unnecessary frame setting #trivial

Source/Layout/ASDimension.h, Source/Layout/ASDimension.mm
Exposes the <UIKit/UIGeometry.h> header in ASDimension otherwise under some circumstances UIEdgeInsets is not defined if compiled with Yoga enabled.
=> Fix compiling ASDimension if Yoga enabled #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASDisplayNode+Yoga.mm, Source/Layout/ASLayout.h, Source/Layout/ASLayout.mm, Source/Layout/ASYogaLayoutSpec.mm, Source/Private/ASInternalHelpers.h, Source/Private/ASInternalHelpers.m, Tests/ASLayoutFlatteningTests.m
I'm facing an issue that blocks the first release of Weaver. In order to inspect the whole layout **element** tree that contains both display nodes and layout specs, I have to tell **all** display nodes to skip flattening their calculated layout immediately and only do so when the layout is applied (https://github.com/TextureGroup/Texture/pull/337). When it's time to flatten a layout tree, the tree contains **unflattened** calculated layouts of all nodes in the corresponding node tree. The flattening algorithm doesn't handle this use case well because it relies on `isFlattened` flag of each `ASLayout` object which is never turned on.
The fact that the algorithm relies on that flag also caused a problem with Yoga integration because a Yoga tree is always flattened, but we may forget to set …
=> [ASLayout] Revisit the flattening algorithm

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/Details/ASDataController.mm, Source/Private/ASMutableElementMap.h, Source/Private/ASMutableElementMap.mm
Unfortunately, since supplementary elements are keyed by section index, we have to migrate supplementaries when sections are inserted/deleted. So if you have section 0 with a header, and you insert a section at index 0, that previous header should now be at index path e.g. `{1, 0}`.
So we migrate all supplementary elements when there are section-level changes. This is meant to be a minimal diff to fix the crash, and it was reduced down from the larger change #405 which unifies our index change tracking.
Resolves #397 and (I believe) #385 @Pacek @mrvincenzo
=> Fix issue where supplementary elements don't track section changes

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+Yoga.mm
This ensures that measure funcs are not set for container / empty spacer
nodes, because Yoga has more internal capabilities than layoutThatFits:
knows about.
Avoid need for the main layout pass to directly call setup for measure
funcs, by making it an implicit part of .yogaLayoutInProgress =.
Tear down the measure func after the layout pass to avoid retain cycle.
=> [Yoga] Refine the handling of measurement functions when Yoga is used.

Source/ASDisplayNode+Layout.mm
I believe this check is supposed to be here. Unit tests pass with it in place.
Without it, calling layoutThatFits: (as ASDataController does) and then calling
it again later (as ASCollectionNode does when answering the sizeForItem: call)
will recompute the layout, potentially on main.
This seems to have more of an impact / benefit for Yoga layouts, but I don't think
its benefit is exclusive to them.
=> [ASDisplayNode+Layout] In layoutThatFits:, check and use _pending layout if valid.

Source/ASVideoPlayerNode.mm
The ASVideoPlayerNode delegate flag that indicated whether the delegate implemented the didTapFullScreenButtonNode method wasn't getting used, so I've added the check to the ASVideoPlayerNode's didTapFullScreenButton method.
=> [ASVideoPlayerNode] Check that the video player's delegate implements the didTapFullScreenButtonNode method before calling it #trivial

CHANGELOG.md, Source/Details/ASDataController.mm
- Previously, when a change set is empty, `ASDataController` forwards the change set to its delegate right away, without dispatching to its editing queue and then back to main.
- This behaviour can potentially cause bad internal states in UITableView which trigger a crash reported in #83.
- Fix by still reusing the existing pending map, because the data source's state has not changed, but go through the editing queue and main queue tunnel.
Fixes #83.
=> [ASDataController] Fix a crash in table view caused by executing an empty change set during layoutSubviews

CHANGELOG.md, Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASDataController.h, Source/Details/ASDataController.mm, Source/Details/ASRangeController.h, Source/Details/ASRangeController.mm
Fixes https://github.com/TextureGroup/Texture/issues/378. Tested with the project attached in that report and smoke tested ASDKgram.
=> [ASDataController] Apply new visible map inside batch updates block

Source/ASCollectionNode.mm, Source/ASDisplayNode.mm, Source/ASTableNode.mm
This was originally added for ASCollectionNode and ASTableNode preloading to work
as intended when nested inside of another ASRangeController-powered node. Indeed,
it is still necessary to trigger layout on these UIKit-backed components in order
for their own ASRangeControllers to start preparing content within them.
However, unlike the comment suggests, it is *not* necessary to do this for image
nodes. ASNetworkImageNode has only one .URL, and does not use the .bounds or
.calculatedLayout at all during loading. Even the ASMultiplexImageNode does not
use the .bounds, and the ASMapNode uses .calculatedLayout instead of .bounds.
This change has important performance benefits. In particular, it avoids
layouts that would occur on the main thread, often including text sizing,
and also can …
=> [ASDisplayNode] -didEnterPreloadState does not need to call -layoutIfNeeded #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/Details/ASDataController.mm, Source/Details/ASIntegerMap.h, Source/Details/ASIntegerMap.mm, Source/Private/ASMutableElementMap.h, Source/Private/ASMutableElementMap.m, Source/Private/_ASHierarchyChangeSet.h, Source/Private/_ASHierarchyChangeSet.mm, Tests/ASIntegerMapTests.m, Tests/Common/ASTestCase.m
This is a larger, more risky follow-up to #404 .
This introduces ASIntegerMap, which is a pretty wrapper around unordered_map. It also has some handy logic for generating mappings across updates, and there are singletons for identity and null mappings.
This simplifies and unifies our tracking of index changes at the section and item levels, and improves performance by storing these mappings in an immutable store rather than recomputing them for each query. 
For most updates, most of the mappings will be the shared identity mapping, and it'll be easy to tell.
Note: I know a lot of code was added to _ASHierarchyChangeSet, but it's also become much more powerful. You can now get O(1) bi-directional index path and section index mappings with very little pre-computation cost. 
**Note:** I …
=> Introduce ASIntegerMap, improve our changeset handling #trivial

Source/Private/ASDisplayNode+AsyncDisplay.mm
Without it `AS_KDEBUG_ENABLE` will evaluate to 0 [here](https://github.com/nguyenhuy/Texture/blob/665f8c054f0e95dc83c61e3caa5e7b17bf01a4c4/Source/Private/ASDisplayNode%2BAsyncDisplay.mm#L280).
=> Add missing import in ASDisplayNode+AsyncDisplay #trivial

CHANGELOG.md, Source/ASCollectionView.mm, Source/Base/ASBaseDefines.h, Source/Details/_ASCollectionReusableView.h, Source/Details/_ASCollectionReusableView.m, Source/Details/_ASCollectionViewCell.h, Source/Details/_ASCollectionViewCell.m
- `_ASCollectionReusableView` and `_ASCollectionViewCell` no longer expose getters for their collection element and cell node properties. This is to make sure that clients can only obtain elements from the visible map which is always the source of truth.
- Since the map can return `nil` for an element request, it's much safer to check and avoid adding/removing a nil pointer to an `NSArray`.
- Since we use a special way to check whether an object of kind of `_ASCollectionViewCell` or `_ASCollectionReusableView`, based on the assumption that these classes are subclass restricted, I added cast-or-return  macros in the header files, closer to where the restrictions are declared.
=> [ASCollectionView] Small improvements

Source/Private/ASDispatch.h
Texture fails to build with this error on clang 4.0:
```
external/Texture/pod_support/Headers/Public/AsyncDisplayKit/ASDispatch.h:32:35: error: illegal initializer type 'atomic_size_t' (aka '_Atomic(size_t)')
__block atomic_size_t counter = ATOMIC_VAR_INIT(0);
^
In module 'std' imported from external/Texture/pod_support/Headers/Public/AsyncDisplayKit/ASStackUnpositionedLayout.h:18:
/private/var/tmp/_bazel_bkase/a00d4cbe29902fb63d5778cc19944cd2/external/clang40/bin/../include/c++/v1/atomic:1839:30: note: expanded from macro 'ATOMIC_VAR_INIT'
^
1 error generated.
```
See
http://techqa.info/programming/question/38233019/Initializing-an--atomic-int--with-a-braced-constant--Is-this-valid-C-code--If-so-why-does-it-not-compile-in-clang-
Replacing the intialization with just 0 (and not the macro …
=> Workaround clang4.0 <stdatomic.h> initialization #trivial

Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Details/UIView+ASConvenience.h, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASCoreAnimationExtras.h, Source/Private/_ASCoreAnimationExtras.mm, Source/Private/_ASPendingState.mm
This makes it much easier to use the ASCoreAnimationExtras method which offers by
far the most efficient way to display a stretchable image.
In the future, we should move that function to UIImage+ASConvenience or another
header where it can be more easily found and enjoyed!
=> [ASDisplayNode] Allow setting stretchable contents on nodes; add bridged properties. #trivial

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h, Source/Private/ASDisplayNodeLayout.h, Source/Private/ASDisplayNodeLayout.mm
Instead of pushing an `invalidate()` call onto display node layouts, and having a dirty flag on them, use an atomic counter that represents a node's layout data state.
This makes it easier to control checkpoints and avoid accidentally using stale layout data.
=> Use a sentinel NSUInteger for node layout data #trivial

Source/Private/_ASPendingState.mm
I audited this more carefully and found some gaps in my PR from yesterday.
This also ensures the grouping and ordering of all the contents properties
is consistent across all of the places they appear.
In the future, it would be great to make the #define macros more sophisticated
so that we can add property bridging with fewer lines changed, and for
objects besides ASDisplayNode too!
=> [ASDisplayNode] Fix some gaps in the bridging of new contents* properties.

CHANGELOG.md, Source/Details/ASDataController.mm
- Elements are not allocated and measured in batches anymore. Remove the code that does batch allocation.
- The value returned by `-_allocateNodesFromElements:andLayout:completion` is not used. Remove it.
- Remove `+parallelProcessorCount`.
- Remove `RETURN_IF_NO_DATASOURCE` macro. It's used only once and is not worth it.
=> [ASDataController] Clean up

Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASDataController.h, Source/Details/ASDataController.mm, Source/Details/ASRangeController.h, Source/Details/ASRangeController.mm
After #420, there is no change occurs between those 2 methods. Having them separately doesn't achieve anything and can cause confusions.
=> [ASDataController ] Merge willUpdateWithChangeSet and didUpdateWithChangeSet delegate methods #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASPagerNode+Beta.h, Source/ASPagerNode.m, Source/Details/ASCollectionFlowLayoutDelegate.m, Source/Details/ASCollectionGalleryLayoutDelegate.h, Source/Details/ASCollectionGalleryLayoutDelegate.m, Source/Details/ASCollectionLayoutContext.m, Source/Details/ASCollectionLayoutDelegate.h, Source/Details/ASCollectionLayoutState.h, Source/Details/ASCollectionLayoutState.mm, Source/Private/ASCollectionLayout.mm, examples/ASCollectionView/Sample/ViewController.m, examples/CustomCollectionView/Sample/MosaicCollectionLayoutDelegate.m
- This allows users to return different sizes based on certain conditions, such as the collection node's bounds or grid constants.
- ASPagerNode will also act as a size provider to ensure all pages have an up-to-date size that is its bounds.
=> [ASCollectionLayout] Add ASCollectionGalleryLayoutSizeProviding

CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm
The problem was introduced by #428. It will occur if a node does either of the followings:
1. Keeps using a stale pending layout over a calculated layout
2. Doesn't update the next layout's version after calling `_setNeedsLayoutFromAbove`.
=> [ASDisplayNode] Fix infinite layout loop

CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASNetworkImageNode.mm
This is a further fix to #464 that addresses the additional case mentioned in #463 as a follow-up.
`transitionLayoutWithSizeRange` is now an unconditional layout invalidation, unless the transition is canceled using the pre-existing logic. 
As ridealongs, I added a `detailedLayoutDescription` property to ASDisplayNode that can be useful when debugging, and I fixed two tiny instances of stale code that caused build errors when verbose logging was enabled. cc @appleguy as this new property may be particularly handy for you, as LLDB does not play well with the C++ structs we use for display node layouts.
=> Invalidate layouts more aggressively when transitioning with animation

CHANGELOG.md, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode.mm, Source/ASNodeController+Beta.h, Source/ASNodeController+Beta.m
With these changes, I'd also like to propose that we move ASNodeController
out of Beta (renaming the files without +Beta). Let me know what you think!
Because we don't support ASNodeController directly in ASCV / ASTV, it is still
important to allow flipping the ownership in certain cases (in particular, for
root CellNodeController objects that should follow the lifecycle of the
ASCellNode rather than owning the ASCellNode).
=> [ASNodeController] Add -nodeDidLayout callback. Allow switching retain behavior at runtime.

CHANGELOG.md, Source/Layout/ASStackLayoutSpec.h, Source/Layout/ASStackLayoutSpec.mm, Source/Private/Layout/ASStackLayoutSpecUtilities.h, Source/Private/Layout/ASStackPositionedLayout.mm, Source/Private/Layout/ASStackUnpositionedLayout.mm
Hi guys,
I haven't opened an issue / feature request for this, but here it is, a PR that fixes a small bug in the flex wrap layout, and add a nice property to it.
- The first commit fixes a bug where spacing is not taken into account when splitting items in lines. This causes items to overflow the allowed size range in certain cases. Specifically, too many items can be added to a line because the line length doesn't keep track of spacing. See the demo project for an example.
- The second commit adds the `lineSpacing` property to the `ASStackLayoutSpec` that... well... adds space between lines. I tried to keep changes as minimal as possible, tell me what you think!
As usual, here's a small [demo project](https://github.com/flovouin/Texture-FlexWrapBugs) that demonstrates the bug and the …
=> [ASStackLayoutSpec] Flex wrap fix and lineSpacing property

docs/showcase.md
Based on email response from @garrettmoon - opening PR for showcase site update with new blog post link added to ClassDojo icon.
=> [Showcase] Update showcase - add blog post link to ClassDojo icon #trivial

CHANGELOG.md, Source/ASDisplayNode+Layout.mm
=> [Layout Transition] Avoid calling didComplete method if pending layout transition is nil

CHANGELOG.md, Source/ASTableView.mm, Source/Base/ASAvailability.h
Starting in iOS 11 `UITableView` automatically uses estimated heights. ([Source](https://twitter.com/smileyborg/status/871858815053946880))
This causes some odd behaviour in Texture, specifically with batch fetching where a lot of jumping can happen when the load occurs. 
[User djug](https://asyncdisplaykit.slack.com/archives/C0V63R86T/p1500761127076778) in the Slack encountered this issue earlier and posted their solution which is the basis for this, and is as simple as re-disabling the new default behaviour so that automatic height estimation does **not** occur.
In order to let this occur only on iOS 11 (not sure if there's any pre-iOS-11 code running on the assumption of the old default, don't want to cause a regression) I made it only occur on iOS 11 and later. This required an …
=> iOS 11 UITableView automatic height estimation fix

CHANGELOG.md, Source/ASCellNode.h, Source/ASCellNode.mm, Source/Details/ASCollectionElement.mm, Tests/ASCollectionModernDataSourceTests.m
Thanks to @Kaspik and slack users mlilek, jdeguzman, and emre for reporting the issues this collision has caused in their apps.
This is an implementation of a proposal from @Kaspik to rename the field to `nodeViewModel`. This will be a breaking change for users who have already modified their product code to account for the collision.
As the implementor of the `viewModel` field, I take responsibility for all the effort y'all went through to adapt to it. Sorry. Hopefully this patch isn't too late to save some of you a lot of effort.
Everyone let me know what you think about this.
=> Rename -[ASCellNode viewModel] to -[ASCellNode nodeViewModel] to avoid collisions

CHANGELOG.md, Source/ASDisplayNode.mm
We are seeing a crash in Pinterest like the one attached below.
I don't know why the re-entrant call to self.view would not return immediately (since _view is not nil as guaranteed by the `_loadViewOrLayer` method), and I don't know why we're getting a KERN_PROTECTION_FAILURE,  but either way, I believe this is the correct code for the `_locked_` method.
=> Avoid re-entrant call to self.view when applying initial pending state

CHANGELOG.md, Source/Private/ASCollectionLayout.mm
Reported by @wsdwsd0829 [here](https://github.com/TextureGroup/Texture/pull/450#discussion_r132855870). 
Reproducible in "examples/ASCollectionView" by enabling `ASYNC_COLLECTION_LAYOUT` and popping the view controller after just 2 seconds ([this line
](https://github.com/TextureGroup/Texture/blob/master/examples/ASCollectionView/Sample/ViewController.m#L96)). The crash occurs when a containing view controller is popped out right after its collection view finished a batch update, but before an update animation settles. As soon as the view controller is deallocated, its collection view's layout is invalidated. Then when the update animation stops, it asks for the layout's content size and triggers the assertion. Fix by returning a zero size instead.
=> ASCollectionLayout to return a zero content size if its state is unavailable

CHANGELOG.md, Source/Details/ASCollectionLayoutState.mm, Source/Private/ASCollectionLayout.mm, Source/Private/ASCollectionLayoutState+Private.h
- During the first layout calculation, measure more than just elements in the visible viewport.
- Remove unncessary params in `-[ASCollectionLayoutState getAndRemoveUnmeasuredLayoutAttributesPageTableInRect]`.
=> ASCollectionLayout improvements

CI/exclude-from-build.json
Updating these files, CHANGELOG.md for example, shouldn't cause CI to run tests and build examples again.
=> [CI] BuildKite to ignore all markdown files

CHANGELOG.md, Source/ASImageNode+AnimatedImage.mm
My debugging showed that this is causing a strong retain cycle and causes ASVideoNode to never deallocate.
=> ASImageNode+AnimatedImage playbackReadyCallback retain cycle

CHANGELOG.md, Source/ASCollectionNode.h, Source/ASCollectionNode.mm, Source/ASCollectionView.h, Source/ASCollectionView.mm, Source/ASTableNode.h, Source/ASTableNode.mm, Source/ASTableView.h, Source/ASTableView.mm, Source/Details/ASDataController.h, Source/Details/ASDataController.mm, Source/Details/ASMainSerialQueue.h, Source/Details/ASMainSerialQueue.mm, Tests/ASCollectionModernDataSourceTests.m, Tests/ASCollectionViewTests.mm, Tests/ASTableViewTests.mm
Over time, there have actually been a lot of legitimate uses for an API like this.
In fact, I'm not quite sure what has held us back from adding one!
I believe that at least some portion of -wait calls (even if less than 50%) could be
replaced with -onDidFinishProcessingUpdates:, which could potentially improve the
performance of applications using -wait by a significant amount.
Please take a close look at implementation correctness. Although I'm in a bit of a
rush, I'm aiming to make this properly documented and added a basic test -- but it
could certainly use some more detailed testing as a followup.
=> [ASCollectionNode] Add -isProcessingUpdates and -onDidFinishProcessingUpdates: APIs.

CHANGELOG.md, Source/ASEditableTextNode.h, Source/ASEditableTextNode.mm
=> SEP-491 prerequisite: add textViewShouldBeginEditing: to ASEditableTextNodeDelegate

CHANGELOG.md, Cartfile, Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.m, Texture.podspec
This allows PINRemoteImage to download from a set of URLs depending on network conditions.
More context perhaps:
https://github.com/pinterest/PINRemoteImage/pull/407
https://github.com/pinterest/PINRemoteImage/pull/403
=> Adds support for specifying a quality indexed array of URLs

CHANGELOG.md, Source/Private/ASCollectionLayout.mm
Failing to do this will cause `ASCollectionLayout` to report a content size that spans beyond the safe scrollable area of the collection node. In case of `ASPagerNode`, that then causes the pager to bounce vertically and messes up with the pull-to-dismiss gesture in closeup.
=> [ASCollectionLayout] Exclude content inset on scrollable directions from viewport size

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm, Tests/ASRunLoopQueueTests.m
I wrote a failing tests for [#518](https://github.com/TextureGroup/Texture/issues/518). Then made it pass.
Apparently, the problem is `NSPointerArray` won't be marked as `needsCompaction` when stored weak pointers become NULL. This makes subsequent calls to `compact` to return early without effectively removing NULL's. As a result `ASRunLoopQueue` is never marked as drained, event though there is no more work to do.
I added an `isEmpty` public property to `ASRunLoopQueue` which is only used in tests. That's not pretty, but I went this way because IMO the property makes sense in an API like that (if you have a queue, it's very natural to have a way to know if it's empty). If you don't want to have this property, we need to find out another way for the test to _sense_ that the queue has …
=> Mark ASRunLoopQueue as drained if it contains only NULLs

CHANGELOG.md, Source/ASImageNode.mm, Source/ASNetworkImageNode.mm
Moving this logic from `ASNetworkImageNode` down to `ASImageNode` so `ASMultiplexImageNode` can benefit from it as well.
=> [ASImageNode] Always dealloc images in a background queue

Source/ASCollectionNode.mm
`-[ASCollectionNode didLoad]` transfers contentInset from the `pendingState` to the newly materialized `ASCollectionView`'s `contentInset` . However for `ASPagerNode`, this action triggers `-[ASCollectionNode contentInset]` which in turns calls `-[ASCollectionNode pendingState]` before the `pendingState `is cleared on the pager node, thereby prematurely triggering the assert:
```
ASDisplayNodeAssert(![self isNodeLoaded] || !_pendingState, @"ASCollectionNode should not have a pendingState once it is loaded");
```
To fix this we clear out the pending state on the node before transferring the `pendingState` properties to the` ASCollectionView`
=> Fix -[ASPagerNode view] triggering pendingState + nodeLoaded assert #trivial

Source/Details/ASElementMap.m
when indexPath's section or item is actually negative that is invalid。
=> [ASElementMap] Fix indexPath's section or item is actually negative #trivial

CHANGELOG.md, Source/ASImageNode.mm, Source/ASTextNode.mm, Source/ASTextNode2.mm, Source/Details/ASBasicImageDownloader.mm, Source/Details/ASThread.h, Source/Private/ASBasicImageDownloaderInternal.h, Source/TextKit/ASTextKitContext.mm
This is an interesting crash. Here is an example report in Pinterest app, happening on the static `cacheLock` mutex of `ASImageNode`:
There are other similar crashes related to `__staticMutex` in `ASTextKitContext` reported in https://github.com/TextureGroup/Texture/issues/136. For instance, see thread #0 and #5 in [this report](http://crashes.to/s/7d0c464960f), or thread #0 and #14 [here](http://crashes.to/s/e43ab8f7d5c).
Basically, what's happening is that all static mutexes are destroyed when an app is terminated by the system. At the same time, a static mutex is being unlocked or destroyed on another thread. The unlock or destruction yields a non-zero error code, which triggers an assertion, even in production.
A similar issue was discussed and fixed in Realm-Core …
=> Fix crashes caused by failing to unlock or destroy a static mutex while the app is being terminated

Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASPendingState.mm, Tests/ASDisplayNodeTests.mm
- Fix crashes caused by https://github.com/TextureGroup/Texture/pull/554
=> [_ASPendingState] Make sure accessibility strings are not nil before allocating attributed strings for them #trivial

CHANGELOG.md, Source/ASImageNode+AnimatedImage.mm, Source/Private/ASImageNode+AnimatedImagePrivate.h
Found a dumb deadlock thanks to @djblake
=> Use node lock instead of separate one to avoid deadlocks.

Source/ASDisplayNode.mm
After scheduling the ivar for main thread deallocation we have clear out the ivar, otherwise we can run into a race condition where the main queue is drained earlier than this node is deallocated and the ivar is still deallocated on a background thread
=> Clear ivar after scheduling for main thread deallocation #trivial

docs/_docs/faq.md
Right now the faq- table of contents has links to the different headlines that are mentioned in the faqs, but some of the generated id s don't match the referencing
a tag.
=> update faq toc links to match the generated html id #trivial

CHANGELOG.md, Source/Details/ASPINRemoteImageDownloader.m
This default is fairly low - only 20MB - but for most apps with images
in the size range of 10-50KB, this is still 400-1000 images.
Once some optimizations land to PINCache, we'll match the PINCache
default of 50MB to ensure the default better serves users with larger
objects in the cache.
Apps should preferably set their own byteLimit to an optimal value.
@garrettmoon - one interesting question for us is the best place to
set .byteLimit as an app. Digging into the ASPINRemoteImageDownloader
and doing this type cast is a bit complicated, so a passthrough API
to get the PIN* objects directly might be worthwhile.
=> [PINCache] Set a default .byteLimit to reduce disk usage & startup time.

Source/Private/ASInternalHelpers.m
Certain objects need to be deallocated on main. We have an automatic mechanism were it goes through each ivar and checks if the object needs to be deallocated on main or not. We have to add `ASTextKitComponents` to this list of classes now.
There are multiple ways to tackle this issue, this PR just adds the class right into the method that checks for classes who should be deallocated on main. It will have the problem as we check it with a string comparison if we change the name of the ASTextKitComponents we could miss this change in here as well as if we would like to add new classes this can easily hard to maintain.
I will follow up with a PR that is more flexible approach, but it will add some overhead.
Adresses #586
=> ASTextKitComponents needs to be deallocated on main

CHANGELOG.md, Source/ASVideoNode.mm
Hi guys,
I was adding a custom seek bar to a video node, and noticed that when changing the played video, I was still getting `didPlayToTimeInterval` delegate calls for the old video.
You can easily see what I mean in [this sample project](https://github.com/flovouin/Texture-VideoNodeObserver).
The video is reloaded after 2 seconds, and after that, the progress bar goes crazy, switching back and forth between the time info of the two players.
Not releasing the time observer also means that the former video keeps playing in the background, and hence seems to increase CPU consumption (twice the load on my device).
The fix is simple: actually release the time observer when removing the player. Because the observer is linked to the player, I just moved allocation/deallocation of the observer …
=> [ASVideoNode] Time observer fix

Source/ASNetworkImageNode.mm
Good catch by @djblake, if you scroll fast enough, you leave images
set on the image node because didExitPreloadRange (which would have
cleared it) was already called.
=> Don't set download results if no longer in preload range.

Source/TextKit/ASTextKitComponents.h, Source/TextKit/ASTextKitComponents.mm
https://github.com/TextureGroup/Texture/pull/603 unnecessarily triggers assertions when temporary components that are created [here](https://github.com/TextureGroup/Texture/blob/master/Source/TextKit/ASTextKitComponents.mm#L84) and [here](https://github.com/TextureGroup/Texture/blob/master/Source/TextKit/ASTextKitComponents.mm#L104) are deallocated off the main thread. Fix (and close https://github.com/TextureGroup/Texture/issues/607) by not asserting on these objects.
=> [ASTextKitComponents] Temporary components can be deallocated off main #trivial

examples/AnimatedGIF/ASAnimatedImage/ViewController.m
Pinterest is deprecating \*media-cache-\* URLs. s-media-cache-ak0.pinimg.com 301's to i.pinimg.com.
```
➜  curl -svo /dev/null https://s-media-cache-ak0.pinimg.com/originals/07/44/38/074438e7c75034df2dcf37ba1057803e.gif 2>&1 | grep "< "
< HTTP/1.1 301 Moved Permanently
< Location: https://i.pinimg.com/originals/07/44/38/074438e7c75034df2dcf37ba1057803e.gif
...
```
=> update Pinterest CDN URL in example code

Source/ASEditableTextNode.mm, Source/TextKit/ASTextKitComponents.h, Source/TextKit/ASTextKitComponents.mm, Tests/ASTextKitTests.mm
Currently the checker is triggered either when the components need to get the backing text view's bounds, or when the text view's delegate is cleared out during deallocation.
In the first case, I add a new subclass of UITextView that has a thread-safe bounds property and is used exclusively by ASTextKitComponents.
The second case is handled in #598. However, a new main thread assertion added in #603 causes background deallocations of temporary components to fail. #610 attempts to fix that, but since temporary components don't have a reference to a text view, it's fine to avoid the assertion altogether.
=> [ASTextKitComponents] Make sure Main Thread Checker isn't triggered during background calculations #trivial

CHANGELOG.md, Source/ASCollectionView.mm
If we've changed our leading screens for batch fetching, we
may need to batch fetch.
=> Check if we need to do a batch update

AsyncDisplayKit.xcodeproj/project.pbxproj, Tests/ASNavigationControllerTests.m
The **ASNavigationController** override some UIKit functions.
The unit tests are just here to be sure that the normal behavior of a **UINavigationViewController** is working as expected.
=> [Tests] Introducing tests for the ASNavigationController

Tests/ASPagerNodeTests.m
Tiny PR to add test **scrollToPageAtIndex** for the **ASPagerNode**
=> [Tests] Add test scrollToPageAtIndex ASPagerNode

CHANGELOG.md, Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm, Source/Details/ASPINRemoteImageDownloader.m
This should help consumers who are interested in tracking their image cache performance.
=> Have ASNetworkImageNode report whether images were cached or not

Source/ASCollectionView.mm
This allows rotation to work properly when rotating UIKit passthrough
cells that need to change width.
This diff was written and tested for use with #431, but it's fundamentally the same with the current HEAD.
=> [ASCollectionView] Call -invalidateFlowLayoutDelegateMetrics when rotating. #trivial

docs/_docs/inversion.md
Append swift example at inversion example
=> [Documentation] Update Inversion Docs

CHANGELOG.md, Source/Base/ASAvailability.h, Source/Details/_ASDisplayView.mm, Source/Details/_ASDisplayViewAccessiblity.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASPendingState.mm
- Introduces `AS_AVAILABLE_IOS(x)` macro.
- When possible, evaluates to `__builtin_available(iOS x, *)` – same as `@available` but valid in C/C++.
- Otherwise evaluates to the runtime version check `AS_AT_LEAST_IOSx` – checking CFCoreFoundationVersionNumber.
- Changes our attributed accessibility implementations not to use KVC. Instead we check both the SDK version and the runtime version. It's a little ugly but it's correct on both versions of Xcode, and it scales better (and faster!). cc #642 which does some of this same stuff.
- Removes an old `#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_6_0` check. Sorry iOS 5 SDK users 😢
=> Make the framework backwards compatible with Xcode 8

CHANGELOG.md, Source/ASCollectionView.mm, Source/ASDisplayNode.mm, Source/ASDisplayNodeExtras.h, Source/ASDisplayNodeExtras.mm, Source/ASImageNode.mm, Source/ASMultiplexImageNode.mm, Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm, Source/ASTableView.mm, Source/ASViewController.mm, Source/Private/ASInternalHelpers.h, Source/Private/ASInternalHelpers.m
In order to be sure we've released our local reference before the queue releases its reference, we need to pass a double-pointer.
Minor breaking API changes in this diff:
- `ASPerformBackgroundDeallocation(x) -> ASPerformBackgroundDeallocation(&x)`
- Swift: `ASDeallocQueue.sharedDeallocationQueue() -> ASDeallocQueue.sharedDeallocationQueue`
- `ASPerformMainThreadDeallocation(x) -> ASPerformMainThreadDeallocation(&x)`
=> [Minor Breaking API] Make deallocation queues more reliable

CHANGELOG.md, Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASDataController.mm, Source/Details/ASElementMap.h, Source/Details/ASElementMap.m, Source/Private/ASMutableElementMap.h, Source/Private/ASMutableElementMap.m, Source/Private/ASSection.h
Previously, there was no native way to map between sections. So our best shot was to pick item 0 and translate its index path, and then read the section index. This has a couple of failure modes:
- There is no item 0 in the "from" map (empty section)
- Item 0 is deleted, reloaded, or moved in the change
To fix this and provide more direct section tracking, we:
- Always create `ASSection` objects, even if the data source provides no context for them.
- Do the mapping between these. It's fast O(N) – shouldn't be an issue.
In the future I hope we can go further with `ASSection` but this is a good start.
=> Make it possible to map between sections even if they're empty

docs/_docs/containers-asnodecontroller.md
When Obj-C is selected on this page, the bottom half of the documentation is missing. When Swift is selected, malformed content appears where the documentation and subsequent code blocks are nested inside the first code block.
Repro'd here in Safari and Chrome: http://texturegroup.org/docs/containers-asnodecontroller.html
I think the bug is that &lt;PhotoCellNode&gt; is being parsed as an HTML tag, and this should fix it.
=> Fix bug that breaks ASNodeController docs page

docs/_docs/layout2-api-sizing.md
This fixes the broken documentation here: http://texturegroup.org/docs/layout2-api-sizing.html
=> Add missing </div> tags in Layout API Sizing docs

CHANGELOG.md, Source/ASDisplayNode+Layout.mm
Before:
- Even if a pending layout was applied before, it'll be unnecessarily applied again in next layout passes and cause `-calculatedLayoutDidChange` being called multiple times.
After:
- If a pending layout was applied, the calculated layout will not be ignored but reused, if possible, in next layout passes.
Test plan: `testSetNeedsLayoutAndNormalLayoutPass` in #424.
=> [ASDisplayNode+Layout] Ensure a pending layout is applied once

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm, Source/Details/_ASDisplayLayer.mm, Source/Layout/ASLayout.mm, Source/Private/ASDisplayNode+FrameworkPrivate.h, Tests/ASLayoutEngineTests.mm, Tests/ASLayoutTestNode.h, Tests/ASLayoutTestNode.mm, Tests/ASTLayoutFixture.h, Tests/ASTLayoutFixture.mm, Tests/Common/ASTestCase.h, Tests/Common/OCMockObject+ASAdditions.h, Tests/Common/OCMockObject+ASAdditions.m, Tests/Common/debugbreak.h
This adds a testing platform and some unit tests to the layout engine. Right now there are flags to toggle between the current behavior and the desired behavior, and they're set to "current behavior."
Issues reproduced (need to merge with GitHub issues):
- Extraneous `calculatedLayoutDidChange` calls. Not a biggie.
- If a layout pass comes in mid-transition, we will calculateLayout: for some nodes against their current bounds on main, but discard the result. https://github.com/TextureGroup/Texture/pull/424/files#diff-b1441b7e61c34b6f132da6c94bb10c0cR125
- If we do `setNeedsLayout` and get a layout pass while a transition is measuring, the transition's "to-layout" will win, but the setNeedsLayout+layoutPass should actually win since its data is newer. …
=> Add unit tests for the layout engine

CHANGELOG.md, Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.m
#557 
This reverts commit 3c77d4a5da44c46c7b80b2a627c95389b7d6352d.
This removes support for specifying multiple URLs on an ASNetworkImageNode. We decided to remove this for now because of the added complexity and the confusion between this and ASMultiplexImageNode.
This functionality may return at some point in another form.
=> Revert Adds support for specifying a quality indexed array of URLs

CHANGELOG.md, Source/ASDisplayNode.mm, Tests/ASDisplayNodeImplicitHierarchyTests.m
This makes sure subnodes are inserted and start preloading right away, instead of waiting until the next layout pass of the supernode. Fixes #693.
=> Ensure an ASM enabled node applies its pending layout when enters preload state

Source/ASNetworkImageNode.mm
Without this, the image node will not attempt to refetch the image when it enters the preload range again later.
=> #trivial Fixes image nodes being stuck not being able to download image

Source/ASCollectionView.mm, Source/ASTableView.mm
This protects `ASTableView`'s `willDisplayCell:forRowAtIndexPath:` and `didEndDisplayingCell:forRowAtIndexPath:` against nil elements, matching the behaviour added to `ASCollectionView` on #421. Should fix the crash reported in #709.
I also added `consumesCellNodeVisibilityEvents` to `_ASTableViewCell`, again to resemble the implementation of its counterpart `_ASCollectionViewCell`.
Any feedback is very much welcome.
=> [ASCollectionElement] Check for nil elements on ASTableView as well.

CHANGELOG.md, Source/ASCollectionView.mm
Now `collectionNode:willDisplaySupplementaryElementWithNode:` and `collectionNode:didEndDisplayingSupplementaryElementWithNode:` of `ASCollectionDelegate` aren't called in any conditions. It's happening because corresponding flags aren't added to `_asyncDelegateFlags`. My pull request fixes this issue.
=> Add missing flags for ASCollectionDelegate

Source/Base/ASLog.h, Source/Base/ASLog.m
PR #528 (and related issue #524) provided a mechanism to disable logs at runtime. In most of my apps, I like to expose a menu in debug builds which allows me to toggle logs of certain types on/off at runtime. 
This PR adds an `ASEnableLogging()` function which parallels the existing `ASDisableLogging()`, so that logs can be toggled, rather than only disabled.
=> Add support for toggling logs off and back on at runtime

CHANGELOG.md, Source/ASCollectionNode.h, Source/ASCollectionView.mm, Source/Details/ASDataController.mm, Source/Layout/ASLayoutElement.h, Source/Private/ASCollectionLayout.mm, examples/ASCollectionView/Sample/ViewController.m
This patch enables interactive movement for collection node items and updates the `ASCollectionView` example to showcase it.
Caveats:
- Item movement is disabled when using async collection layout. See the comment at the top of `- (BOOL)collectionView:(UICollectionView *)collectionView canMoveItemAtIndexPath:(NSIndexPath *)indexPath` for details.
- When the item is dropped, a new node will be created for it, so it may flash while it's rendered. This is because our change set currently represents moves as delete/insert so the old node is discarded.
To use:
- Have your data source implement `collectionNode:moveItemAtIndexPath:toIndexPath:`.
- Optionally, implement `collectionNode:canMoveItemWithNode:`. As with UIKit, this defaults to `YES` as long as you implement the move method.
- Use the …
=> Enable collection node interactive moves

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Dangerfile, Source/ASDisplayNode.mm, Source/ASImageNode.mm, Source/ASMapNode.mm, Source/ASTextNode.mm, Source/AsyncDisplayKit.h, Source/Debug/AsyncDisplayKit+Debug.m, Source/Details/ASGraphicsContext.h, Source/Details/ASGraphicsContext.m, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/UIImage+ASConvenience.m, examples/ASDKgram/Sample/AppDelegate.m
Normally `UIGraphicsGetImage` makes a copy of the bitmap data. Since we are done with the context, we don't need to waste time and memory making a copy. **We quickly rack up hundreds of megabytes of total allocations from our CGImages** and even though they're reclaimed, it's inefficient. For uncached ASImageNode renders, this happens _twice_ per draw (opportunity: once we generate the cached contents, return them to ASDK intact rather than drawing them.)
**The end result is that ASGraphicsGetImageAndEndCurrentContext is virtually free, while UIGraphicsGetImageFromCurrentImageContext and CGBitmapContextCreateImage are two of the most time- and memory-intensive functions we call.** It turns out that CALayer `_display` does basically the same thing.
Another very very big win here is that, …
=> Add an experimental "no-copy" renderer

Dangerfile, Source/ASTextNode.mm, examples/CustomCollectionView/Sample/AppDelegate.m
Fixes #745 
I added a TODO inside of a "post-Texture-modified" file to test the new dangerfile.
=> Update dangerfile for 2018 #trivial

CHANGELOG.md, Source/ASDisplayNode.mm
After #706, a layout pass is forced on an ASM-enabled node that enters preload state to make sure that its subnodes can start preloading as well. However, when the node is visible, a (coalesced, thus more efficient) layout pass will be triggered by CA soon anyways, so rely on it instead.
=> [ASDisplayNode] Don't force a layout pass on a visible node that enters preload state

AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit.xcscheme, CHANGELOG.md, Source/ASCollectionView.mm, Source/ASDisplayNode+Yoga.mm, Source/ASTableView.mm, Source/Base/ASBaseDefines.h, Source/Details/ASCollectionFlowLayoutDelegate.m, Source/Details/ASCollectionGalleryLayoutDelegate.mm, Source/Details/ASElementMap.h, Source/Details/ASElementMap.m, Source/Layout/ASLayout.mm, Source/Layout/ASLayoutSpec.mm, Source/Private/ASTwoDimensionalArrayUtils.m, Source/_ASTransitionContext.m
The idea here is, standardize on `ASArrayByFlatMapping` and make that macro faster and return an immutable array.
Immutable arrays mean (1) free copying, and (2) free zero-arrays and optimized singleObjectArrays, which means less retaining/releasing. Yay!
I haven't profiled this yet. Just want to put it out there.
=> Faster collection operations

AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit.xcscheme, CHANGELOG.md, Source/ASCollectionView.mm, Source/ASDisplayNode+Yoga.mm, Source/ASTableView.mm, Source/Base/ASBaseDefines.h, Source/Details/ASCollectionFlowLayoutDelegate.m, Source/Details/ASCollectionGalleryLayoutDelegate.mm, Source/Details/ASElementMap.h, Source/Details/ASElementMap.m, Source/Layout/ASLayout.mm, Source/Layout/ASLayoutSpec.mm, Source/Private/ASTwoDimensionalArrayUtils.m, Source/_ASTransitionContext.m
Reverts TextureGroup/Texture#748
I should have  marked that diff is not ready to land. I need to address the issue that, if you call `mutableCopy` on an array created using our custom callbacks, the copy will not retain its objects.
I have a solution, but until I implement it (tonight?) this isn't 100% production-safe.
=> Revert "Faster collection operations"

Source/ASImageNode.mm, Source/Details/ASGraphicsContext.h
Because I forgot to replace this `UIGraphicsEndImageContext` call with its `ASGraphics` version, if you have the experiment enabled and this branch is taken then the image buffer will not be freed.
=> NoCopyRendering experiment: Fix possible memory leak if image node rendering is canceled #trivial

CHANGELOG.md, Source/ASDisplayNode.mm, Source/Details/ASGraphicsContext.m, Source/Private/ASInternalHelpers.m, Tests/ASDisplayNodeTests.mm
This PR achieves the following:
- *Critical* Fixes an issue with no-copy rendering where images with bytes-per-row not aligned to 32 have to be copied by CoreAnimation.
- Removes our `+load` method by changing `ASScreenScale` to use `UIGraphics` which is thread-safe.
- Prevents leaks if users fail to close their ASGraphics contexts.
- ASGraphics creates images in the device-specific (wide color) space, same as plain UIGraphics. This doesn't seem to matter as far as I can tell – CA will not copy the image in either case, but still best to copy UIGraphics.
- Always read fields from "reference" UIGraphics contexts so that if they change we are covered.
=> Improve no-copy rendering experiment, remove +load method

Source/Details/_ASDisplayView.h, Source/Details/_ASDisplayView.mm
For an upcoming diff I need to have access to the node of the `_ASDisplayView`. To be aligned with `_ASDisplayLayer` we should expose it the same way. We exposed it within https://github.com/facebookarchive/AsyncDisplayKit/pull/2346/files for `_ASDisplayLayer`
=> Expose asyncdisplaykit_node in _ASDisplayView same as in _ASDisplayLayer #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASMultiplexImageNode.mm, Source/ASNetworkImageLoadInfo.h, Source/ASNetworkImageLoadInfo.m, Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm, Source/AsyncDisplayKit.h, Source/Details/ASBasicImageDownloader.h, Source/Details/ASBasicImageDownloader.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.h, Source/Details/ASPINRemoteImageDownloader.m, Source/Private/ASNetworkImageLoadInfo+Private.h, Tests/ASBasicImageDownloaderTests.m, Tests/ASMultiplexImageNodeTests.m, examples/ASDKgram/Sample/PhotoCellNode.m
`PINRemoteImage` recently gained support for retrieving the raw network response from image downloads.
In order to pipe this data to the application layer, network image nodes need to retrieve it and pass it through.
This diff is **minor breaking API** (see changelog) but since the `didLoadImage:info:` method was only added recently https://github.com/TextureGroup/Texture/pull/639 and since the migration pathway is trivial, I think we can release it in the next minor version.
Introduces class `ASNetworkImageLoadInfo` which includes source type, URL, download identifier, and a new `id userInfo` field.
Basic image downloader sends `nil`.
PIN image downloader sends `PINRemoteImageManagerResult`.
The URL is useful as well since, given that we unlock before calling out to the delegate, the …
=> Add support for providing additional info to network image node delegate

examples/ASDKgram/Sample/PhotoFeedModel.m, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoFeedModel.swift
When there are no additions to the collection, `numberOfAdditionsCompletion` (and therefore `completeBatchFetching`) is called on a background thread instead of the main thread.
This issue has not come up in this example because the user would have to scroll literally 1000 pages in order to experience it. This is important to fix to maintain consistency in the examples.
=> Fixed: completeBatchFetching is called on a background thread

CHANGELOG.md, Source/ASDisplayNode.mm
This reverts #751 (commit 2e9858837251cf16c9ffd19ba2eaeaa1012c8977).
The reason we can't wait for the coming CA's layout pass is that cell node visibility events occur before the pass, at which time the cell's subnodes don't have correct frames for impression tracking.
The root cause of this problem is that, right now, cell node visible states are set by ASRangeController well before the layout pass of the hosting collection/table view. That means we're "jumping the gun". The more I think about this, the more I agree with @Adlai-Holler that we need to treat visible state differently. That is, a node should only be visible (and thus get visibility events) after it's fully loaded, it's view/layer attached to the hierarchy and laid out by a CA transaction. In other words, at the end of the …
=> [ASDisplayNode] Force a layout pass on a visible node as soon as it enters preload state

CHANGELOG.md, Source/ASNetworkImageNode.mm
- Don't dispatch to main thread if there's no callout to run.
- Don't lock and then immediately unlock when we reach the main thread.
- Don't call out with `nil` image in the case of animated images.
- Call out using the exact image we loaded, instead of re-reading `self.image` at callout time, when it may have changed. If we loaded another image in the mean time, we will have scheduled that callout and it's important to preserve the serial nature here.
As I commented in #775, the docs say these callouts are off-main, but I decided to keep the on-main behavior for this diff.
=> Improve ASNetworkImageNode delegate callout behavior

Source/Details/ASGraphicsContext.m
We need to retain this since the image is about to go away.
There is however **no danger currently**, because the returned color space is a system constant so its retain count is always -1. This is just a matter of API correctness.
=> [Graphics contexts] Retain the reference color space #trivial

examples/CatDealsCollectionView/Sample/BlurbNode.h, examples/CatDealsCollectionView/Sample/BlurbNode.m, examples/CatDealsCollectionView/Sample/ItemNode.h, examples/CatDealsCollectionView/Sample/ItemNode.m, examples/CatDealsCollectionView/Sample/ItemStyles.h, examples/CatDealsCollectionView/Sample/ItemStyles.m, examples/CatDealsCollectionView/Sample/ItemViewModel.m, examples/CatDealsCollectionView/Sample/LoadingNode.h, examples/CatDealsCollectionView/Sample/LoadingNode.m, examples/CatDealsCollectionView/Sample/PlaceholderNetworkImageNode.h, examples/CatDealsCollectionView/Sample/PlaceholderNetworkImageNode.m, examples/CatDealsCollectionView/Sample/ViewController.m
=> Get CatDealsCollectionView example running again #trivial

Source/ASTextNode2.mm
Fixes #767 
We can add the background only if we really prepare the attributed string only for drawing. We are calculating the layout without background color now and use it for sizing of the node that in the end will draw the attributed string with background color. Background color should not the influence the size though.
=> Fix ASTextNode2 is accessing backgroundColor off main while sizing / layout is happening

CHANGELOG.md, Source/ASDisplayNode.h, Source/Private/ASDisplayNode+UIViewBridge.mm
- If the node's property was updated on a background thread and main thread has not executed the block that updates `cornerRadius` of the node's layer, the layer's property is out-of-date and shouldn't be used.
- After this change, ASDisplayNode's cornerRadius is the only source of truth and users must always use it instead of CALayer's.
Relevant PR: #465.
Recorded bug [here](https://cl.ly/osDG) - Pay attention to the "Save" button on the top right corner.
=> [ASDisplayNode] Always return the thread-safe cornerRadius property, even in slow CALayer rounding mode

CHANGELOG.md, Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASRangeController.h, Source/Details/ASRangeController.mm
This should result in memory savings in many apps, since errant relayouts are pretty common.
=> [ASRangeController] Fix stability of "minimum" rangeMode if the app has more than one layout before scrolling.

CHANGELOG.md, Source/Private/ASIGListAdapterBasedDataSource.m
There was no way to implement this useful scroll view delegate when using an IGListAdapter in conjunction with AsyncDisplayKit since it wasn't being passed through.
=> Add missing scrollViewWillEndDragging passthrough delegate

Texture.podspec
The IGListKit subspec currently has the dependency hardcoded to version `3.0.0`. I've come across a need to use a later version of IGListKit, so in the process I thought it would be nice for the podspec to allow a little more flexibility in versioning of the dependency. This PR will default to the latest 3.x version, but would also allow consumers to override the IGListKit dependency in their Podfiles to be anything in the 3.x.x range.
=> Update IGListKit dependency to allow for updated versions

CHANGELOG.md, Source/ASDisplayNode.mm, Source/Details/_ASDisplayView.h, Source/Details/_ASDisplayView.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/ASDisplayNodeInternal.h, Tests/ASDisplayNodeTests.mm, Tests/ASTableViewTests.mm
If certain `UIResponder` methods are overwritten in a `ASDisplayNode` subclass they are not considered. The only two methods that are currently properly forwarded are: `canBecomeFirstResponder` and `canResignFirstResponder` in _ASDisplayView.mm. Every other UIResponder method will never reach any `_ASDisplayView`. This especially is problem for `ASEditableTextNode` as we overwrite these methods in there and expect to be considered.
Example repo: https://github.com/maicki/TextureResponderChain
I added a test that show's this invalid behavior. You can find them under `ASDisplayNodeTests.mm` and `ASTableViewTests.mm`
The way I actually stumbled upon the issue is that as soon as an `ASEditableTextNode` is a subnode of a `ASCellNode` as well as a first responder, calling `reloadData` on an …
=> Fix UIResponder handling with view backing ASDisplayNode

CHANGELOG.md, Source/ASDisplayNode+Beta.h, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.mm, Source/ASNodeController+Beta.h, Source/ASNodeController+Beta.m, Source/AsyncDisplayKit.h, Source/Private/ASInternalHelpers.h, Source/Private/ASInternalHelpers.m, Source/Private/_ASPendingState.mm
Additionally this has a few minor fixes for Yoga support, and adds some basic but universally valuable callbacks like -nodeDidLoad to ASNodeController.
=> [ASDisplayNode] Consolidate main thread initialization and allow apps to invoke it manually instead of +load.

CHANGELOG.md, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode.mm, Source/Base/ASAssert.m, Source/Base/ASBaseDefines.h, Source/Layout/ASLayoutElement.mm
C11 thread-local variables are faster and safer than pthread_specifics. Let's use them!
Unfortunately, the pretty alias `thread_local` is defined in `threads.h`, an optional part of C11 that Clang doesn't support yet. But the actual `_Thread_local` storage classifier works just fine. It calls into `tlv_get_addr` provided by `dyld`, and it's a lot faster than `pthread_getspecific`.
Docs: http://en.cppreference.com/w/c/language/storage_duration
Here's the latest source available:
https://opensource.apple.com/source/dyld/dyld-519.2.2/src/threadLocalHelpers.s.auto.html
So 32-bit ARM this is built on pthread_getspecific. 64-bit ARM uses some crazy assembly that I don't understand.
=> Replace pthread specifics with C11 thread-local variables

CHANGELOG.md, Tests/ASDisplayNodeTests.mm, Tests/ArrayDiffingTests.m
Right now, automatic subnode management is not fixing up the z-order for nodes and their views, whenever existing subnodes are moved to a different place in the layout.
This can result in particularly weird issues when an existing layout changes with some additional nodes and some removed nodes that may displace or separate some existing nodes that also need to change order.
Once we fix, it will be easy to improve the Overlay and Background tests that are below this to also check the reversal / relayout case (I don't think they would pass currently). cc @maicki @nguyenhuy @Adlai-Holler 
```
ASDisplayNodeTests.mm:2410: error: -[ASDisplayNodeTests testThatStackSpecOrdersSubnodesCorrectly] : (([node.subnodes isEqualToArray:nodesReverseOrder]) is true) failed - subnodes: (
"<ASDisplayNode: …
```
=> [ASDisplayNode] Add unit tests for layout z-order changes (with an open issue to fix).

Source/ASTextNode.mm
Since the lock was acquire before we try to access the renderer, we should call `-_locked_renderer` to avoid re-acquiring the same (recursive) lock.
=> [ASTextNode] Avoid acquiring instance lock multiple times #trivial

CHANGELOG.md, Source/ASTextNode.mm
I made this before I saw that #819 exists, and while I think @hebertialmeida's solution may possibly be faster (though it could lead to thread explosion), I think this solution is more precise.
The race condition is in the C++ struct `ASTextKitAttributes` itself. Since there is no synchronization around the contents of that struct, the sanitizer is correctly warning us.
This has led me down a heck of a rabbit-hole with memory safety. In lieu of a more general fix for the problem of creating very fast, but flexible and thread-safe C++ structures that interoperate well with Objective-C, this fix solves the thread sanitizer warnings in an appropriate way, by protecting access to that structure, at least in the `hash` and `isEqual` methods, which seems sufficient since the class is …
=> Fix Text Node Thread Sanitizer Warning

CHANGELOG.md, Dangerfile, Source/ASTextNode2.mm
Putting the background color in the text drawing isn't the right way to go – we need to fill the entire layer with the background color instead.
This also puts a lock on the `pointSizeScaleFactors` property even though it isn't actually respected and fixes a case where NSMutableAttributedStrings could leak into a cache (no harm done right now).
=> [ASTextNode2] Fix background color drawing

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASCGImageBuffer.h, Source/ASCGImageBuffer.m, Source/Details/ASGraphicsContext.h, Source/Details/ASGraphicsContext.m
- In Pinterest, No-Copy rendering is having no impact except a slight increase in memory warnings.
- Something's wrong – need to match the native function more closely.
- Create a custom buffer, instead of NSMutableData.
- The custom buffer uses `mmap` and, when an image is created it uses `vm_protect` to mark the memory as read-only.
- Behavior copied from `CGBitmapContextCreateImage`.
- Could be that this makes it possible for CA to map the image memory into the renderserver.
- Also tags the memory as a CGImage, for viewing in Instruments.
=> [NoCopyRendering] Use vm instead of malloc

Source/ASCGImageBuffer.m
I removed this for testing the non-VM path, but didn't mean to commit it.
=> Put back VM flag in ASCGImageBuffer

Source/ASViewController.h, Source/Details/ASTraitCollection.h, Source/Details/ASTraitCollection.m
As `ASPrimitiveTraitCollection` is a struct, the application can always initialize it in its own way, without using Texture-provided initialization functions. This may lead to `preferredContentSize` field being `nil`, which, in turn, may lead to frustrating crashes when the struct is given to Texture.
While simply advising the user to always use the provided initialization functions should solve the problem, it's better to always treat this structure as possibly improperly initialized and guard against `nil` value in this field.
Additionally this PR explicitly marks all `UIContentSizeCategory` usage in `ASTraitCollection` class as non-null.
=> [ASPrimitiveTraitCollection] Always treat preferredContentSize as a potential nil #trivial

Source/Details/ASIntegerMap.mm
NSIndexSet+ASHelpers.h should be a user vs a system or framework include.
=> Make NSIndexSet+ASHelpers.h reference local #trivial

Source/Details/ASRecursiveUnfairLock.m
In the recursive case (lock while locked,) we previously still stored self as the current thread, which was redundant. This removes that operation and also simplifies the locking code.
=> Remove Redundant Atomic Store from Recursive Unfair Lock in Recursive Case #trivial

Source/ASCGImageBuffer.h, Source/ASCGImageBuffer.m
This fixes a bug when no-copy rendering is enabled where small images may be corrupt.
Marked trivial because this is a bugfix for a change that's unreleased (already in the master section of changelog).
=> [NoCopyRendering] In non-VM case, use calloc to get a zerod buffer #trivial

AsyncDisplayKit.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
This file is added to `xcshareddata`. It's harmless and this way the team can synchronize on any workspace changes that Xcode wants us to make in the future, rather than each contributor getting prompted.
=> Check in Xcode 9.3 "workspace checks" file

Source/Base/ASSignpost.h
AS_KDEBUG_ENABLE macro definition was producing warning: “Macro expansion producing ‘defined’ as undefined behavior”
This prevents building in Xcode 9.3 
Refer to issue: https://github.com/TextureGroup/Texture/issues/872
=> Fix macro definition for AS_KDEBUG_ENABLE producing warning #trivial

CHANGELOG.md, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.m, Source/Details/ASThread.h, Source/Private/ASInternalHelpers.m
This also fixes a missing `exp_unfair_lock` constant 😅 .
This can avoid some pretty serious pre-main time.
The diff is hard to read, so here's what it does:
- Create static `NSNumber *`'s for the two BOOLs. If you're not in the experiment, these will be set during `ASInitializeFrameworkMainThread`. If you are in the experiment, the initializer function does nothing.
- In the two accessor functions e.g. `BOOL ASDefaultAllowsGroupOpacity()` we have a dispatch_once that checks the static to see if it was set in the initialize function, and if not it selects the default based on UIKit documentation (by reading Info.plist).
- There was some thread-unsafety before which is maintained. Namely, the statics were not thread-affined and they still aren't but the dispatch_once has a memory barrier …
=> Add experiment to skip creating UIViews altogether for constants

CHANGELOG.md, Source/Base/ASBaseDefines.h, Texture.podspec
Using `std=gnu++11` causes subtle issues that I don't fully understand yet.
This adds a warning if you compile Texture using that C++ standard.
=> Request std=c++11 dialect again, and add warning

Source/ASTextNode.mm
Because multiple threads can enter this allocWithZone: method around the same time, it is possible for one of them to setSuperclass first, and then the second thread would get stuck in an infinite loop.
When climbing the inheritance hierarchy, ASTextNode2 would be encountered by this second thread, and it would continue until reaching c == Nil. Since there was no case to catch this, an infinite loop would result.
Then the main thread can be deadlocked if a method like waitUntilAllUpdatesAreProcessed is called on ASCollectionView.
=> [ASTextNode] Fix a deadlock that could occur when enabling experimental ASTextNode2 via ASConfiguration

Schemas/configuration.json, Source/ASExperimentalFeatures.h
When I added this new constant I forgot to update the JSON. Since most users aren't going to validate their content against the JSON I expect, this shouldn't impact them.
=> Update configuration schema #trivial

CHANGELOG.md, Source/TextKit/ASTextKitComponents.mm
=> Prevent UITextView from updating contentOffset while deallocating

Source/ASDisplayNode.mm
Since `didExitHierarchy` is called without the node's instance lock being held, the lock must be acquired before accessing `pendingInterfaceState`.
=> [ASDisplayNode] Improve thread-safety of didExitHierarchy #trivial

CHANGELOG.md, Source/ASConfigurationInternal.m, Tests/ASConfigurationTests.m
This makes sure that A/B testing frameworks can activate control users as well as treatment ones.
=> Always call out to delegate for experiments, whether enabled or not

CHANGELOG.md, Source/ASTextNode2.h, Source/ASTextNode2.mm, Source/Details/ASThread.h
Although I don't know of any specific crashes caused by this, I think we should
lock all properties by default. There are also some indications of premature
optimization in keeping lock scope small, where it is actually important to
have transactional integrity, and also where the ASDisplayNode base class is
otherwise going to repeatedly re-lock the object anyway.
I think this will remain pretty efficient, especially with os_unfair_lock enabled.
=> [ASTextNode2] Upgrade lock safety by protecting all ivars (including rarely-changed ones).

Source/ASImageNode+AnimatedImage.mm, Tests/ASNetworkImageNodeTests.m
Hey guys,
I recently tried to update to `master` and ran into an issue where the `defaultImage`s I set in my `ASNetworkImageNode` are replaced by `nil` when they leave the preload range.
It turns out, #896 does not take into account the case where the `animatedImage` might be `nil`. Hence the call to `_locked_setAnimatedImage` no longer performs an early return like it used to, because `animatedImage.playbackReady` is `NO`.
This PR fixes this and gives me back my `defaultImage`s, even after they've gone out of the preload range and back. :-D
This time I haven't set up a sample project like I usually do, but I made up for it by adding a new test, yay! This test shows that the `defaultImage` is currently incorrectly set to `nil` when the `ASNetworkImageNode` leaves the preload range.
I've …
=> [ASImageNode+AnimatedImage] Fix early return when animatedImage is nil in setAnimatedImage #trivial

CHANGELOG.md, Texture.podspec
It's been since January that we've been on 2.6.
=> Cut 2.7 release

CHANGELOG.md, Source/ASDisplayNodeExtras.h
=> Make ASPerformMainThreadDeallocation visible in C

CHANGELOG.md, Source/Details/Transactions/_ASAsyncTransaction.h, Source/Details/Transactions/_ASAsyncTransaction.mm, Source/Details/Transactions/_ASAsyncTransactionContainer.h, Source/Details/Transactions/_ASAsyncTransactionContainer.m, Source/Details/Transactions/_ASAsyncTransactionGroup.h, Source/Details/Transactions/_ASAsyncTransactionGroup.m
- Remove unused methods.
- `addAsyncOperation` we no longer do async rendering.
- `addCompletion` this was implemented in a somewhat questionable way anyway.
- `addOperation` without priority. You can just specify default priority.
- Implement CALayer category properties using CALayer dynamic properties rather than associated objects.
- Tighten up the `mainTransactionGroup` API and trivial reorg of its implementation.
=> Clean up async transaction system a bit

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASLocking.h, Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm, Source/AsyncDisplayKit.h, Source/Details/ASThread.h, Source/Layout/ASLayoutElement.h, Source/Layout/ASLayoutElement.mm, Source/Layout/ASLayoutSpec.h, Source/Layout/ASLayoutSpec.mm
- New protocol `ASLocking` which extends `NSLocking` and adds the `-tryLock` method.
- New macros `ASSynthesizeLockingMethodsWithMutex` and `ASSynthesizeLockingMethodsWithObject` to remove locking method boilerplate.
- Make all lockables conform to `ASLocking`.
- Add `ASDN::Mutex::tryLock()`.
- Add `ASLockSequence` which repeatedly tries to lock different locks in sequence.
No functional changes.
This is a precursor to #956 .
=> Add support for acquiring multiple locks at once

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASDisplayNode.mm, Source/ASDisplayNodeExtras.mm, Source/ASMainThreadDeallocation.h, Source/ASMainThreadDeallocation.mm, Source/AsyncDisplayKit.h, Source/Private/ASInternalHelpers.h, Source/Private/ASInternalHelpers.m, Source/TextKit/ASTextKitComponents.mm
This makes it possible to:
- Trampoline ivars from non-display-node classes.
- Require other classes of ivar to be trampolined to the main thread.
=> Generalize the main thread ivar deallocation system

Source/ASMainThreadDeallocation.h, Source/ASMainThreadDeallocation.mm
=> Fix crash when call needsMainThreadDeallocation on NSProxy instances #trivial

CHANGELOG.md, Source/ASCollectionView.mm, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNodeExtras.mm, Source/ASNetworkImageNode.mm, Source/ASRunLoopQueue.mm, Source/ASTableView.mm, Source/ASTextNode.mm, Source/Base/ASBaseDefines.h, Source/Details/ASBasicImageDownloader.mm, Source/Details/ASCollectionLayoutState.mm, Source/Details/ASDataController.mm, Source/Details/ASPageTable.m, Source/Details/NSArray+Diffing.m, Source/Details/NSIndexSet+ASHelpers.h, Source/Details/NSIndexSet+ASHelpers.m, Source/Details/_ASDisplayViewAccessiblity.mm, Source/Layout/ASLayout.mm, Source/Layout/ASStackLayoutSpec.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/Private/ASMutableElementMap.m, Source/Private/ASTwoDimensionalArrayUtils.m, Source/Private/TextExperiment/Component/ASTextLayout.m, Source/Private/_ASHierarchyChangeSet.mm, Source/_ASTransitionContext.m
Unfortunately, Foundation and UIKit are not going to be compiled with ARC any time soon.
So until then, calling methods like `+[NSArray array]` under ARC will not use the fast-return path and will result in `alloc -> autorelease -> retain` to get a +1 instead of just `alloc`. Plus draining the pool takes time! Why waste it?
=> Reduce usage of autorelease pools

CHANGELOG.md, Source/Base/ASBaseDefines.h, Source/Details/ASPhotosFrameworkImageRequest.h, Source/Details/ASPhotosFrameworkImageRequest.m, Source/Details/ASThread.h, Source/Private/_ASCoreAnimationExtras.mm
- `AS_ARRAY_COUNT` is replaced by C++ array iteration.
- `hidden/pure/const` aren't used.
- `ASDISPLAYNODE_WARN_UNUSED` is unused in favor of `AS_WARN_UNUSED_RESULT`
- `ASDISPLAYNODE_NOT_DESIGNATED_INITIALIZER` is unnecessary since we can mark the initializer unavailable.
- `ASDISPLAYNODE_NOTHROW` is superseded by the `noexcept` decorator from C++14
=> Remove unused/unneeded header macros

Source/Private/ASLayoutTransition.mm
Fixed removing node from supernode after layout transition when automaticallyManagesSubnodes is disabled. In case if developer prefer to manage subnodes by himself then he wants to be sure that stack will not change automatically.
=> Fixed removing node from supernode after layout transition

CHANGELOG.md, Schemas/configuration.json, Source/ASCollectionView.mm, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.m, Source/ASTableView.mm, Source/Details/ASDataController.mm, Source/Details/ASDelegateProxy.h, Source/Details/ASDelegateProxy.m
Currently we have an issue where the background deallocation of most cell nodes is not happening, because of the following stack:
```
thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 8.1
* frame #0: 0x000000010ac960ff PinterestDevelopment`::-[ASDisplayNode dealloc](self=0x00007fc71d959a00, _cmd="dealloc") at ASDisplayNode.mm:415
frame #1: 0x000000010bd1c6aa PinterestDevelopment`-[PIPinCloseupGalleryCellV1 dealloc](self=0x00007fc71d959a00, _cmd="dealloc") at PIPinCloseupGalleryCell.m:189
frame #2: 0x0000000118268a6e libobjc.A.dylib`objc_object::sidetable_release(bool) + 202
frame #3: 0x000000010ac0b1f8 PinterestDevelopment`::-[ASCollectionElement .cxx_destruct](self=0x00006080003be300, _cmd=".cxx_destruct") at ASCollectionElement.mm:29
frame #4: 0x0000000118252920 …
```
=> Create an experiment to remove extra collection teardown step

CHANGELOG.md, Source/Base/ASBaseDefines.h, Source/Layout/ASLayout.mm
Layout flattening is one of the most common operations in our framework and it currently involves a ton of needless retain/release traffic (4 rr pairs per layout). This diff reduces that to 0.
Since I hope to make more use of the `__unsafe_unretained` qualifier in the future, I added an `unowned` alias for it, to make it prettier.
Obviously please review this diff carefully, since no optimization is worth crashing.
=> Optimize layout flattening

docs/_docs/team.md
Small thing, but noticed this path is dead. Switching link in Michael Schneider's bio from upgrading.html to adoption-guide-2-0-beta1.html (used in navigational links across texturegroup.org/docs)
Testing this doesn't quite work in preview as the path differs a bit from when its accessible through the normal resolver. I assume this will substitute the last path slug and the server maps `_docs` to `docs` https://github.com/TextureGroup/Texture/tree/master/docs/_docs
=> [texturegroup.org] Use valid link for Upgrade to 2.0 beta 1 page #trivial

Source/ASDisplayNodeExtras.h, Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm, Source/ASTextNode.mm, Source/ASTextNode2.mm
Small cleanup to get our warnings down to zero again and add getters to satisfy the atomicity of defined properties.
=> Add missing instance variables in ASTextNode and warnings cleanup #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASCollectionView.mm, Source/ASCollections.h, Source/ASCollections.m, Source/ASExperimentalFeatures.m, Source/ASTableView.mm, Source/AsyncDisplayKit.h, Source/Base/ASBaseDefines.h, Source/Details/ASCollectionFlowLayoutDelegate.m, Source/Details/ASCollectionGalleryLayoutDelegate.mm, Source/Layout/ASLayout.mm, Source/Layout/ASLayoutSpec.mm, Source/Private/_ASHierarchyChangeSet.mm, Tests/ASCollectionsTests.m
- Adds a new `+arrayByTransferring:count:` factory method to `NSArray`.
- Public version of private `__CFArrayCreateTransfer` function.
- "Consumes" a C-array of `strong id`. Also works with `vector` in C++.
- The C-array (or vector) is nilled out in the process. Consumed.
- Removes N retain/release pairs compared to `initWithObjects:count:` or NSMutableArray.
- Gives you an immutable (free-copy) array.
- Applies this method to `ASArrayByFlatMapping` and layout flattening.
- Solid unit test.
=> Create transfer-array method and use it

CHANGELOG.md, Source/ASDisplayNode.mm, Source/Details/_ASDisplayView.mm, Source/Private/ASDisplayNodeInternal.h, Tests/ASDisplayNodeTests.mm
In certain cases we don't properly consider the overwritten responder methods from the `ASDisplayNode`. This PR should fix this situation and is adding a test to prevent this in the future.
Fixes #957
=> Properly consider node for responder methods

CHANGELOG.md, Source/Private/ASIGListAdapterBasedDataSource.m
The method `scrollViewDidEndDecelerating` have been declared by proxy but wasn't not implemented, thus messages weren't delivered to `IGListAdapter.scrollViewDelegate`.
This simple request addresses this issue.
=> [IGListKit] Adds missing UIScrollViewDelegate method to DataSource proxy

CHANGELOG.md, Source/ASDisplayNode.mm, Source/Base/ASAssert.m, Source/Base/ASAvailability.h, Source/Layout/ASLayoutElement.mm
Fixes part of the issue discussed in #873 #929 and #969.
We now provide fallbacks for i386.
=> Fix 32-bit simulator build on Xcode >= 9.3

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/AsyncDisplayKit.h, Source/Details/NSArray+Diffing.h, Source/Details/NSArray+Diffing.m, Source/Details/NSArray+Diffing.mm, Source/Layout/ASLayout+IGListKit.h, Source/Layout/ASLayout+IGListKit.mm, Source/Layout/ASLayout.mm, Source/Private/ASLayoutTransition.h, Source/Private/ASLayoutTransition.mm, Tests/ASDisplayNodeImplicitHierarchyTests.m, Tests/ASDisplayNodeTests.mm, Tests/ArrayDiffingTests.m
...and NSArray+Diffing.
Add some tests.
See https://github.com/TextureGroup/Texture/pull/816 for more details on the existing shortcomings. This PR should allow z-order to be correct after nodes move during a transition.
=> Add move detection and support to ASLayoutTransition

Source/ASConfiguration.m, Source/ASDisplayNode.mm, Source/Details/ASElementMap.m, Source/Details/ASIntegerMap.mm, Source/Private/ASTwoDimensionalArrayUtils.m, Source/Private/TextExperiment/Component/ASTextLine.m, Source/Private/_ASCoreAnimationExtras.mm, Source/Private/_ASHierarchyChangeSet.mm
Oh `%zd`, you were the solution to all our problems. The perfect specifier for `NSInteger` a.k.a `ssize_t`.
But the lords of Clang have struck you down. So let's throw in the towel and cast to `long`. For now, using `%tu` for `NSUInteger` doesn't generate warnings so let's leave it be. Easy enough to change later.
=> Address warnings in Xcode >= 9.3 about using %zd for NSInteger #trivial

CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm, Source/ASImageNode+AnimatedImage.mm, Source/ASImageNode.mm, Source/ASNetworkImageNode.mm, Source/ASTextNode.mm, Source/ASTextNode2.mm, Source/ASVideoNode.mm, Source/ASVideoPlayerNode.mm, Source/Details/ASThread.h, Source/Private/ASDisplayNode+FrameworkPrivate.h, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/ASDisplayNodeInternal.h
- Rename `ASDisplayNodeAssertLockUnownedByCurrentThread` to `ASAssertUnlocked`, and `ASDisplayNodeAssertLockOwnedByCurrentThread` to `ASAssertLocked` -> shorter and hopefully easier to distinguish between the two.
- Add assertions to `_locked_` and `_u_` (i.e "unlocked") methods.
- Turn `CHECK_LOCKING_SAFETY` on by default. After #1022 and #1023, we're in a good shape to actually enforce locked/unlocked requirements of internal methods. Our test suite passed, and we'll test more at Pinterest after the sync this week.
- Fix ASVideoNode to avoid calling `play` while holding the lock. That method inserts a subnode and must be called lock free.
- Other minor changes.
=> Stricter locking assertions

CHANGELOG.md, Source/Layout/ASLayout.h, Source/Layout/ASLayout.mm
=> Remove NSMutableArray for retaining sublayout elements

Source/Details/ASThread.h
We accidentally landed this being set to 1 for all builds a few days ago (#1024).
=> Turn lock-checking on only when assertions are enabled #trivial

AsyncDisplayKit.xcodeproj/project.pbxproj, BUCK, CHANGELOG.md, Source/ASDisplayNodeExtras.h, Texture.podspec
We don't currently use exceptions so we don't need the extra binary to support them.
`-fno-exceptions` removes unwind tables and makes C++ STL put "abort" wherever there would be an exception.
`-fno-objc-arc-exceptions` removes code that ARC adds to prevent leaks in the case of exceptions https://clang.llvm.org/docs/AutomaticReferenceCounting.html#exceptions
**How big is the win?**
- In terms of total o-file size, the framework goes from **33.3MB to 31.5MB** for ARM64 release builds.
- In terms of executable size, the CatDealsCollectionView ARM64 release binary goes from **12.3MB to 11.7MB**.
So modulo any Apple fiddling with your binary, the 64-bit one should shrink by about 600KB.
=> Turn off exceptions to reduce binary size (-600KB for arm64)

Source/Layout/ASLayout.mm
- Major bug in the release: I was releasing the layout itself, not the layout element.
- Improvement in the retain: Previously I bridge-casted then retained (= `[[[o retain] autorelease] retain]`), now I use a bridging retain (= `[o retain]`).
Thanks Michael for recognizing that the CI simulator loop was caused by this. I don't know why it resulted in a simulator loop but at least it's fixed.
=> Fix the bug I introduced in #1030 #trivial

docs/_docs/containers-ascollectionnode.md
=> Fix & update ASCollectionNode constrained size doc. #trivial

.gitignore, Podfile, Podfile.lock
With any luck this will fix the CI.
=> Pin OCMock version to 3.4.1 because 3.4.2 has issues

Source/Layout/ASLayout.h, Source/Layout/ASLayout.mm
The CI unit tests were fixed in #1038, this should fix the examples build.
=> Revert unreleased layout debug method name change from #1030 #trivial

Source/ASTextNode.mm
=> [ASTextNode] One more check variables before calling delegate method #trivial

docs/_docs/automatic-layout-containers.md
New images taken from http://texturegroup.org/docs/automatic-layout-containers.html.
=> Changed lost images to existing one. #trivial

Source/Private/ASLayoutTransition.mm
The comment at line 305 strongly implies this is expected to be a dynamic cast.
=> Remove misleading comment and add assertion #trivial

Source/Private/ASDisplayNode+UIViewBridge.mm
Doing so may trigger `-layer:didChangeBoundsWithOldValue:newValue:` on the layer's delegate (i.e `ASCALayerExtendedDelegate`) which then runs other operations that require the lock to be free.
=> Avoid setting frame on a node's backing store while holding its lock

docs/_docs/automatic-layout-basics.md
In order for markdown to properly render headers, there needs to be a space between the `#` and the text. I've added these where I found them missing.
=> Fix headers in markdown

Source/ASTextNode.mm, Tests/ASDisplayLayerTests.m
Some code paths in our app use `class_createInstance` directly on subclasses of ASTextNode and so bypass `allocWithZone:`. In order to get the correct class hierarchy, the change must be made somewhere else.
- Move the class change for subclasses from `allocWithZone:` to `initialize`.
We get the added benefit of improving performance.
=> [ASTextNode2] Simplify allocWithZone: + initialize implementation #trivial

CHANGELOG.md, Source/Private/_ASPendingState.mm
We currently create attributed & non-attributed copies of accessibility hint, label, and value whenever you set them. We don't need to – UIKit will bridge between the two worlds for us. Creating attributed strings is actually pretty expensive. So we just update our flags and set whichever one was set most recently.
- Remove nonattributed <-> attributed duplication in accessibility properties.
- In the getters (only used before-node-load), generate the corresponding value on demand.
- Will almost never be called.
- Always update "changed" flags to ensure the latest value is applied in the case that the view was given a different value outside of ASPendingState.
=> Remove extra string/attributed string creation in accessibility props

Source/ASDisplayNode.mm, Source/ASNodeController+Beta.mm, Source/Private/ASDisplayNodeInternal.h
After #1061, if your unit tests use mock nodes you may get a crash because we access ivars on the mock display node. It is unsafe to access ivars on mock objects.
This diff makes it so that we send the node a message. If it's a mock, the mocking system will forward the message to the real instance.
=> Remove direct ivar access on non-self object to fix mocking case #trivial

CHANGELOG.md, Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.m, Source/Private/TextExperiment/Component/ASTextLayout.h, Source/Private/TextExperiment/Component/ASTextLayout.m
Creating framesetters is a very expensive operation. During multipass layout we create multiple framesetters for the same attributed string. And then if none of those layouts is actually selected, we create another one for the layout used for rendering. Cache them to improve performance.
- Make a new experiment `exp_framesetter_cache` which reuses framesetters in an NSCache.
- Make a raw-pointer set and a lock, to track which framesetters are busy.
- If the cached framesetter for the target string is busy, we just create one and discard it. In practice this is unlikely and hasn't happened in testing.
=> Add an experimental framesetter cache in ASTextNode2

CHANGELOG.md, Source/ASTextNode2.mm, Source/Private/TextExperiment/Component/ASTextLayout.h, Source/Private/TextExperiment/Component/ASTextLayout.m
Make text rendering faster.
- Remove pointless attributed string mutable copy in ASTextLayout. No clue why this was here but it is not useful in the least.
- Provide an option to make ASTextContainers immutable and get free copying. ASTextLayout copies its container, which is often already a copy so we save that.
=> Reduce copying in ASTextNode2 stack

Source/ASLocking.h
Hitting this error because we're compiling with a stricter set of build rules internally.
=> Fix compiler error in ASLocking #trivial

Source/ASControlNode.mm, Source/ASImageNode.mm
=> #trivial Shouldn't hold the lock while adding subnodes

CHANGELOG.md, Source/ASConfigurationDelegate.h, Source/ASConfigurationInternal.h, Source/ASConfigurationInternal.m, Source/Private/ASInternalHelpers.m
- Add the new callback.
- Could have taken this opportunity to change the ASConfigurationInternal API to expose the singleton object and call a method on it.
- Instead kept the C-function API for now to keep the change minimal.
=> Add a -textureDidInitialize delegate callback

CHANGELOG.md, Source/ASImageNode+AnimatedImage.mm, Source/ASImageNode.h
- Unlock before cleanup
- Unlock before calling out to `animatedImageSet:previousAnimatedImage:` to prevent a deadlock.
=> Unlock before cleanup and calling out to subclass hooks for animated images.

Source/ASTextNode2.mm
- This call was copied from TextNode1.
- Git blame there not helpful.
- Not causing problems right now.
- Doesn't belong.
- We have `needsDisplayOnBoundsChange=YES` in `init`.
=> Don't setNeedsDisplay on text node 2 measure #trivial

CHANGELOG.md, Source/ASTextNode2.mm
- My previous change #1065 intended for us to _sometimes_ copy our mutable text container during layout.
- It had a bug where we _always_ copy the text container.
- It turns out we _never_ need to copy it, because we hold our lock while we use the container. We never mutate or retain the layout during measurement.
Copying text containers is surprisingly expensive hence I think this is worthwhile.
=> Don't copy container during ASTextNode2 measure

CHANGELOG.md
In https://github.com/TextureGroup/Texture/pull/1012 the change note was mistakenly added to the already released 2.7 version. Moved it to the section about master.
=> changelog fix: let / var macros did not make it to 2.7

Source/ASDisplayNode.mm, Source/Base/ASBaseDefines.h
- A small optimization.
- New macro `ASTransferStrong(lvalue)` steals a +1 from the lvalue and clears it.
=> Don't copy onDidLoadBlocks #trivial

Source/ASEditableTextNode.h, Source/Details/ASPINRemoteImageDownloader.h, Source/Details/ASPINRemoteImageDownloader.m, Source/Private/ASDisplayNode+FrameworkPrivate.h
- Fix typos in `ASEditableTextNode.h` and `ASDisplayNode+FrameworkPrivate.h`.
- Remove unnecessary declaration for `ASPINRemoteImageDownloader`'s `sharedDownloader` class property.
- Remove unnecessary empty lines in `ASPINRemoteImageDownloader.m` and `ASEditableTextNode.h`.
=> Fix typos and minor code cleanups #trivial

Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h
- An empty hash table takes 2 heap allocations at 288 bytes.
- 2 hash tables per node (original and copy for safe enumeration) is 576 bytes per node.
- ASDisplayNode is only 928 bytes, so these hash tables add 60% more weight.
- Most of these blocks are global blocks (no value capture, free retain/release) and some are stack blocks. No malloc blocks.
=> Remove use of NSHashTable for interface state delegates #trivial

CHANGELOG.md, Source/Details/ASPINRemoteImageDownloader.h, Source/Details/ASPINRemoteImageDownloader.m
Add a method for setting preconfigured PINRemoteImageManager instead of using the self-created ASPINRemoteImageManager.
In this way, we can add custom configuration to the PINRemoteImageManager such as request configuration/url configuration.
=> Add a method for setting preconfigured PINRemoteImageManager

CHANGELOG.md, Source/ASCollectionNode.mm, Source/ASTableNode.h, Source/ASTableNode.mm, Tests/ASCollectionViewTests.mm
While setting the interface state of a node in certain circumstances we hit the path that first grabs the instance lock and calls `-[ASCollectionNode clearContents]` while the view is not loaded. Within `clearContents` we need access to the rangeController from the view by calling self.view.rangeController what will trigger creating the view and the assert linked in the issue will be thrown as `didLoad` should not be called with the instance locked held.
For now I removed the need to use the view to access the `rangeController` what should fix the situation described above and linked here: #1094
Further todos should be that we improve the locking impelementation around this area. Currently `-[ASDisplayNode clearContents]` is accessing instance variables and therefore should be prefixed …
=> Remove necessity to use view to access rangeController in ASTableNode, ASCollectionNode

Source/Details/ASPINRemoteImageDownloader.m
Fix typo in the new api for setting a preconfigured remote image manager
=> Fix RemoteImageDownloader name mismatch #trivial

Source/ASExperimentalFeatures.h, Source/ASRunLoopQueue.mm, examples/CatDealsCollectionView/Sample/AppDelegate.m
This improves general performance/energy usage and possibly increase warm starts.
=> Rollout ASDeallocQueueV2 #trivial

CHANGELOG.md, Schemas/configuration.json, Source/ASCollectionView.mm, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.m
This is a follow up on #1136. Our experiment results show that clearing data frequently is the cause of our #1 crash. @maicki and I believe that this is because silently clearing its data while the collection view is still being used, without notifying the backing UICollectionView, puts it out-of-sync and causes mayhem next time the collection view processes a batch update. If you look at the stack trace closely, you'll notice that the crash doesn't occur on the same run loop that `clearData` was called, making it extremely tricky to investigate and identify the root cause.
To fix this problem, I'm proposing to only call `clearData` if the collection view is actually being torn down. I'm also going to set up another experiment to slowly roll this out to make sure we don't reintroduce the …
=> Only clear ASCollectionView's data during deallocation

Source/ASCollectionNode.mm, Source/ASCollectionView.mm, Source/ASImageNode.mm, Source/ASTableNode.mm, Source/ASTextNode.mm, Source/ASTextNode2.mm, Source/TextKit/ASTextKitContext.mm
Fixes `-Wmissing-noescape` warnings which have become smarter in Xcode 10
=> Add missing NS_NOESCAPE attributes in overwritten methods #trivial

CHANGELOG.md, Source/ASDisplayNode+Layout.mm, Source/ASTextNode.mm, Source/ASTextNode2.mm, Source/Private/ASDisplayNodeInternal.h
Currently some race condition can happen within `-[ASTextNode setAttributedText:]`:
- Thread A calls `setAttributedText:`
- We change the text with the lock held and we grab the length of the _attributedString
- After getting the length a thread switch happens
- A thread B calls setAttributedText:. The attributed text instance var get's updated and it finishes the method
- Thread switch happens back to A and it's going again. It goes into the if block and try to access the last character based on the old length that is not up to date anymore and it crashes
You can repro it if you simulate a thread switch and the crash on the descender line via a semaphore like: 
```
- (void)setAttributedText:(NSAttributedString *)attributedText semaphore:(dispatch_semaphore_t)semaphore
{
if …
```
=> Fix crash setting attributed text on multiple threads

CHANGELOG.md, Source/ASTextNode2.mm
ASTextNode2 uses ASTextLayout to calculate its layout and bounding rect. When the constrained width that is used for layout calculation is inf/max (e.g when the node is inside a horizontal stack), ASTextLayout doesn't ignore its right/center/natural text alignment but takes it into account. That results in an unreasonable size (and position).
Fix by detecting when the node is calculating intrinsic size and force its layout alignment to be left. Other alignments should still work when the max width is finite/reasonable.
=> ASTextNode2 to ignore certain text alignments while calculating intrinsic size

Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm
`-imageNodeDidStartFetchingData:` and `-imageNodeDidFinishDecoding:` are always called on main thread, and the documentation should reflect that.
=> Update documentation of ASNetworkImageNodeDelegate #trivial

docs/Gemfile
Seeing a warning from GitHub that suggests to update Jekyll because of this vulnerability:
> Jekyll through 3.6.2, 3.7.x through 3.7.3, and 3.8.x through 3.8.3 allows attackers to access arbitrary files by specifying a symlink in the "include" key in the "_config.yml" file.
[CVE-2018-17567](https://nvd.nist.gov/vuln/detail/CVE-2018-17567)
=> Update Jekyll to 3.6.3

CHANGELOG.md, Source/ASDisplayNode+Beta.h
A UIAccessibilityCustomAction can be initialized with a target and a selector. The selector is expecting methods with the following signature:
```
- (BOOL)performAccessibilityCustomAction;
- (BOOL)performAccessibilityCustomAction:(UIAccessibilityCustomAction *)action;
```
Within Texture we use a different signature:
```
- (void)performAccessibilityCustomAction:(UIAccessibilityCustomAction *)action;
```
This diff will update the Texture API to adapt the correct API for a UIAccessibilityCustomAction:
- (BOOL)performAccessibilityCustomAction:(UIAccessibilityCustomAction *)action;
=> Fix mismatch in UIAccessibilityAction selector method

examples_extra/Placeholders/Sample/PostNode.m, examples_extra/Placeholders/Sample/ViewController.m
Simply removes the usage of measure: and allows project to build. Not sure if examples warrant a changelog addition?
=> Migrate placeholder example project from 1.0 to 2.x

AsyncDisplayKit.xcodeproj/project.pbxproj, CHANGELOG.md, Source/ASButtonNode.mm, Source/ASDisplayNode+Beta.h, Source/ASDisplayNode.mm, Source/ASTextNode.mm, Source/ASTextNode2.mm, Tests/ASButtonNodeTests.m, Tests/ASTextNode2Tests.m
Expose default Texture-set accessibility values as properties in ASDisplayNode, and added relevant overrides and tests.
This allows clients to look up the default a11y values set by Texture in ASDisplayNode (and its subclasses) and reset them if needed.
=> [ASDisplayNode] Expose default Texture-set accessibility values as properties

Source/Details/ASRecursiveUnfairLock.h, Source/Details/ASRecursiveUnfairLock.m
This should fix a problem if a `ASRecursiveUnfairLock` is imported in a non c++ compiled file as the implementation file will not have access to `stdatomic.h`.
=> Move import of stdatomic to ASRecursiveUnfairLock implementation file #trivial

Source/ASTextNode+Beta.h, Source/ASTextNode.mm, Source/ASTextNode2.mm
- Expose textLayoutForConstraint:, unavailable for `ASTextNode` for now
- Refactor `compatibleLayoutWithContainer:text:` into a static method
=> Expose a way to determine if a text node will truncate for a given constrained size #trivial

Source/TextKit/ASTextKitRenderer.mm
Avoid building multiple rects that are exactly the same.
=> Small fix in ASTextKitRenderer #trivial

CHANGELOG.md, Source/ASTextNode.mm, Source/ASTextNode2.mm, examples/Kittens/Sample/AppDelegate.m, examples/Kittens/Sample/BlurbNode.m
This diff will change the behavior handling tapping on the additional attributed message:
If `passthroughNonlinkTouches` is set to YES, taps on the additional attributed message will *not* call the `textNodeTappedTruncationToken:` delegate method anymore. Previously tapping on the additional attributed message always called `textNodeTappedTruncationToken:` without any dependence on `passthroughNonlinkTouches`.
Another approach could be to add a new property like: `handleAdditionalTruncationString` that if set to YES will call `textNodeTappedTruncationToken:` otherwise not. This would not depend on `passthroughNonlinkTouches`.
Furthermore this diff fixes taps within the additional attributed message within `ASTextNode2` what currently didn't really work. Before this the tap was not …
=>  Don’t handle touches on additional attributed message if passthrough is enabled

CHANGELOG.md, Source/ASTextNode.h, Source/ASTextNode.mm, Source/ASTextNode2.h, Source/ASTextNode2.mm, Source/Private/TextExperiment/Component/ASTextLayout.m
iOS will adjust line spacing if it pulls in out-of-font glyphs (ie emojis).
The cap-to-font-height option will override this adjustment, keeping line spacing (baseline-to-baseline) consistent but possibly crowding the emoji (or other out-of-font glyphs).
Implementing required ASTextNode2 to expose the linePositionModifier delegate used by ASTextLayout.
=> Correct linePositionModifier behavior

CHANGELOG.md, Source/Details/_ASDisplayViewAccessiblity.mm
Modified the ASDisplayNode accessibility label to only aggregate its sub-nodes' labels when it doesn't have any explicit accessibility label set on itself. If an existing label is already present, it is instead treated as an override to the container's a11y label. Added relevant tests.
=> Tweak a11y label aggregation behavior to enable container label overrides

CHANGELOG.md, Source/ASTextNode2.mm, Source/Private/TextExperiment/Component/ASTextLayout.m
As we use the returned size for sizeThatFits, we need to make sure we don't truncate text and then return the smaller size (leading to even more text being truncated).
If a newline character takes the text outside of the bounds, that text should be truncated.
=> Newline character support and truncated line sizing improvement.

Source/ASTextNode2.mm
It was only considering the individual constraint width/height when calculating the intrinsic size. However, this will not work when textnode is in a vertical ASStackLayoutSpec which also try to set a flexShrink. 
If it needs to calculate either height or width based on its own content where either of them is ambiguous, it needs to apply the proper line break mode and text alignment.
Related commit: https://github.com/TextureGroup/Texture/pull/1166/commits/a139d66c5d1d90ace6ef9adcaabe86d6df62bf38
=> ASTextNode2 to consider both width and height when determining if it is calculating an intrinsic size

CHANGELOG.md, Source/ASCollectionView.mm, Source/ASTableView.mm
The current approach we use to check if we should clear data if the dataSource / delegate changes via the `ASExperimentalClearDataDuringDeallocation` flag has some issue. The problem is that we are checking `_isDeallocating` and bail out if not true although we should only do that if the ASExperimentalClearDataDuringDeallocation flag is true.
We have the same change within `ASCollectionView`. We know from previous investigations (see #1155) that this currently can cause crashes. For consistency let's get this code over to `ASTableView` though with the experiments setup we have within `ASCollectionView`.
=> Fix logic cleaning data if delegate / dataSource changes and bring over logic to ASTableView

Source/ASNetworkImageNode.mm, Source/ASTextNode.mm, Source/Details/ASMainSerialQueue.mm, Source/Details/ASRecursiveUnfairLock.h, Source/Details/ASTraitCollection.h, Source/Private/TextExperiment/Component/ASTextLayout.m, Source/TextKit/ASTextKitFontSizeAdjuster.mm, Source/TextKit/ASTextKitRenderer.mm, Source/TextKit/ASTextKitTailTruncater.mm
The compiler is still not smart enough to notice that noescape blocks should not warn on retaining self 👎 but that's OK. This will clean up our CI logs a lot.
=> Address compiler warnings #trivial

Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.mm, Tests/ASButtonNodeTests.m, Tests/ASTextNodeTests.m
- Remove whitespace at the end of the line
- Fix indentation
- Wrap if check for assertion in ASDISPLAYNODE_ASSERTIONS_ENABLED
- Add testTextNodeSwitchWorksInMultiThreadEnvironment tests
=> Follow up cleanup #trivial

Source/ASDisplayNode.mm, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Tests/ASConfigurationTests.mm
Performing a layout pass within `didEnterPreloadState` can have a meaningful performance impact, enough that we should measure it as an ASConfiguration experimental feature.
=> Add experiment flag to skip layoutIfNeeded in enterPreloadState for ASM nodes #trivial

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm
We will revert #1023 until we find a different solution for the underlying issue.
The current solution introduces problems if we are unlocking before calling `_completePendingLayoutTransition` in `_u_measureNodeWithBoundsIfNecessary`. `_completePendingLayoutTransition` needs to be happening in one transaction if called from `_u_measureNodeWithBoundsIfNecessary`.
Unfortunately this also means we need to remove some of our locking assertions within subnodes insertion / removal methods.
=> Revert #1023 #trivial

Source/ASImageNode.mm
- Clear _displayCompletionBlock while we still have the node's instance lock. Because it may not be the same block by the time the lock is reacquired. In other words, it can happen that another thread sets a new display block after this thread releases the lock but before it reacquires it. And we don't want to clear out the new block.
- Reduce a lock/unlock pair which should help perf a tiny bit.
=> [ASImageNode] Fix a threading issue which can cause a display completion block to never be executed

Source/Details/ASThread.h
Might want to use split diff for this.
Just a major overhaul to clear some space. Note: AS_CHECK_LOCKING_SAFETY is gone – if we have asserts that are failing despite correct usage of our APIs, we need to comment them out and address them.
=> Clean up our mutex, fix try_lock not hooking into assert mechanism

Source/ASDisplayNode.mm
Locking assertions are always active now.
=> Remove CHECK_LOCKING_SAFETY check

Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/_ASDisplayViewAccessiblity.mm
Collections have their own handling in UIKit that we shouldn't mess with. As such no nodes that contain CollectionNodes should ever be treated as AccessibilityContainers.
=> Fix A11Y for horizontal collection nodes in Texture

Source/ASDisplayNode.mm, Source/ASNodeController+Beta.h, Source/ASNodeController+Beta.mm
This prevents lock-interleaving deadlocks. The controller and node should stay in sync with each other conceptually anyway.
=> Have node and controller share lock

Source/ASDisplayNode.mm
https://github.com/TextureGroup/Texture/pull/886 enforces that some nodes are loaded before they are sent a visiblity event, but it was not propagating the trait collection before forcing the load.
We are propagating traits in `_setSupernode:` (which was happening after the forced load). I moved the possible forced load to `_setSupernode:`, after propagating traits but before any visibility states are changed.
=> [ASDisplayNode] Propagate traits before loading a subnode

docs/_data/nav_development.yml, docs/_docs/development/automatic-subnode-layout.md, docs/_docs/development/cell-node-lifecycle.md, docs/_docs/development/collection-animations.md, docs/_docs/development/collection-asynchronous-updates.md, docs/_docs/development/components.md, docs/_docs/development/how-to-develop-and-debug.md, docs/_docs/development/layout-specs.md, docs/_docs/development/layout-transitions.md, docs/_docs/development/node-lifecycle.md, docs/_docs/development/overview.md, docs/_docs/development/structure.md, docs/_docs/development/threading.md, docs/_includes/nav_development.html, docs/_layouts/docs.html
This adds a structure for us add developer documentation too.
=> Add development docs structure

AsyncDisplayKit.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm
add more delegate methods for monitoring network image node progress so we can better keep track of optimization opportunity
=> add more delegate methods for monitoring network image node progress

Source/Details/ASTraitCollection.mm
With the changes to `ASPrimitiveTraitCollection` in https://github.com/TextureGroup/Texture/commit/e392f832f42897da41a7c0106709b55427efcea4 a new `ASPrimitiveTraitCollectionMakeDefault` was created. The new method didn’t give all values in an `ASPrimitiveTraitCollection` a default value (or initialize the struct with `{}`). This was causing fields like `userInterfaceIdiom`, `forceTouchCapability`, and `displayScale` to be filled with garbage, leading to `ASPrimitiveTraitCollectionIsEqualToASPrimitiveTraitCollection` to return `YES` when the trait collection hadn’t really changed.
It also looks like the getter `containerSize` was not implemented.
=> [ASPrimitiveTraitCollection] Fix ASPrimitiveTraitCollectionMakeDefault and implement containerSize

Source/Details/_ASCollectionViewCell.mm
This replaces #1268 that was unfortunately not enough to only forward the calls to the node. Extra checks need to be in place in case `UICollectionView`s animated updating API is used and hidden `UICollectionViewCell`'s are still within `UICollectionView`s subviews.
Thanks @stremsdoerfer for the initial PR!
=> Forward hitTest:withEvent and piontInside:withEvent: to node within _ASCollectionViewCell

Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Details/_ASDisplayViewAccessiblity.mm, Tests/ASConfigurationTests.mm, Tests/ASDisplayViewAccessibilityTests.mm
Disable because a11y not update correctly as layer backed nodes inserted/removed/updated. 
A few other case will fail otherwise as shown in tests. 
Fixes:  #1161
Attempt to invalidate a11y (instead of disable cache) code is here: https://github.com/TextureGroup/Texture/pull/1260 while does not seem worth the effort.
=> Disable a11y cache

Source/ASCollectionNode+Beta.h, Source/ASCollectionNode.mm, Source/ASCollectionView.mm, Source/ASCollectionViewProtocols.h, Source/ASSectionController.h, Source/ASSupplementaryNodeSource.h, Source/ASTableView.mm, Source/Details/ASCollectionInternal.h, Source/Details/ASDataController.h, Source/Details/ASDataController.mm, Source/Details/ASRangeController.h, Source/Details/ASRangeController.mm, Source/IGListAdapter+AsyncDisplayKit.mm, Source/Private/ASIGListAdapterBasedDataSource.h, Source/Private/ASIGListAdapterBasedDataSource.mm, Source/Private/_ASHierarchyChangeSet.h, Source/Private/_ASHierarchyChangeSet.mm, Tests/ASCollectionViewTests.mm
`ASCellLayoutMode`s  are flexible settings for applications to improve the flexibility of integrating Texture within an app. 
Providing this mode allows for developers to debug potential issues or work towards resolving technical debt in their collection view data source, while ramping up asynchronous collection layout.
=> Introduce ASCellLayoutMode

Source/Details/ASPINRemoteImageDownloader.mm
If PIN_ANIMATED is enabled, the creation of a PINRemoteImageManager
will create a sharedDownloader also. Thus we cannot assert that it
doesn't exist. We will move this assertion up to the methods that
create the preconfiguredSharedManager and before said manager is
allocated.
=> Move assertions so they are valid.

Source/ASCollectionView.mm
Most ASCellNodeBlocks are wrapped by ASCollectionView.mm to add an `interactionDelegate` as well as calling `enterHierarchyState` on the node and setting its transform to a reflection if `inverted` is set on the collectionView.
This PR adds this behavior to supplementary nodes as well.
=> Wrap supplementary node blocks to enable resizing them.

Source/ASTableNode.mm, Tests/ASTableViewTests.mm
Before ASTableView is loaded, the property `automaticallyAdjustsContentOffset` is stored on `pendingState` but never set to view.
This PR may fix this issue #23.
=> Set automaticallyAdjustsContentOffset to ASTableView when view is load

Source/ASTextNode.mm, Source/ASTextNode2.mm
Make global static a function local static. This stops it from being initialized premain and affecting startup time.
=> Reduce startup time.

Schemas/configuration.json, Source/ASCollectionView.mm, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASTableView.mm, Tests/ASConfigurationTests.mm
Through crashes in the past, we established that:
1. We can't clear data if the collection/table view is still being used. (#1155)
2. We may clear data during deallocation, and even so, we want to do it if user is in `ASExperimentalClearDataDuringDeallocation` experiment.
As such, the logic change introduced in #1200 is not correct. It causes `-clearData` to **always** be executed if user is not in the experiment (which is true by default).
I suspect what you wanted to do is setting up an experiment and hook up with Texture. And even then, we need to fix the implementation of `clearData`. I'm seeing a crash in production (1st screenshot below) which looks like a memory issue when `self` (i.e the collection view) is gone and accessing the editing queue (i.e …
=> Add a way to opt out of always-clear-data behavior in ASCollectionView and ASTableView

Source/ASCollectionView.mm
As of today, ASRangeController doesn't manage the interfaceState for supplementary nodes. This bug was introduced with a refactoring of this code a couple months ago.
With this change, the supplementary nodes will automatically enter each interfaceState bit when they are added to a view hierarchy.
=> [ASCollectionView] Supplementary nodes should not enter ASHierarchyStateRangeManaged.

docs/_docs/corner-rounding.md
=> performance spell correction

examples/ASDKgram/Sample.xcodeproj/project.pbxproj, examples/ASDKgram/Sample/Availability.h, examples/ASDKgram/Sample/FeedHeaderNode.m, examples/ASDKgram/Sample/PhotoCellNode.m, examples/ASDKgram/Sample/PhotoFeedSectionController.m, examples/ASDKgram/Sample/TailLoadingNode.m
- Fix Yoga layout within `PhotoCellNode`
- Add Yoga layout support to `FeedHeaderNode` and `TailLoadingNode`
=> Add Yoga layout to ASDKGram Texture cells

Schemas/configuration.json, Source/ASCollectionView.mm, Source/ASCollectionViewProtocols.h, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASTableView.mm, Tests/ASCollectionViewTests.mm, Tests/ASConfigurationTests.mm
- `exp_skip_a11y_wait`: An experiment that skips a wait when accessibility elements of a collection/table view is collected. The wait was introduced in #1217. We suspect this causes some perf regressions and need to confirm via an experiment.
- `exp_skip_default_cell_layout_mode`: An experiment that skips a new default behavior of `ASCellLayoutModeNone`, introduced in #1273. The new behavior blocks main thread when 1) the collection/table view reloads data (including the initial load and any subsequent ones), 2) there is a small number of async cells to be laid out, or 3) the collection/table view hasn't had enough content to fill the visible viewport. While I agree that this new behavior may help with display latency when it's more important than FPS (i.e during app startup), I'm not …
=> Add experiments to skip waiting for updates of collection and table views

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASCellNode.mm, Source/ASDisplayNode+Beta.h, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+LayoutSpec.h, Source/ASDisplayNode+LayoutSpec.mm, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode+Yoga.h, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASImageNode.mm, Source/Details/_ASDisplayViewAccessiblity.mm, Source/Private/ASDisplayNodeInternal.h, Source/Private/ASLayoutTransition.mm, Tests/ASDisplayNodeTests.mm
Currently most of the layout spec code is tightly coupled to `ASDisplayNode` and yoga related layout logic is guarded by multiple compiler flag.
This PR tries to separate layout code logic a bit by moving it into different files and categories on `ASDisplayNode`. This is a first small step to separate and should give us a good base for even separate them more.
=> Improve separation of code for layout method types

Source/ASDisplayNode+Beta.h, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Base/ASBaseDefines.h, examples/CatDealsCollectionView/Sample.xcodeproj/project.pbxproj, examples/CatDealsCollectionView/Sample/ASDisplayNode+CatDeals.h, examples/CatDealsCollectionView/Sample/ASDisplayNode+CatDeals.mm, examples/CatDealsCollectionView/Sample/ItemNode.m
right at the outset: 
- Causes no compiler warnings
- Does nothing unsafe or undocumented
Node controllers were added as a way for clients to customize node behavior globally. If you subclass ASTextNode and ASImageNode, you have to duplicate any common logic you want to add.
Node controllers however introduce additional complexity and duplication – if ASNetworkImageNode can fire off network requests, why does it need a controller? Nodes are in fact a sort of tiny view controller and we should stick with the original abstraction instead of adding a different one in.
This diff does something pretty strange, but I think useful. It modifies the node API to (1) offer a public ivar to ASDisplayNode and (2) guarantee that certain `ASDisplayNode+Subclass` category methods e.g. interface state …
=> Add extension points for global node behaviors, potentially replacing interface state delegates

Source/ASSectionController.h, Source/ASSupplementaryNodeSource.h, Source/Private/ASIGListAdapterBasedDataSource.mm
After #1273 was merged it's possible to implement either `nodeBlockForItemAtIndex:` or `nodeForItemAtIndex:` in the `ASSectionController` case and `nodeBlockForSupplementaryElementOfKind:atIndex:` or `nodeForSupplementaryElementOfKind:atIndex` in the `ASSupplementaryNodeSource` case.
As it's an or case now instead of having the required we move them to optional and throw an assertion if no one of the two is implemented.
=> Move ASSectionController and ASSupplementaryNodeSource method to be optional

Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Private/ASDispatch.mm, Tests/ASConfigurationTests.mm
This has shown performance wins against our current core_count*2 approach in some profiling, possibly due to reduced context switching.
=> Add an experimental flag to use native dispatch_apply

Source/ASNodeController+Beta.h, Source/ASNodeController+Beta.mm
Reverts TextureGroup/Texture#1227
This problem with this is, if you call `self.node` from within `-createNode` (say, a few methods deep) you will not have finished creating the node and you'll get a deadlock. Using a recursive mutex you would get infinite recursion. Using some kind of flag you would get nil.
Until we can think through the best fix here, reverting.
=> Revert "Have node and controller share lock"

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+Yoga.h, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.mm, Source/ASNodeController+Beta.h, Source/ASNodeController+Beta.mm, Source/ASScrollNode.mm
Yoga layout will try to acquire locks from above node during layout, which is Bad under our conventions. So we must acquire locks for all ancestor nodes before beginning so we do not create a deadlock with some other thread trying to lock downward (which is Good).
1) lock to root for tree
2) lock self to change parent (& consequently root)
3) add lockPair to try-lock node & controller together
4) lock controllers if they exist in lockToRoot...
5) disable some asserts due to lock to root. :(
=> Lock up to yogaRoot during layout to avoid deadlocks.

Source/ASCollectionView.mm
Like it says on the tin, if content isn't ready we can't do valid calculations to see if batching is necessary.
=> Setting leading screens was causing fetch every time if content wasn't ready

Source/ASDisplayNode+Layout.mm
Doing so leaves it locked when we elsewhere explicitly unlock the node to ascend.
=> Do not lock the nodeController if we are not locking to root.

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+Yoga.mm, Source/Layout/ASLayoutElement.mm
I didn't write this so ask @Adlai-Holler "not Tim Rowe" if there's any questions 😛
=> Add `setNeedsLayout` to yoga tree changes.

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/AsyncDisplayKit.h
I'm having a problem with using AsyncDisplayKit with Carthage.
I've previously used Cocoapods with my project, but whilst changing to Carthage, I noticed that ASCollectionElement.h is private.
I presume this is a mistake as ASCollectionElement is referenced in other public headers in this project.
=> Make ASCollectionElement Public

Source/ASDisplayNode+Layout.mm, Source/Base/ASBaseDefines.h
This method is actually pretty painful in today's world. In one iPad mini trace, the first page of nodes spent 6.6ms in this call, just in time profiler.
This only affects Yoga users currently.
=> Optimize _assertSubnodeState

Source/Details/_ASCollectionViewCell.mm
Hi,
The first step of this modification was:
- The node can have a transformation, the point is not converted to the scaled node.
Second step:
use convertPoint
`
CGPoint pointOnNode = [self.node.view convertPoint:point fromView:self]
return [self.node hitTest:pointOnNode withEvent:event];
`
But...
With this situation
- _ASCollectionViewCell calls ASDisplayNode
- ASDisplayNode calls ASDisplayView1
- ASDisplayView1 calls ASDisplayNode
- ASDisplayNode calls ASDisplayView1
- ASDisplayView1 calls Super.... finished
We need to calculate the new point (for node with view only, because touch for layerBacked is not supported)
This this modification, we win 1 loop for nothing...
- _ASCollectionViewCell calls ASDisplayView
- ASDisplayView1 calls ASDisplayNode
- ASDisplayNode calls ASDisplayView1
- …
=> _ASCollectionViewCell - The point isn't converted before to send to node, impossible to touch button into the node hierarchy

Source/ASDisplayNode.mm, Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm, Tests/ASDisplayNodeTestsHelper.mm
This queue is extremely busy, since every single node enters it on every single interface state change on the main thread.
Avoid waking up the run loop for every single node.
Avoid a ton of NSPointerArray overhead that we don't need.
Avoid retain/release traffic on the singleton by using an inline function. I confirmed that in release mode, the static __strong is correctly inlined and no ARC traffic is incurred.
I will post some traces in a little while.
=> Optimize ASCATransactionQueue

Source/Details/_ASDisplayViewAccessiblity.mm, Tests/ASDisplayViewAccessibilityTests.mm
I was working on accessibility in our app and noticed these weren't implemented yet. There's no checking if the node implements the method because `NSObject` provides default implementations.
=> Add forwarding of UIAccessibilityAction methods

Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASNetworkImageNode.mm, Tests/ASConfigurationTests.mm, Tests/ASNetworkImageNodeTests.mm
This showed performance gains for us on startup when the main thread was under heavy contention.
=> Launches switching ASNetworkImageNode callbacks to global queue.

Source/ASTextNode2.mm
Instead of only looking at the point you actually touched, this searches in a 44x44 rect around the touch to find any links you might have hit. Similar behavior from ASTextNode1.
=> Make ASTextNode2 more forgiving when searching for links

Podfile.lock, Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASMultiplexImageNode.mm, Source/ASNetworkImageNode.mm, Source/Details/ASBasicImageDownloader.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.mm, Source/Private/ASInternalHelpers.h, Tests/ASConfigurationTests.mm
Right now when an image node enters preload state, we kick off an image request with the default priority. Then when it enters display state, we change the priority to "imminent" which is mapped to the default priority as well. This means that requests from preload and display nodes have the same priority and are put to the same pool. The right behavior would be that preload requests should have a lower priority from the beginning.
Another problem is that, due to the execution order of -didEnter(Preload|Display|Visible)State calls, a node may kick off a low priority request when it enters preload state even though it knows that it's also visible. By the time -didEnterVisibleState is called, the low priority request may have already been consumed and the download/data task won't pick up …
=> Experiment with different strategies for image downloader priority

Source/Details/ASRangeController.mm
Luckily it seems this didn't cause huge memory bloat because there's
a check below that keeps the display flag from being set in low memory
conditions when the node is off the screen.
=> Whoops, someone forgot an else!

Source/ASTextNode2.mm
Found by Clang Static Analyzer:
```
~/Texture/Source/ASTextNode2.mm:663:39: warning: Potential leak of an object stored into 'truncationTokenLine'
CTLineRef truncationTokenLine = CTLineCreateWithAttributedString((CFAttributedStringRef)_truncationAttributedText);
^
~/Texture/Source/ASTextNode2.mm:666:49: warning: Potential leak of an object stored into 'additionalTruncationTokenLine'
CTLineRef additionalTruncationTokenLine = CTLineCreateWithAttributedString((CFAttributedStringRef)_additionalTruncationMessage);
^
2 warnings generated.
```
=> Fix CTLineRef leaks

Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASTextNode.mm, Source/Details/_ASDisplayLayer.h, Tests/ASConfigurationTests.mm
In many cases this reduces the backing store of text nodes by 1/2.
=> Adds support for using UIGraphicsImageRenderer in ASTextNode.

Source/Private/ASMutableElementMap.mm
Found by Clang Static Analyzer:
```
~/Texture/Source/Private/ASMutableElementMap.mm:32:24: warning: Conversion from value of type 'NSMutableArray<NSMutableArray *> *' to incompatible type 'ASMutableCollectionElementTwoDimensionalArray *'
_sectionsOfItems = (id)ASTwoDimensionalArrayDeepMutableCopy(items);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
=> Clean up a clang analyzer cast error

Source/ASConfigurationInternal.h, Source/ASConfigurationInternal.mm
- Use `dispatch_once` when not debugging.
- Clean up the singleton – replace the method + macro with an inline function.
=> Make experiment checks faster

Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm
Basically NS_INLINE means "static inline" and the static part means each call site of this function got its own copy. Using just plain inline isn't really an option either because it would mean that each module would get its own. In practice that's OK since it's private to Texture but better just to make it extern.
Fixes the unit tests when running with interface coalescing on. The unit tests wait on this queue, and they were waiting on the wrong queue!
=> Make shared CA transaction queue variable extern so it's actually shared

Source/ASDisplayNode.h, examples/CatDealsCollectionView/Sample/ASDisplayNode+CatDeals.mm
Naming this context will cause us a bunch of problems. Can we rename before we release this?
=> Naming ivar context can conflict with subclasses

Tests/ASSnapshotTestCase.h, Tests/ASTableViewTests.mm, Tests/ASTextKitTests.mm
These headers fail `-Wdocumentation`. Only adding local warning supression so the warning remains in the Texture code base. Fixes #1400
=> Suppress documentation warnings when using external libraries

Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Details/UIView+ASConvenience.h, Source/Details/_ASDisplayLayer.mm, Source/Details/_ASDisplayView.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/ASDisplayNodeInternal.h, Source/Private/_ASPendingState.mm, Tests/ASDisplayNodeTests.mm
- Make `_ASDisplayView` forward `actionForLayer:forKey:` to the node, so now nodes get that call for view and layer backed nodes.
- Remove `_ASDisplayView will/didMoveToWindow` since we can derive that information from `actionForLayer:` just like layer-backed nodes do.
- Add a base-implementable node method `layerActionForKey:` that the node will call.
- Add bridging for the `CALayer.actions` property so you can set up your actions off-main.
This makes it possible to add pretty broad animation support outside of the `transitionLayoutWithSizeRange:` pipeline.
=> Add layer-action support to nodes

Source/Details/ASMainSerialQueue.mm
There is no point to lock after `runBlocks` only to unlock right afterward.
=> Avoid an unnecessary lock & unlock pair in ASMainSerialQueue

.clang-format, format
@Adlai-Holler @appleguy @nguyenhuy @garrettmoon I would appreciate for any input on the code format. For now I added a `.clang-format` file to discuss and iterate on.
Preview: https://github.com/TextureGroup/Texture/compare/master...MSClangFormatPreview
=> Add clang-format for a common source code format

Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Details/ASRangeController.mm, Tests/ASConfigurationTests.mm
When a visible collection/table view is about to become invisible, we tell its range controller to update (see https://github.com/TextureGroup/Texture/pull/882). However, [an optimization in ASRangeController](https://github.com/TextureGroup/Texture/commit/90a1bb23469a38820adc681fca4aac23ea5c77ed) doesn't expect that. Instead, it assumes that the view is **invisible** and going to be **visible** soon. As a result, it tells cell nodes in *all* ranges to start preloading and rendering, including nodes that weren't even in the display range. To react to that, those nodes [put themselves into the rendering queue](https://github.com/TextureGroup/Texture/blob/master/Source/ASDisplayNode.mm#L2955) which causes them to load their back store (view/layer).
Since ASRangeController is such a …
=> Fix a bug in ASRangeController that causes cell nodes to render unnecessarily

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+Yoga.h, Source/ASDisplayNode+Yoga.mm, Source/Private/ASDisplayNodeInternal.h
Unfortunately I'm unable to add a test easily because Yoga tests aren't setup in the CI yet.
However, this can be reproduced and confirmed fix by the following code:
ASDisplayNode *child1 = [[ASDisplayNode alloc] init];
child1.style.width = ASDimensionMake(ASDimensionUnitPoints, 10);
child1.style.height = ASDimensionMake(ASDimensionUnitPoints, 10);
child1.style.margin = ASEdgeInsetsMake(UIEdgeInsetsMake(5, 5, 5, 5);
ASDisplayNode *child2 = [[ASDisplayNode alloc] init];
child2.style.width = ASDimensionMake(ASDimensionUnitPoints, 10);
child2.style.height = ASDimensionMake(ASDimensionUnitPoints, 10);
ASDisplayNode *canvas = [[ASDisplayNode alloc] init];
canvas.style.width = ASDimensionMake(ASDimensionUnitPoints, 100);
canvas.style.height = ASDimensionMake(ASDimensionUnitPoints, 100); …
=> Fix a bug with Yoga nodes whose position change and don't update.

Source/Details/ASRangeController.mm
The changes in #1418 is a bit too aggressive when it comes to nodes that are in display range. It forces those nodes to not preload.
Also update the changes to avoid diluting the experiment data by triggering too broadly (i.e avoid triggering when the old and new implementations yield the same result leading to no behavior change).
=> Follow up on the ASRangeController fix in #1418

docs/Gemfile
See issue #1321 jekyll 3.6.3 has no compatible github-pages version
=> Removed locked jekyll version

Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASViewController.mm, Tests/ASConfigurationTests.mm
The release in `-[ASRunLoopQueue releaseObjectInBackground]` might not actually be doing everything necessary to free memory.
=> Experiment with disabling background dealloc for ASViewController

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/Details/Transactions/_ASAsyncTransactionContainer.mm, Tests/ASTransactionTests.mm
Add unit tests that help find cycles. `-testWeakWithSingleOperation` fails without the code fix applied.
=> Fix retain cycle with transaction operations

Source/ASConfigurationDelegate.h, Source/ASDisplayNode.mm, Source/Private/ASTipsController.mm
With the latest version of Xcode installed I was getting this dyld error at app launch time:
```Swift class extensions and categories on Swift classes are not allowed to have +load methods```
It looks like it's possible to replace `+load` methods with a static `__attribute__((constructor))` function without making dyld angry.
=> Replace +load initializers with __attribute__((constructor)) functions

Source/ASImageNode.mm
If the image is opaque, and it fills the context, the context can be opaque regardless of whether they set the flag on the node.
=> Have image nodes draw into opaque contexts automatically if possible

Source/ASDisplayNode+Layout.mm
We came across an infinite layout loop in `_u_measureNodeWithBoundsIfNecessary`. After requesting a layout from above, the sizes between pending and caluclated layout still do not match. We continue to prefer to use the pending layout and ask for another layout loop from above. We can’t seem to break out of this loop. The solution (thanks to Huy for the guidance) was to nil out the pending layout we get from requesting the layout from above.
I was only able to reproduce this when working with a node in a `UINavigationBarItem’s` `titleView`. I think that UIKit must be doing something sneaky with setting the frame on the view. While I was not able to create a unit test to catch this issue (I tried for a long time, and can post what I’ve come up with to see if anyone has any suggestions), I …
=> [ASDisplayNode] Stop infinite layout in _u_measureNodeWithBoundsIfNecessary

Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Details/Transactions/_ASAsyncTransactionContainer.mm, Tests/ASConfigurationTests.mm, Tests/ASTransactionTests.mm
=> Wrap transaction operation retain cycle fix in an experiment

Source/ASDisplayNode.mm
As the comment says, we return kCFNull from +defaultActionForKey:. Stubbing this to nil is important so that CA will search the actions and style.actions dictionaries for layer actions.
=> Fix the stub for layerActionForKey: to let CA continue the search

Source/ASImageNode.mm
Reverts TextureGroup/Texture#1432
I like this diff, but as I bet Pinterest realized, it doesn't play well with image/context modification blocks that expect a transparent context. Revert for now.
=> Revert "Have image nodes draw into opaque contexts automatically if possible"

Source/ASTextNode.mm, Source/ASTextNode2.mm, Tests/ASTextNode2Tests.mm, Tests/ASTextNodeTests.mm
I'd like to propose a change in the way `isAccessibilityElement` is updated when setting the `attributedText` property on `ASTextNode` and `ASTextNode2`. 
Currently this always happen when the `attributedText` property is updated. This makes sense in most cases. But when you set a string and you configure the text node's `isAccessibilityElement` property to `NO`, it will change back to yes if you update the string. Meaning you always need to update `isAccessibilityElement` after updating the text. 
I think that in the case where the `attributedText` property has been set, and the `isAccessibilityElement` has been explicitly set to `NO`, and you update the text (not set the property to `nil`) it makes sense to respect this setting and making the user of the text node responsible for …
=> [Text Nodes] Maintain isAccessibilityElement setting on text nodes when updating text

Source/Base/ASLog.h
On an A8 in a large app, creating & tearing these down can take ~80us in some cases. Since using activity data in production hasn't really caught on at all, let's limit this to debug.
=> Only create activities during debug

Source/ASDisplayNode.mm, Source/ASTextNode.mm, Source/ASVisibilityProtocols.h
1. Remove lock of ASTextNodeRendererKey, don't provide property readwrite for external.
2. Add `nil` and `class kind` check for `isEqual:`.
=> Remove lock of ASTextNodeRendererKey

Source/ASCollectionNode.h, Source/ASCollectionNode.mm, Source/ASCollectionView.h, Source/ASCollectionView.mm
Adding the ability for ASCollectionNode’s subclasses to customize the behavior of its default panGestureRecognizer.
With texture and UIKit, you can't assign a collection's default pan gesture delegate to an instance other than the collectionView itself, so for code like this `self.pagerNode.view.panGestureRecognizer.delegate = self;`, UIKit would raise the following exception:
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'UIScrollView's built-in pan gesture recognizer must have its scroll view as its delegate.'`
I don't see any other way to do this since Texture's collectionNode wraps its underlying view and users of this class would not be able to subclass the view.
=> Make ASCollectionNode's pan gesture customizable

Source/ASCollectionView.mm, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode.mm, Source/ASMainThreadDeallocation.mm, Source/ASMultiplexImageNode.mm, Source/ASNavigationController.mm, Source/ASTabBarController.mm, Source/ASViewController.mm, Source/Base/ASLog.h, Source/Base/ASLog.mm, Source/Details/ASBatchContext.mm, Source/Details/ASDataController.mm
=> Remove iOS 8 logging support

Source/Private/ASDisplayNode+AsyncDisplay.mm
iOS attempts to automatically close these when the thread exits, but some versions (at least iOS 10, checking others) have a bug which causes it to just keep spinning indefinitely.
cc @garrettmoon @nguyenhuy @ay8s Everyone should cherry-pick this into any branches that include #1458.
=> Fix open context bug introduced in #1458

Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h
Found this by enabling `#pragma clang diagnostic error "-Wobjc-missing-property-synthesis"` for `ASDisplayNode`. One property is unused, saving 8 bytes of heap space per instance on 64-bit builds. Implement setter/getters for these properties, and add appropriate locking. add the warning as error to the build for this file.
=> Make sure all ASDisplayNode properties have backing ivars for consistency.

Source/ASControlNode.h, Source/ASControlNode.mm
Enable `#pragma clang diagnostic error "-Wobjc-missing-property-synthesis"` for this file.
=> Ensure ASControlMode properties lock before accessing their ivars

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASDisplayNode.mm, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASImageNode.mm, Source/ASMapNode.mm, Source/Debug/AsyncDisplayKit+Debug.mm, Source/Details/ASGraphicsContext.h, Source/Details/ASGraphicsContext.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/UIImage+ASConvenience.mm, Tests/ASConfigurationTests.mm
Make sure to turn on "ignore whitespace" when viewing the diff.
=> Add a new "global drawing" experiment to use UIGraphicsRenderer

.github_changelog_generator, CHANGELOG.md, Texture.podspec
This diff updates `Texture.podspec`, `CHANGELOG.md` and `.github_changelog_generator` on master to match what went into `2.8.1` release. Note that this release is **not** based off master but the 2.8 release tag. See the [release branch](https://github.com/TextureGroup/Texture/tree/2.8.1) for details.
=> Cut version 2.8.1 #changelog

Source/ASCollectionNode.mm, Source/ASCollectionViewProtocols.h, Source/Details/ASLayoutRangeType.h
These objects accumulate in the heap, so reducing their size will allow more to accumulate before memory warnings.
Group the `BOOL`s into a struct. Shrink the various stored `enum`s to fit the size of their contents. Move the ivars around so that the smaller `enum` are near each other and the bitfield struct.
=> Shrink _ASCollectionPendingState from 144 to 128 bytes, a 12.5% reduction

Source/Private/_ASPendingState.mm
These objects accumulate in the heap, so reducing their size will allow more to accumulate before memory warnings.
Shrink ASPendingState `BOOL`s. Use `unsigned int` for these bitfields for clarity. Separate from `_flags` as that struct is compared to `0` for testing. The `_boolFlags` struct is just storing other `BOOL`s.
=> Shrink _ASPendingState from 824 to 808 bytes, reduction of ~2%

Source/ASDisplayNode+Beta.h, Source/ASDisplayNode+InterfaceState.h, Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+Yoga.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASImageNode.mm, Source/Private/ASDisplayNode+FrameworkPrivate.h, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/ASDisplayNodeInternal.h
These objects accumulate in the heap, so reducing their size will allow more to accumulate before memory warnings.
Group the `BOOL`s into a struct. Shrink the various stored `enum`s to fit the size of their contents. Move the ivars around so that the smaller `enum` are near eachother and the bitfield struct.
=> Shrink ASDisplayNode from 1072 to 968 bytes, reduction of 10.74%

Source/ASButtonNode+Private.h, Source/ASButtonNode.h, Source/Layout/ASStackLayoutDefines.h
Button: 1312 to 1288 bytes, running on iPhone SE simulator. 1.9% reduction.
Shrink the enums it stores, and place them next to each other (along with a BOOL) to reduce instance size.
=> Shrink Button Node

Source/ASTextNode.mm, Source/ASTextNode2.mm, Source/ASTextNodeCommon.h
Running in iPhone SE Simulator:
- ASTextNode: 1360 to 1352 bytes .6% reduction
- ASTextNode2: 1360 to 1304 bytes 4.3% reduction
Shrink stored enum sizes. Group BOOLs near these smaller enums. Override -usingExperiment to return constant instead of never set, but allocated ivar.
=> Shrink TextNode(2)

Source/ASPagerNode.mm, Source/Details/ASRangeController.mm, Source/Details/ASScrollDirection.h
Running on iPhone SE Simulator:
ASPagerNode 1240 to 1232 bytes .7% reduction
ASScrollNode 1104 to 1096 bytes .7% reduction
- make ASScrollNode smaller by shrinking ASScrollDirection, which requires a change to ASRangeController
- shrink ASPagerNode by declaring the BOOL next to the struct
=> Shrink Pager and Scroll Node

Source/ASControlNode.h, Source/ASControlNode.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h
Revert "Ensure ASControlMode properties lock before accessing their ivars (#1476)"
This reverts commit ce1e1956f402a7b762119b0f5fa8df4fccd927e6.
Revert "Make sure all ASDisplayNode properties have backing ivars for consistency. (#1475)"
This reverts commit d6061f4390f64d0faff1b3432084362f8f9e147d.
- Except the unused property `interfaceStateSuspended` is still removed (this is a memory saver).
=> Keep the atomics - does not affect memory reduction work

Source/ASCellNode.mm
Group the BOOLs together, since there are only 4 (and there are no other auto-generated ivars that are < 64 bits) this is sufficient and keeps the properties `atomic`.
=> Shrink ASCellNode by 8 bytes

Source/ASDisplayNode.mm, Source/ASRunLoopQueue.mm, Source/Base/ASBaseDefines.h, Source/Base/ASLog.h, Source/Base/ASLog.mm, Source/Base/ASSignpost.h, Source/Details/ASDataController.mm, Source/Details/ASObjectDescriptionHelpers.mm, Source/Details/ASRangeController.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/Private/ASInternalHelpers.mm
- Removes support for colored intervals. These weren't really useful and they aren't part of the signpost api.
- Fixes warnings when building for profiling.
- Fixes an issue with range controller interval logging.
- Adds an interval for interface orientation changes.
- Removes some enum values that aren't used.
- Still has no impact when not profiling.
Tested on iOS 10 and iOS 12.
=> ASSignpost: Add support for the os_signpost API, fixes

Source/Layout/ASLayoutElement.h
- Shrink the enum. Save 8 bytes. There are 1000s of these in the heap after running Pinterest for 10 minutes.
=> Shrink ASLayout

Source/Layout/ASStackLayoutDefines.h
- Resize enums to make `ASStackLayoutSpec` 40 bytes smaller. This applies to the subclasses too.
=> Shrink LayoutSpec classes

Source/Details/Transactions/_ASAsyncTransactionContainer+Private.h, Source/Details/Transactions/_ASAsyncTransactionContainer.mm, Source/Private/ASInternalHelpers.h, Source/Private/ASInternalHelpers.mm
Scrolling down to the end of a feed (~100 items) on my iPad this data had:
=> Reclaim CALayer asyncTransactions, use pointer-based NSMutableSet instead

Source/ASDisplayNode.mm
There's a lot more we could do to optimize this, but at least this makes the memory growth curve less steep. @bolsinga 💕
=> Discard _pendingDisplayNodes after subtree is rendered

Source/Details/_ASDisplayViewAccessiblity.mm
We should assign the `accessibilityElements` to the `_accessibilityElements` property.
=> Assign accessibilityElements to _accessibilityElements

Source/ASDisplayNode.mm, Source/Details/_ASDisplayView.h, Source/Details/_ASDisplayView.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/ASDisplayNodeInternal.h
Use same flag paradigm we use within `-[_ASDisplayView hitTest:withEvent:]` and `-[_ASDisplayView pointInside:withEvent:]` for responder chain methods.
=> Use flag for responder chain methods between view and node dispatching

Source/ASMultiplexImageNode.h
AS_USE_PHOTOS currently allows opting out of linking with the Photos framework / Photos features of Texture, however with the ASMultiplexImageNode header, it still imports from the Photos framework and when "Automatically Link with Frameworks" is enabled, it'll link with Photos.framework.
This fixes that by conditionally importing / excluding unavailable API based on whether or not AS_USE_PHOTOS is enabled.
=> Fix Opting-Out of Linking with Photos Framework

Source/Private/TextExperiment/Component/ASTextLayout.mm, Source/Private/TextExperiment/Component/ASTextLine.mm
=> Don't eagerly create arrays for attachments in ASTextNode2

docs/_docs/development/how-to-develop-and-debug.md, docs/_docs/development/how-to-develop.md
Quick guide on how to start developing with Texture.
=> [Dev docs] How to develop with Texture

Source/ASDisplayNode.mm, Source/Details/_ASDisplayView.mm
After #1396, some view-backed nodes in our app stop responding to tap events. I tracked this issue down to [this change](https://github.com/TextureGroup/Texture/pull/1396/files#diff-7fbc7d84a259cbfbee7546a5310dddcfR162) which suggests that the order of execution matters.
This diff attempts to fix the issue by restoring the previous call order where `__enterHierarchy` and `__exitHierarchy` are driven by `_ASDisplayView`'s `-willMoveToWindow:` and `-didMoveToWindow` if the node is view-backed. Layer-backed nodes will still call `__enterHierarchy`/`__exitHierarchy` when they get `kCAOnOrderIn`/`kCAOnOrderOut`.
This maintains the layer-action support introduced in #1396.
=> Restore call pattern where UIView methods drive __enterHierarchy and __exitHierarchy for view-backed nodes

Source/ASCellNode.mm, Source/Details/ASCollectionElement.mm, Source/Private/ASCellNode+Internal.h
The pointer is available via the node's `collectionElement`. There is no point to store it again in the node. Removing the ivar helps to reduce the memory footprint of ASCellNode and avoid the need to set it.
=> Remove ivar of ASCellNode.owningNode

docs/_docs/development/collection-asynchronous-updates.md
This document describes the internal workings of ASCollectionNode, ASPagerNode, and ASTableNode, specifically how they handle asynchronous batch updates and then forward them to their backing UICollectionView or UITableView.
Let me know if there is anything else I should mention/explain more, as well as any other feedback. Thanks!
=> [Dev doc] Collections and asynchronous updates

Source/ASTextNode2.mm, Tests/ASTextNode2Tests.mm
`[NSAttributedString enumerateAttribute:inRange:options:usingBlock]` can be called multiple times with a value of nil. The current logic didn't consider this to find out if a links is present within the attributed string.
=> Fix ASTextNode2 supportsLayerBacking

Source/ASDisplayNode.mm, Tests/ASDisplayNodeTests.mm
Placeholder is not working anymore since `placeholderEnabled` is read from _flags but never set to it.
```
if (_flags.placeholderEnabled && !_placeholderImage && [self _locked_displaysAsynchronously]) {
```
```
- (BOOL)_locked_shouldHavePlaceholderLayer
{
DISABLED_ASAssertLocked(__instanceLock__);
return (_flags.placeholderEnabled && [self _implementsDisplay]);
}
```
=> Fix placeholder

Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Details/ASDataController.mm, Tests/ASCollectionModernDataSourceTests.mm, Tests/ASCollectionViewTests.mm, Tests/ASCollectionViewThrashTests.mm, Tests/ASConfigurationTests.mm, Tests/ASTableViewTests.mm, Tests/ASTableViewThrashTests.mm
Step 1 of the pipeline is on main thread and needs pendingMap which was updated by the end of step 1 of the run. And step 1 operates on data source index space. So it should be ok to start it ASAP -- without waiting for any running work on the background editing queue.
One potential race condition after this change is that it's possible for main thread to query the data source (step 1) while the editing queue consumes the last change set (step 3). However, as long as the client's each nodeBlock and the node's layout code capture/reference an individual model object (as opposed to the whole data set) -- which is what clients are supposed to do anyways, then everything should be fine.
The benefit of this diff is that the pipeline will be able to accept many more change sets within a short …
=> [ASDataController] Add an experiment that avoids flushing editing queue before starting the data pipeline pipeline

Source/ASButtonNode.mm, Tests/ASButtonNodeTests.mm
We use the `ASButtonNode` as a pure icon button that has no title, and I also give this button an accessibility label. Since this buttton's `titleNode` will be non-nil if the `self.titleNode` getter is ever called, my accessibility label will get reset to empty string every time the button's state changes (`selected`, `enabled`, etc.). However, I'd like my button's accessibility label to remain consistent in this case. This PR addresses this problem, i.e. if the button title and the new title are both either empty or nil, we do not reset the accessibility label. Also added corresponding test.
=> Fixes accessibilityLabel bug on ASButtonNode that has no title

Source/TextKit/ASTextKitCoreTextAdditions.mm
In iOS13, there is an issue with the font returned from "-[UIFontj fontWithName:size:]". When asking for "SFUI-Regular" returns "Times New Roman" font. It seems like a reasonable default would be to return the system font in the case that the requested font was not respected.
=> Bridge CTFontRef directly to UIFont when converting attributes on NSAttributedString

Source/Details/ASRangeController.mm
Fix the following warning in the build process:
```
⚠️  /Texture/Source/Details/ASRangeController.mm:402:66: 'scrollableDirections' is deprecated: Use ASCollectionNode property instead. [-Wdeprecated-declarations]
```
=> Fix the build warning in `ASRangeController.mm`

docs/_docs/development/overview.md
The Getting Started page has a nice one pager on the different parts of Texture. Link to that page if any reader needs the simple overview.
=> [dev docs] Add link to Getting Started to Overview page

Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm
There is a missing delegate when image cannot load from cache.
=> add new networking image delegate method when image does not load from cache

Source/Details/UIView+ASConvenience.h, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASPendingState.mm
Given that UIColor is now a dynamic provider we can no longer rely on the fact that there is a 1:1 mapping between UIColor <-> CGColorRef.
I've updated the UIViewBridge and ASPendingState accordingly to use UIColor and translate to CGColorRef only when interacting with layers. This should preserve any dynamic capabilities we might need in the future when trying to re-render layer backed nodes.
Depends on https://github.com/TextureGroup/Texture/pull/1588
=> Update ASPendingState backgroundColor type to UIColor

Source/Details/UIView+ASConvenience.h, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASPendingState.mm
Prevent losing its new dynamic capabilties
Just putting up this PR since the last one merged into my feature branch instead of master
https://github.com/TextureGroup/Texture/pull/1592
=> Update Pending state type for backgroundColor to UIColor

examples/ASDKTube/Sample/Controller/VideoFeedNodeController.m, examples/CustomCollectionView-Swift/Sample/ViewController.swift, examples/HorizontalWithinVerticalScrolling/Sample/ViewController.m, examples/Kittens/Sample/ViewController.m, examples/LayoutSpecExamples-Swift/Sample/OverviewViewController.swift, examples/LayoutSpecExamples/Sample/OverviewViewController.m, examples/Swift/Sample/ViewController.swift, examples/VerticalWithinHorizontalScrolling/Sample/ViewController.m
Migrate example projects to the recommended `-nodeBlock` data source method, so node containers will be able to prepare and display all of its cells concurrently
=> Migrate example projects to the recommended `-nodeBlock` data source method

examples/ASDKTube/Sample/AppDelegate.m, examples/ASDKTube/Sample/Controller/VideoFeedNodeController.m, examples/ASDKgram/Sample/Utilities.h, examples/CatDealsCollectionView/Sample/ItemViewModel.m, examples/HorizontalWithinVerticalScrolling/Sample/HorizontalScrollCellNode.mm, examples/HorizontalWithinVerticalScrolling/Sample/RandomCoreGraphicsNode.m, examples/SocialAppLayout-Inverted/Sample/ViewController.m, examples/VerticalWithinHorizontalScrolling/Sample/GradientTableNode.mm, examples/VerticalWithinHorizontalScrolling/Sample/RandomCoreGraphicsNode.h, examples/VerticalWithinHorizontalScrolling/Sample/RandomCoreGraphicsNode.m
Fix all project coding warnings in `examples` folder
=> Fix all project coding warnings in `examples` folder

Tests/ASBasicImageDownloaderTests.mm
Fix the following error in `ASBasicImageDownloaderTests` when building Tests:
```
testAsynchronouslyDownloadTheSameURLTwice, Asynchronous wait failed: Exceeded timeout of 30 seconds, with unfulfilled expectations: "First ASBasicImageDownloader completion handler should be called within 3 seconds", "Second ASBasicImageDownloader completion handler should be called within 3 seconds".
```
=> Fix ASBasicImageDownloaderTests

docs/_docs/development/cell-node-lifecycle.md, docs/_docs/development/collection-animations.md, docs/_docs/development/collection-asynchronous-updates.md, docs/_docs/development/how-to-debug.md, docs/_docs/development/structure.md, docs/_docs/development/threading.md, docs/_layouts/docs.html
Our pages are organized in 2 dirs: `/docs/` and `/development/`.
Within a dir, `prevPage` and `nextPage` are relative (to the dir) so its path should be appended to their href links (see [docs/_layouts/docs.html](https://github.com/TextureGroup/Texture/compare/master...nguyenhuy:HN-Fix-Prevnext?expand=1#diff-c7714274956193f5a3dd8e30f038591c)). The dir is available in the page's `permalink` var.
Some prevPage and nextPage point to a page in a different dir in which case they must not be relative. Instead they must include the other dir's path and thus their links won't be modified.
Also removed some pages that are no longer needed and fixed some `prevPage` and `nextPage` values.
I tested this diff locally and all links worked fine.
=> [Dev docs] Fix previous and next page links

Source/ASTextNode.h, Source/ASTextNode.mm, Source/ASTextNode2.h, Source/ASTextNode2.mm
After this [PR](https://github.com/TextureGroup/Texture/pull/1184), `ASTextNode` and `ASTextNode2` don't handle touches on additional attributed message if `passthroughNonlinkTouches` is YES. But sometimes we maybe want to handle these touches action, even if `passthroughNonlinkTouches` is YES.  
So I add the new property `alwaysHandleTapTruncationAction` to `ASTextNode` and `ASTextNode2`, when `alwaysHandleTapTruncationAction` is YES, `ASTextNode` and `ASTextNode2` always handle touches on additional attributed message.
=> Add new property alwaysHandleTapTruncationAction to ASTextNode2 and ASTextNode.

Source/ASImageNode+AnimatedImage.mm
We previously tried to optimize showing animated images (e.g. GIF) by calling
display link for updating the frame just when when we need the next frame, but
this resulted in some frames dropping when `frameInterval` wasn't respected like
you can find from this GIF:
https://i.pinimg.com/originals/58/9c/e8/589ce828d2ef0797da0e85b1c6d2f2b3.gif
Since the the display link fire method continues if we detect we're
at the same image index as before, let's just remove this optimization.
=> Stop setting `frameInterval` for animated image optimization

Source/ASVideoNode.h, Source/ASVideoPlayerNode.h
Update `periodicTimeObserverTimescale`'s comment default value to `10000`, according to the real value set in the implementation.
=> Fix a comment bug in `ASVideoNode` and `ASVideoPlayerNode`

Source/ASDisplayNode.mm
It appears that UIKit might be setting the delegate ivar directly which bypasses establishing the `_delegateFlags` ivar on `ASDisplayLayer`. This is critical for things like ASPagerNode, ASCollectionNode that depend on layer delegateFlags to forward bounds changes.
Radar filed: FB6956185
Resolves: #1595
=> Force `-[_ASDisplayLayer setDelegate:]` to evaluate delegateFlags in iOS 13

Source/Layout/ASYogaUtilities.mm
- Return CGFloat
- Proper check for YGUndefined
- Add YGUndefined default return value
=> Cleanup for cgFloatForYogaFloat

Source/ASTextNode2.mm, Source/TextKit/ASTextKitContext.mm, Tests/ASTextNode2Tests.mm, Tests/ASTextNodeTests.mm
Resolves crash with stack trace:
```
Fatal Exception: NSRangeException
NSRLEArray objectAtIndex:effectiveRange:: Out of bounds
0  CoreFoundation                 0x1eab6298c __exceptionPreprocess
1  libobjc.A.dylib                0x1e9d3b9f8 objc_exception_throw
2  CoreFoundation                 0x1eaa6cbc0 -[NSCache init]
3  Foundation                     0x1eb4e4a7c -[NSRLEArray objectAtIndex:effectiveRange:]
4  Foundation                     0x1eb4e4c34 -[NSConcreteAttributedString attribute:atIndex:effectiveRange:]
5  PinterestEnterprise            0x10419ecdc -[ASTextKitContext initWithAttributedString:tintColor:lineBreakMode:maximumNumberOfLines:exclusionPaths:constrainedSize:] + 68 (ASTextKitContext.mm:68)
6  PinterestEnterprise            0x1041a3c48 -[ASTextKitRenderer …
```
=> Avoid querying for NSAttributedString attributes on empty string

Source/ASDisplayNode.mm, Source/Details/_ASDisplayLayer.mm
We rely on the delegate setter to be called to set the flag. However, a recent change in iOS 13 (beta) causes the setter to not be called at all and thus we had to put up a workaround (https://github.com/TextureGroup/Texture/pull/1609). While the workaround works, the performance benefit that the flag provides doesn't warranty the extra complexity IMO. So I think we should just remove everything.
=> Remove _ASDisplayLayer's delegateDidChangeBounds flag

Source/ASDisplayNode.h, Source/Private/ASDisplayNode+UIViewBridge.mm
Quick follow up on https://github.com/TextureGroup/Texture/pull/1617:
- Need to assert thread affinity in the getter when the node is view-backed and loaded. This is because UIView properties can't be accessed off main thread.
- When the node is view-backed, we shouldn't ascend the node hierarchy. UIView should already ascend the view hierarchy and we currently don't support adding a view-backed node as a subnode of a layer-backed node (the other way around is fine).
- `_getFromViewOnly` and `_setToViewOnly` check if the node loaded and do the right thing. So by checking `layerBacked` first, we can use them simplify our getter and setter.
=> Minor changes to tint color support

.github/workflows/ci.yml
Block pull requests from forked repositories that aren't from, and aren't labeled by, a maintainer.
=> [GitHub CI] Add step to block PRs from forked repositories unless they have the right label

Source/ASExperimentalFeatures.mm, Source/ASImageNode.mm, Source/ASNetworkImageNode.mm, Source/Debug/AsyncDisplayKit+Debug.mm, Source/Private/TextExperiment/Utility/ASTextUtilities.h, Source/Private/_ASPendingState.mm
Minor code improvements, including: 
- Simplify code logic
- Keep using user-defined type
=> Minor code improvements

.github/workflows/ci.yml
In #1627 I introduced an approval step that is meant to block PRs from forked repos unless they're labeled as "CI approved" by a maintainer. Turned out it doesn't work. When a label is added, a pull_request event with "labeled" as its action is fired but GitHub CI didn't restart the workflow. My guess is it checked the PR's commit and branch and determined that nothing has changed. Here is what the doc says: "A workflow runs on a specific version of code in your repository, determined by the commit SHA and Git ref" ([Source](https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events)).
This diff removes the approval step so all PRs will be automatically built. Here are current [usage limits](https://help.github.com/en/articles/workflow-syntax-for-github-actions#usage- …
=> [GitHub CI] Remove build approval step

.github/workflows/danger.yml
Turned out that `@babel/plugin-transform-flow-strip-types` is needed for TypeScript/Bale transpilation with we don't need because we use JS. So instead of installing the module, we can. just disable transpilation by `DANGER_DISABLE_TRANSPILATION` environment variable to `true`.
Test plan: Tested manually [here](https://github.com/TextureGroup/Texture/commit/a4cfe347914c23aafe08603bf82372d4cb94136c/checks).
=> Update Danger workflow

Source/ASConfigurationInternal.mm, Source/ASRunLoopQueue.mm, Source/Details/ASCollectionViewLayoutController.mm, Source/Details/ASElementMap.mm, Source/Details/ASPageTable.mm, Source/Details/ASThread.h, Source/Details/ASWeakSet.mm, Source/Layout/ASLayoutElement.mm, Source/Layout/ASLayoutSpec.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm
Keep using `unowned` macro for code consistence, instead of using `__unsafe_unretained` directly.
=> Keep using `unowned` macro

Source/ASImageNode.mm
use lock to avoid crash when image might be changed during the trait collection change
=> use lock in asyncTraitCollectionDidChangeWithPreviousTraitCollection

Source/ASImageNode.mm
The rest of the ivars in in this object use the `_` prefix, so let's use it for all for consistency sake.
=> Use standard ivar _ prefix for userInterfaceStyle in ASImageNodeDrawParameters

Source/ASImageNode.mm
Then access the ivars directly so that another lock access is not required. Using this C++ macro ensures that any future early returns or the like will still unlock.
=> Use MutexLocker when ASImageNode traits change

Source/ASImageNode.mm
Missing with #1629. Other code accesses this ivar with a lock, so doing it here for consistency sake.
=> Use lock to access the image renderingMode when tint color changes

Source/ASImageNode.mm, Source/Private/ASImageNode+AnimatedImagePrivate.h
There is a potential dealloc race condition that can occur when attempting to perform work with image asset out of the main thread. Moving that work into the image node draw loop if necessary
=> Defer image asset regeneration to draw loop

Source/ASDisplayNode.h, Source/Details/UIView+ASConvenience.h, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASPendingState.mm, Tests/ASDisplayNodeTests.mm
Use `CAEdgeAntialiasingMask` instead of `unsigned int` in the codebase.
=> Use `CAEdgeAntialiasingMask` instead of `unsigned int`

Source/Private/_ASPendingState.mm, Tests/ASBridgedPropertiesTests.mm, Tests/ASDisplayNodeTests.mm
- If the tint color changes, be sure to call -setNeedsDisplay on the view.
- Explictly declare tintColor ivar and getter method.
- If the tintColor is the same as the existing one, early-exit.
- Use the ivar and not the property when setting the tintColor, just as is done for background color.
- Add tests that the tintColor will call -setNeedsDisplay
- Backfill tests to document/verify the tintColor behavior on a node.
=> Node TintColor Tweaks

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASImageNode.mm, Tests/ASImageNodeTests.m
When ASImageNodes changes tintColor or enters the hierarchy, ensure `-setNeedsDisplay` is called if the image is templated. Basically apply #1629 to the hierarchy code as well, and backfill unit tests for that change too. Add unit tests to ensure this behavior works.
=> ASImageNode tintColor improvements.

Source/ASTextNode2.mm
I was hitting a crash in ASTextNode2 (in an ASCellNode) while using `truncationAttributedText` and `additionalTruncationMessage`. It seemed to only happen on a tap event when `maximumNumberOfLines` was 0, and the text was long enough to run off screen requiring the user to scroll. The node rendered fine, but crashed as the user touched down to scroll. A quick null check before calling `CFRelease` was enough to fix it.
=> Fix CFRelease on null variable when using truncationAttributedText

Source/Details/Transactions/_ASAsyncTransaction.mm
[According to Apple](https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Initialization/Initialization.html#//apple_ref/doc/uid/TP40010810-CH6-SW3), the superclass (super) initializer need to be Invoked first.
=> Fix `_ASAsyncTransaction` initialization method

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/AsyncDisplayKit.h, Source/Details/ASGraphicsContext.h, Source/Details/ASGraphicsContext.mm, Source/Details/ASTraitCollection.h, Source/Details/ASTraitCollection.mm, Tests/ASCollectionViewTests.mm, Tests/ASGraphicsContextTests.mm
`ASGraphicsCreateImageWithOptions` uses global trait collection cause it runs in the background, thus  colors, etc. in `work` block might receive wrong trait collection (e.g. switching dark/light mode when app in the background).
`ASGraphicsCreateImageWithTraitCollectionAndOptions ` solves this problem by taking a trait collection as a parameter and running a drawing code inside of `[[UITraitCollection -performAsCurrentTraitCollection:]`
=> introduction of `ASGraphicsCreateImageWithTraitCollectionAndOptions`

Source/Private/ASLayoutTransition.mm
Using `emplace_back`, it avoids the move operation requires when using `push_back`.
=> Using `emplace_back` instead of `push_back` for efficiency

docs/_docs/layout2-quickstart.md
Quick fix for a broken link in `Layout-Quickstart` doc.
=> [Docs] Fix broken link in `Layout-Quickstart`

Source/ASDisplayNode.mm, Source/ASImageNode.mm, Source/ASMapNode.mm, Source/ASTextNode.mm, Source/Debug/AsyncDisplayKit+Debug.mm, Source/Details/ASGraphicsContext.h, Source/Details/ASGraphicsContext.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm
`ASGraphicsCreateImageWithTraitCollectionAndOptions` supersedes `ASGraphicsCreateImageWithOptions`, thus we deprecate it.
Reference https://github.com/TextureGroup/Texture/pull/1675
>UIImage (ASDKResizableRoundedRects) is untouched cause requires deprecation of other things
>Documentation wasn't created
>ASImageNode Extras remains untouched: needs further deprecation(?)
PS
this is the same as https://github.com/TextureGroup/Texture/pull/1676
=> deprecate ASGraphicsCreateImageWithOptions

Source/ASCollectionNode.h
There is an comment typo on `ASCollectionNode`'s `showsHorizontalScrollIndicator`.
`showsHorizontalScrollIndicator` is initialized to `YES` in the `ASCollectionNode`'s initializer.
It should be `YES` in `ASCollectionNode.h`
```objc
// ASCollectionNode.mm
- (instancetype)init
{
self = [super init];
if (self) {
_rangeMode = ASLayoutRangeModeUnspecified;
_tuningParameters = [ASAbstractLayoutController defaultTuningParameters];
_allowsSelection = YES;
_allowsMultipleSelection = NO;
_inverted = NO;
_contentInset = UIEdgeInsetsZero;
_contentOffset = CGPointZero;
_animatesContentOffset = NO;
_showsVerticalScrollIndicator = YES;
_showsHorizontalScrollIndicator = YES;
}
return self;
}
```
```diff
// ASCollectionNode.h
/**
* A Boolean value that controls whether the horizontal scroll indicator is …
```
=> Fix comment typo for `showsHorizontalScrollIndicator` in ASCollectionNode

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/Private/Layout/ASLayoutSpecUtilities.h, Tests/ASLayoutSpecUtilitiesTests.mm
1. Prefer using `reserve function` rather than `fill constructor` in `AS::map()` for **memory efficiency**
`fill constructor` **constructs** the vector with **n** elements and **initializes** each element with its default constructor, while `reserve function` just allocates memory, **0** element is need to be initialized. 
For example, after running ```result_type res(iterable.size());```, the `res` vector's size is equal to `iterable.size()`, while after running ```res.reserve(iterable.size());```, the `res` vector's size is 0.
Reference:
- http://www.cplusplus.com/reference/vector/vector/vector
- http://www.cplusplus.com/reference/vector/vector/reserve
- http://www.cplusplus.com/reference/iterator/back_inserter
2. Add tests for `ASLayoutSpecUtilities`
=> AS::Map function improvement

Source/ASMultiplexImageNode.mm, Source/ASNetworkImageNode.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.mm, Tests/ASMultiplexImageNodeTests.mm, Tests/ASNetworkImageNodeTests.mm
Best as I can tell, a source type of `ASNetworkImageSourceAsynchronousCache` was meant to indicate a disk cache hit and `ASNetworkImageSourceSynchronousCache` was meant to indicate a memory cache hit. This change adds reporting of memory cache hits to the async rendering path.
=> Fix for images retrieved from the memory cache being reported as disk cache hits.

Source/ASDisplayNode+Layout.mm
Rather than defining `layoutSizeDifferentFromBounds` as a macro, a BOOL can do the job.
=> Change `layoutSizeDifferentFromBounds` macro to a BOOL

docs/_docs/automatic-layout-examples-2.md
Update to use `ASCornerLayoutSpec` for `Photo with Outset Icon Overlay`.
=> [Docs] Update to use `ASCornerLayoutSpec` for `Photo with Outset Icon Overlay`

Source/Private/TextExperiment/String/ASTextRunDelegate.h
For attributes whose type is an `immutable` value class that conforms to the `NSCopying` protocol, it almost always should specify `copy` in the `property` declaration.
=> Add `copy` sematic to `userInfo` property in `ASTextRunDelegate`

Source/ASImageNode.mm, Source/ASTextNode.mm, Source/ASTextNode2.mm
https://github.com/TextureGroup/Texture/issues/#1731
Fix the dead lock issue caused by holding the imageNode's instance lock while walking up the view hierarchy to get the superNode's `tintColor`. If another thread is walking down the tree while holding the supernode's instance lock and trying to acquire the imageNode's lock, then we run into this dead lock.
=> Fix tint color dead lock #1731

docs/_docs/layout2-layoutspec-types.md, docs/_docs/layout2-quickstart.md
Minor fixes in the `Layout` docs.
=> [Docs] minor fixes in `Layout`

Source/Details/ASRecursiveUnfairLock.h, Source/Details/ASRecursiveUnfairLock.mm
- Use relaxed memory since we don't need acquire/release. This'll make it faster.
- Add a couple assertions and organize the code better.
- In contested case, just lock instead of tryLock-fail-lock.
- In recursive case, do not tryLock. Just notice it's recursive and be done.
- In uncontested case, just lock instead of tryLock.
We never experimented with the current (HEAD) version of unfair lock, but this particular version showed benefits across the board and we launched it. Since CATransaction and @synchronized have both moved to unfair lock, there's a clear set of prior art to (try to) use unfair lock. @bolsinga cc #1741
=> Improve recursive unfair lock

Source/Private/ASCollectionLayout.mm
The `_measureElementsInRect()` function in `ASCollectionLayout.mm` was performing a `[elementForItemAtIndexPath:]` on the index path for every attribute. Some of those attributes might be supplementary views, but this distinction was being ignored. The fix will check the `representedElementKind` to see if the item is a supplementary view and if it is, `[supplementaryElementOfKind:atIndexPath:]` will be called instead.
=> Fix element lookup for supplementary attributes.

Texture.podspec
Ran ASKGram without any issues with IGListKit v4.0. #1747
=> Bump up IGListKit version

Source/Details/ASMainSerialQueue.mm
In the original implementation, when removing the first element of an array, we use the `NSMutableArray`'s `removeObjectAtIndex` method, which means to remove a single item, every object in the array is shifted down one, it is `O(n)` time complexity. 
The PR proposes to use `queue`, which is `O(1)` when removing the first element, it is more efficient.
=> Use `queue` in `ASMainSerialQueue`

Source/Details/Transactions/_ASAsyncTransaction.mm
Simplify push_back `GroupNotify` to `_notifyList` list in `_ASAsyncTransaction`.
=> Simplify push_back `GroupNotify`

build.sh
We now run our CI on GitHub Actions so this is no longer used.
=> Remove references to xcpretty-travis-formatter

Source/ASViewController.h, Source/ASViewController.mm, examples/CustomCollectionView-Swift/Sample/ViewController.swift, examples/LayoutSpecExamples-Swift/Sample/OverviewViewController.swift, examples/Swift/Sample/ViewController.swift
[Take 2 of #1740 because I'm an idiot]
Per Slack discussion with @nguyenhuy.
If you want to use `ASViewController` throughout your app as a generalized `UIViewController` stand in (as [the docs mention](http://texturegroup.org/docs/containers-asviewcontroller.html)) it's tricky (at least in Swift) when you want to take a non-node based normal `UIViewController` and make it inherit from `ASViewController` (again to perhaps have a consistent root subclass) because there's only one designated initializer in `ASViewController`, `init(node:)` which does not accept nil values despite the docs indicating that should be okay.
Currently the only course of action is to pass in a dummy node (e.g.: `ASViewController(node: ASDisplayNode())`). Other courses of action include unmarking `init(node:)` as …
=> Add empty ASViewController initializer to facilitate subclassing

Source/Details/ASTraitCollection.h, Source/Details/ASTraitCollection.mm
- UIUserInterfaceLevel was added to ASTraitCollection in #1568. However, it's unavailable on tvOS and thus broke our podspec linting CI job. Fix by only include it if the build target is iOS.
=> Only include UIUserInterfaceLevel in iOS target

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/AsyncDisplayKit.h, Source/Base/ASAvailability.h, Source/Layout/ASLayout+IGListDiffKit.h, Source/Layout/ASLayout+IGListDiffKit.mm, Source/Private/ASLayoutTransition.mm, Texture.podspec
- In IGListDiff is no longer part of IGListKit as of 4.0. It has its own podspec now. After bumping our IGListKit dependency of our subspec, we got an "Undefined symbol: _IGListDiff" error which breaks our podspec linting CI job (as well as some of our clients as reported in #1749).
- To fix it, we can either remove the IGListDiff dependency since it's used once in the entire project, or link to IGListDiffKit pod. I opt for the latter because I imagine many IGListKit users would have IGListDiffKit anyway so we can still take advantage of it (it's faster than our built in diffing algorithm). Plus, it's not a big dependency.
=> Link to IGListDiffKit in our IGListKit subspec

Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/TextKit/ASTextKitContext.mm, Tests/ASConfigurationTests.mm
The ASExperimentalRemoveTextKitInitialisingLock experimental code is unused; pruning.
=> Pruning ASExperimentalRemoveTextKitInitialisingLock code. 

Source/ASDisplayNode.mm
Background:
In some cases `asyncTraitCollectionDidChangeWithPreviousTraitCollection` might be called on loaded node in background. In this case we access `layer` from background thread. It locks main thread and may lead to dead lock.
Fixes:
1. Ensure that `asyncTraitCollectionDidChangeWithPreviousTraitCollection `  accesses `layer` from the main thread.
2. Resolve background color using current trait collection.
3. Simplify locking.
e.g.
```
Thread 0:
0	libsystem_kernel.dylib	
___psynch_mutexwait
1	libsystem_pthread.dylib	
__pthread_mutex_firstfit_lock_wait
2	libsystem_pthread.dylib	
__pthread_mutex_firstfit_lock_slow
3	libc++.1.dylib	
std::__1::recursive_mutex::lock()
4	Pinterest	
ASThread.h:177:22
std::__1::lock_guard<AS::Mutex>::lock_guard(AS::Mutex&)
5	Pinterest …
```
=> fix calling CALayer out of the main thread

Source/Details/ASTraitCollection.mm
As mentioned in the [Slack channel](https://asyncdisplaykit.slack.com/archives/C0V63R86T/p1578575412003700). 
I receive a crash during device rotation of certain screens. It happens when logging out new traits inside the `NSStringFromASPrimitiveTraitCollection` method during the  `ASViewController.mm#propagateNewTraitCollection` calls. 
The controller in question is an old UIStoryboard, I'm not sure of the reason for the nil `preferredContentSizeCategory` being nil, but given it's just a log, it shouldn't be crashing the app.
This PR simply adds a null check to the String conversion method, I'm not sure if someone can shed more light on whether or not this is appropriate, or the root cause might be cause for concern? @Adlai-Holler @nguyenhuy
=> Prevent crashing during non critical logging at rotation

Source/ASDisplayNode.mm
We should resolve color using node's trait collection, but Texture changes it from many places, so node may receive the wrong one.
This is a quick fix. We should revise trait collection propagation mechanism.
=> resolve background color using system trait collection

Source/ASTableViewProtocols.h
- I added new delegate methods to `ASCommonTableViewDelegate`:
`tableView(_:leadingSwipeActionsConfigurationForRowAt:)`
`tableView(_:trailingSwipeActionsConfigurationForRowAt:)`
- And marked old method as deprecated since iOS 13.
=> Adds new delegate methods to ASCommonTableViewDelegate for swipes

Source/ASTableViewProtocols.h
=> Context menu iOS 13 API

Source/ASTableViewProtocols.h
These were recently introduced in #1795 but were missing `nullable`
annotations on their return types.
Also, reorder the declarations to match `UITableView.h`.
=> Add `nullable` to new ASCommonTableViewDelegate methods

Source/Details/_ASDisplayViewAccessiblity.mm, Tests/ASDisplayViewAccessibilityTests.mm, Tests/ASViewControllerTests.mm
Since `NSObject` conforms to the informal accessibility protocol, `ASDisplayNode` has an inherited property for `accessibilityElements`. However, setting this property has no effect since `ASDisplayNode` overrides the `accessibilityElements` getter. Added a small change to the getter to check if the `accessibilityElements` property on `ASDisplayNode` has been explicitly set, and if so return that.
I also added a comment around  `_ASDisplayView`’s `setAccessibilityElements:` method to clear up some (of my own) confusion.
=> [ASDisplayNode] Allow explicit setting of accessibilityElements

Podfile.lock, Schemas/configuration.json, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Details/_ASDisplayViewAccessiblity.h, Source/Details/_ASDisplayViewAccessiblity.mm, Tests/ASConfigurationTests.mm, Tests/ASDisplayViewAccessibilityTests.mm, Tests/ASScrollNodeTests.mm
This diff includes a few improvements for accessibility in Texture.
* When determining a node’s accessibility elements, ignore any elements that are hidden, transparent, or out of the window. This matches UIKit’s behavior.
* When sorting the accessible elements and their origins are equal, give precedence to elements with shorter accessibility frames, followed by elements with narrower widths.
* Allow the ability to customize the comparator block that sorts the accessibility elements
* Create an experiment to stop caching accessibilityElements in `_ASDisplayView`. If we cache elements, we will require users to clear the cache (by calling `setAccessibilityElements` to get the side effect of clearing the cache) when nodes change their hidden state or opacity. This seems like a lot to …
=> [ASDisplayViewAccessibility] A few accessibility improvements

Tests/ASCollectionViewTests.mm
All of the work being done in this tearDown is also being done in -[ASTest tearDown].
So we might as well get rid of the redundant code.
=> Removes unnecessary `-tearDown` code.

Source/Details/ASGraphicsContext.h, Source/Details/ASGraphicsContext.mm, Tests/ASGraphicsContextTests.mm
this PR is an adoption of https://github.com/TextureGroup/Texture/pull/1696
followups: replace `ASGraphicsCreateImageWithTraitCollectionAndOptions` with `ASGraphicsCreateImage`. Deprecate `ASGraphicsCreateImageWithTraitCollectionAndOptions `.
=> support cancelation in ASGraphicsCreateImage

build.sh
It is obscuring errors that are currently occurring in CI for Texture. I do not think logs should be truncated for builds in order to make diagnosis of remote build errors more productive.
=> Do not use xcpretty in builds so that CI errors are logged.

.github/workflows/ci-master-only.yml, .github/workflows/ci-pull-requests-only.yml, .github/workflows/ci.yml, .github/workflows/danger.yml, Source/Details/ASGraphicsContext.h, Source/Details/ASGraphicsContext.mm, Source/Details/_ASDisplayViewAccessiblity.mm, Source/Private/ASIGListAdapterBasedDataSource.mm, Tests/ASCollectionViewTests.mm, Tests/ASDisplayViewAccessibilityTests.mm, Tests/ASGraphicsContextTests.mm, Texture.podspec, build.sh
Previously I put up a diff to exclude accessibility elements that were outside of the current window rect. However, I didn’t take the case of scrollViews (including table and collection views) into consideration. By ignoring cells outside of the window, the scroll view would not advance to additional elements in the scrollView but off screen.
I did some side-by-side testing with UIKit and it appears that no elements are excluded that are in a scroll view, even if the element’s rect is outside of the scroll view’s visible rect. In order to match this behavior, I added a recursive superview check to see if an element that is off screen has a scrollView as a parent. If so, we do not exclude it:
```    
if (!CGRectIntersectsRect(view.window.frame, nodeInWindowCoords) && …
```
=> [Accessibility] Do not exclude elements outside the window’s rect that are subviews of UIScrollView

AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit.xcscheme, Podfile, Podfile.lock, Tests/ASCollectionViewTests.mm
- The issues preventing updates in #1038 are not explained.
- In `ASCollectionViewTests` do not mock every `collectionViewLayout`, only do it for the test that requires it. In addition, call `-stopMocking` when done. OCMock 3.6 found this code using stuff after it should not have been.
- 5c42bb4e2f2424f09097a461ffbaa53cc3e21695 says the layer tests are not typically run, but they are in the project. That diff refers to ASUIViewTests being skipped, but those tests do not exist. So I've just disabled them in this diff. It is not clear how they ever worked.
=> Update to OCMock 3.6

Podfile, Podfile.lock, Tests/ASTableViewTests.mm
- I tried to make these tests work with OCMock, but that only ever saw 1 call.
- All these do is count `-reloadData` calls. I'm not sure why so many other methods were recorded.
- Why we are doing this is the external library targets iOS 5 and is flagged as a warning in builds.
=> Use ASReplaceMethodWithBlock instead of swizzling with a library

docs/_docs/uicollectionviewinterop.md
There is an issue with interop in Swift - you can't return nil instead of node or node block. This would help people reading the documentation overcome the issue.
Confusion example:
https://stackoverflow.com/questions/47676341/texture-ascollectiondatasourceinterop-swift/61993513#61993513
=> Update Swift collection view interop example

Source/ASDisplayNode+Layout.mm, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode.mm, Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Tests/ASConfigurationTests.mm, Tests/ASDisplayNodeSnapshotTests.mm, Tests/ASImageNodeSnapshotTests.mm
- PINS shipped this experiment in 08/2019 with D444057.
=> Ship ASExperimentalTraitCollectionDidChangeWithPreviousCollection

Source/Details/_ASDisplayViewAccessiblity.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Tests/ASDisplayViewAccessibilityTests.mm
A PR to add support for `accessibilityViewIsModal` in `CollectAccessibilityElements`.
If in a list of subnodes more than 1 subnode has `accessibilityViewIsModal` marked as `YES`, then the node with the highest index in `subnodes` will be the one that is considered modal. This behavior matches UIKit.
If the value of `accessibilityViewIsModal` changes, we need to clear all the cached `accessibilityElements` from that view up. I added this in ASDisplayNode’s `setAccessibilityViewIsModal` method. Note that if we ship `ASExperimentalDoNotCacheAccessibilityElements` then we can remove the invalidation step.
Finally, I changed all the tests to ask the view for accessibilityElements, not the node. This is a better representation of what will really happen when UIKit asks a node’s view for its …
=> [ASDisplayNode] Implement accessibilityViewIsModal

Source/ASCollectionViewProtocols.h
Add iOS13 UIContextMenu api to ASCommonCollectionDelegate
=> Add iOS13 UIContextMenu api to ASCommonCollectionDelegate

Source/ASDisplayNode.h
This is a small fix to the documentation for ASCornerRoundingTypeClipping
=> Fix documentation for ASCornerRoundingTypeClipping

Source/Details/_ASDisplayViewAccessiblity.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Tests/ASDisplayViewAccessibilityTests.mm
Most of this code comes from an old PR that @fruitcoder put up https://github.com/TextureGroup/Texture/pull/795 2 years ago.
When creating our array of accessibilityElements, we need to respect the value of `accessibilityElementsHidden`. If the value of this property changes, we need to invalidate the cached accessibility elements (unless we are in the experiment that doesn’t cache `accessibilityElements`).
I created a simple test app and made sure this matched UIKit’s implementation. I also added a test case that changes the value of `accessibilityElementsHidden` and makes sure the proper accessibilityElements are returned.
=> [ASDisplayNode] Implement accessibilityElementsHidden

Source/ASNetworkImageNode.mm, Tests/ASNetworkImageNodeTests.mm
If you have a ASNetworkImageNode with animatedImage
Then you call [ImageNode setURL:someLink resetToDefault:true]
Node will still always display Old animatedImage, the new static image will never be display
Related issue https://github.com/TextureGroup/Texture/issues/1815
=> -[ASNetworkImageNode setURL:resetToDefault:] forget to reset animatedImage

ThreeMigrationGuide.md
This PR adds `ASImageCacherCompletion` breaking API change to the Texture 3.0 Migration Guide.
This is the only point of contact that I had modify in order to make my project compile. It's not clear whether there're more changes or not, I can't easily tell without looking at the tens of PRs that got merged since 2.8.0 🙈 
Texture 3.0 is now under QA process at Tellus and I'll keep this Migration Guide updated with any other internal details we find.
Thanks once again for pushing this release to the finish line :) it's been a long time! 😄 
Cheers!
=> Improve ThreeMigrationGuide.md

Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Details/_ASDisplayViewAccessiblity.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Tests/ASConfigurationTests.mm
We did not notice any effect on performance of the Pinterest app by not caching `accessibilityElements` in `_ASDisplayView`. By not caching the elements, we can be sure that the elements will be correct even when nodes change visibility state. There will be a performance impact when voice over is enabled, but providing the correct elements for the current state of a view is more important than performance in this case.
https://github.com/TextureGroup/Texture/issues/1853
=> [Accessibility] Ship ASExperimentalDoNotCacheAccessibilityElements

Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/Details/ASDataController.mm, Tests/ASConfigurationTests.mm
- Under this experiment, ASDataController will allocate and layout all nodes on the main thread. This helps to avoid deadlocks that would otherwise occur if some of the node allocations or layouts caused ASDataController's background queue to block on main thread. As a bonus, this experiment also helps to measure how much performance wins we get from doing the work off main.
=> Add an experiment that makes ASDataController to do everything on main thread

Source/Details/ASDataController.mm
Follow up on #1911: it's not enough to execute step 3 on the main thread because `-_allocateNodesFromElements:` uses `ASDispatchApply` to offload the work to other threads. So this diff adds a flag to tell that method to do everything serially on the calling thread.
=> More on ASDataController's main-thread-only mode

Source/Private/ASDispatch.h, Source/Private/ASDispatch.mm
=> Ship ASExperimentalDispatchApply

Source/ASTableView.mm
Currently there's no way to make a ASCellNode node non accessible, this change solves the problem for cases when you only want the cell node to be a decorative view like a custom separator between cells
=> All ASCellNode nodes to be non accessible if needed

Podfile, Podfile.lock
I updated the Podfile slightly to allow CocoaPods to pull from the [CDN](https://blog.cocoapods.org/CocoaPods-1.7.2/), which is way faster than the old trunk repo. This doesn't impact clients of Texture, but makes developing a lot easier.
=> Podfile improvements

Source/ASDisplayNodeExtras.mm
Please allow me to try to convince you that this mutation wasn't used, per the static analyzer:
The original code was:
```objc
ASInterfaceState interfaceState = displayNode.pendingInterfaceState;
return (window == nil ? (interfaceState &= (~ASInterfaceStateVisible)) : interfaceState);
```
And then the local `interfaceState` variable is never used again after that line.
First, we expand out the ternary to get this:
```objc
ASInterfaceState interfaceState = displayNode.pendingInterfaceState;
if (window == nil) {
return (interfaceState &= (~ASInterfaceStateVisible));
} else {
return interfaceState;
}
```
Now, zooming in on just the line in the "true" branch":
```objc
return (interfaceState &= (~ASInterfaceStateVisible));
```
Let's expand this by replacing `a &= b` with its longer form: `a = …
=> Fix mutation of variable that is never read

README.md, docs/slack.md
I wanted to join the slack group, but the page seems to be broken. The iframe isn't loading because the invite url is using http, but the service seems to be available over https as well.
=> use https for slack link

docs/_docs/inversion.md
This swift code example is missing the "hidden" class, which all others have, which causes the objc and swift code to show up simultaneously on initial page load.
=> fix missing hidden class

examples/ASCollectionView/Podfile.lock, examples/ASCollectionView/Sample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples/ASViewController/Sample.xcodeproj/project.xcworkspace/contents.xcworkspacedata, examples/ASViewController/Sample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples/CustomCollectionView-Swift/Podfile.lock, examples/CustomCollectionView-Swift/Sample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples/HorizontalWithinVerticalScrolling/Sample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples/HorizontalWithinVerticalScrolling/Sample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples/VerticalWithinHorizontalScrolling/Sample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples_extra/ASDKgram-Swift/ASDKgram-Swift.xcodeproj/project.pbxproj, examples_extra/ASDKgram-Swift/ASDKgram-Swift/AppDelegate.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoFeedTableNodeController.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoFeedTableViewController.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoModel.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoTableViewCell.swift, examples_extra/ASDKgram-Swift/Podfile.lock, examples_extra/EditableText/Sample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
This fixes: Fix: `SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0`. when running on Xcode 12+. 
Minor changes have been added as follows: - 
1. Changed the version number on ASDKGram sample Build Settings from Swift 3 to Swift 5.3.
2. Renamed a couple of method calls on ASDKGram sample to satisfy new Swift 5.3 API.
=> Update asdkGram swift sample to swift version 5.3

Tests/ASTextNodeTests.mm
The ASTextNodeTests currently depend on executing in a specific order as some tests enable the `ASExperimentalTextNode` experimental feature. This is set in a global config, so running any tests which require this experimental feature to not be enabled after a test which enables it will cause that test to fail. This PR resets the experimental features to `kNilOptions` in the per-test setup, removing this ordering dependency.
=> Fix order-dependent ASTextNodeTests

Source/ASMultiplexImageNode.h, Source/ASMultiplexImageNode.mm, Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm, Source/Details/ASBasicImageDownloader.h, Source/Details/ASBasicImageDownloader.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.mm, Tests/ASBasicImageDownloaderTests.mm, Tests/ASMultiplexImageNodeTests.mm, Tests/ASNetworkImageNodeTests.mm, examples_extra/Multiplex/Sample/ScreenNode.m
At the moment the ASBasicImageDownloader does not automatically retry image downloads if the remote
host is unreachable. On the contrary the ASPINRemoteImageDownloader automatically retries. Retrying is
something that ultimately clients need to be able to control, for example to fail fast to an alternative image
rather than keep retrying for more than one minute while not displaying any image. This change exposes
a new option in the ASImageDownloaderProtocol to retry image downloads. It also uses this new option
in both ASNetworkImageNode and also ASMultiplexImageNode, setting it to YES to preserve the current
behaviour.
=> Exposes a new option in ASImageDownloaderProtocol to retry image downloads

Source/ASTextNode2.mm, Source/TextExperiment/Component/ASTextLayout.h, Source/TextExperiment/Component/ASTextLayout.mm
Implements `pointSizeScaleFactors` in ASTextNode2. If you provide and array of `pointSizeScaleFactors` and set a `maximumNumberOfLines` > 0, text layout will check if your text fit in the max number of lines. If not, it will scale your text by the scale factors in `pointSizeScaleFactors` until it either finds the first scale that allows the text to fit, or it runs out of scale factors.
Pro tip: view the diff with the ignore whitespace flag `?w=1` to make it look less scary (most of the changes in ASTextLayout.mm are just moving code into a do/while loop): 
https://github.com/TextureGroup/Texture/pull/1966/files?w=1
=> [ASTextNode2] Add support for pointSizeScaleFactors

Texture.podspec
There were methods like `as_setTextStrikethrough:range:` that ASTN2 uses to implement strikethrough (`NSStrikethroughStyleAttributeName` doesn’t work) that were not public because the `Utility` folder of `TextExperiment` was not exported in the pod.
Make all *.h files in `TextExperiment` part of `public_header_files`
=> [ASTextNode2] Expose all of ASTextNode2 as public files in via the podspec

.github/workflows/ci.yml, Source/TextExperiment/Component/ASTextLayout.mm, Tests/ASTextNode2Tests.mm
If we need to scale text in order to fit in our size, don’t forget to also scale the truncation token!
(disabled carthage so the builds will pass)
=> [ASTextNode2] Scale the truncation token via pointScaleFactors if needed

Source/TextExperiment/Component/ASTextLayout.mm, Tests/ASTextNode2Tests.mm
ASTextNode2 renders centered text a little strangely. If we have a small bit of text in a container size larger than the text, ASTN2 will use the entire container width to center the text but the text node's frame itself will not be the entire container size. For example, here is what ASTN2 looks like when centering text across the width of the phone:
While the text is centered across the phone's width, the text is not centered in the text node itself. 
This fix will align the text node's frame with the container size that computes the offset of the centered text, like this:
=> [ASTextNode2] Fix centered text shorter than container size

Source/ASTableView.mm, Tests/ASTableViewTests.mm
A previous commit
(https://github.com/TextureGroup/Texture/commit/8f7444e0ece61d6ab12ecceb590be26d8d7cc99d)
aimed to fix a preloading bug for ASCollectionView. This commit expands this
fix to ASTableView as the bug occurs there too.
Previous commit message for context:
This experiment makes sure a ASCollectionView's `rangeController` updates when
a changeset WITH updates is applied. Currently it is possible for nodes
inserted into the preload range to not get preloaded when performing a batch
update.
For example, suppose a collection node has:
- Tuning parameters with a preload range of 1 screenful for the given range
mode.
- Nodes A and B where A is visible and B is off screen.
Currently if node B is deleted and a new node C is inserted in its place, node
C will not get preloaded until …
=> Expand ASExperimentalRangeUpdateOnChangesetUpdate to ASTableView

Source/ASCellNode.mm, Source/ASCollectionNode.mm, Source/ASPagerNode.mm, Source/Debug/AsyncDisplayKit+Debug.mm, Source/Details/ASPINRemoteImageDownloader.mm, Source/Details/Transactions/_ASAsyncTransaction.mm, Source/Layout/ASCenterLayoutSpec.mm, Source/Layout/ASInsetLayoutSpec.mm, Source/Layout/ASRatioLayoutSpec.mm, Source/Private/ASCollectionViewFlowLayoutInspector.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/TextKit/ASTextKitFontSizeAdjuster.mm, Source/TextKit/ASTextKitRenderer.mm, docs/_docs/automatic-subnode-mgmt.md, docs/_docs/multiplex-image-node.md, examples/ASCollectionView/Sample/ViewController.m, examples/ASDKTube/Sample/ViewController.m, examples/ASDKgram/Sample/PhotoCellNode.m, examples/ASDKgram/Sample/PhotoTableViewCell.m, examples/ASDKgram/Sample/UserModel.m, examples/VerticalWithinHorizontalScrolling/Sample/ViewController.m, examples/Videos/Sample/ASVideoNode.m, examples/Videos/Sample/ViewController.m, examples_extra/CollectionViewWithViewControllerCells/Sample/ImageViewController.m
Having a semi-colon between a method parameters list and a method
body is not not correct and is usually caused by a copy and paste
error while creating the method definition from its declaration.
Fixes the following compilation warnings when building with
-Wsemicolon-before-method-body (which is part of -Wextra):
ASPINRemoteImageDownloader.mm:230:85: error: semicolon before method body is ignored [-Werror,-Wsemicolon-before-method-body]
- (id <ASImageContainerProtocol>)synchronouslyFetchedCachedImageWithURL:(NSURL *)URL;
^
ASPINRemoteImageDownloader.mm:275:76: error: semicolon before method body is ignored [-Werror,-Wsemicolon-before-method-body]
completion:(ASImageDownloaderCompletion)completion;
^
2 errors generated.
Fixes applied to both code, examples and samples in documentation.
=> Remove trailing semicolons between method parameters and body

Source/ASTextNode2.mm
`rangeOut` is a nullable parameter, but we are treating it as though it is always not null. Make sure it is not null before dereferencing it.
=> [ASTextNode2] Check that rangeOut is non-nil before dereferencing

Source/ASDisplayNode+LayoutSpec.mm, Source/ASDisplayNode.mm, Source/Private/ASBatchFetching.h, Source/Private/ASBatchFetching.mm, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/ASDisplayNodeInternal.h, Tests/ASBatchFetchingTests.mm
This is largely a slight update for https://github.com/TextureGroup/Texture/pull/1805. If RTL is enabled, `calculateLayoutLayoutSpec:` will flip the origin of all sublayouts.
The new part of the diff is that ASBatchFetching now supports proper fetching on RTL horizontal scrollViews.
=> [Layout] Add RTL support to LayoutSpecs

Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Private/ASBatchFetching.h, Source/Private/ASBatchFetching.mm, Tests/ASBatchFetchingTests.mm
`UICollectionViewLayout` has a property called `flipsHorizontallyInOppositeLayoutDirection`. If this is set to `YES` then a RTL collectionView’s contentOffset behaves like it does in LTR. In other words, the first item is at contentOffset 0. In this case, the existing logic for `ASDisplayShouldFetchBatchForScrollView` works in RTL.
If you don’t override `flipsHorizontallyInOppositeLayoutDirection` to be `YES`, then it means that in RTL languages the first item in your collectionView will actually be at x offset `collectionView.contentSize.width - collectionView.frame.size.width`. As you scroll to the right, the content offset will decrease until you reach the end of the data at a content offset of 0,0. In this case, `ASDisplayShouldFetchBatchForScrollView` needs to know that you are in …
=> [RTL/Batching] Make ASDisplayShouldFetchBatchForScrollView aware of flipped CV layouts

Source/ASCollectionView.mm
`flipsHorizontallyInOppositeLayoutDirection` is available in iOS11 and greater. Texture still supports iOS9 so we need to make sure not to call this it in those cases.
Thanks @foxware00 for the bug report! https://github.com/TextureGroup/Texture/issues/2001
=> [RTL] Guard access of flipsHorizontallyInOppositeLayoutDirection for iOS >= 11

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASDKNavigationController.h, Source/ASDKNavigationController.mm, Source/ASVisibilityProtocols.h, Source/AsyncDisplayKit.h, Tests/ASDKNavigationControllerTests.mm
As of iOS15 the AuthenticationServices framework has a class named `ASNavigationController`. We need to rename our `ASNavigationController` to protect against undefined behavior.
Note: THIS IS A BREAKING CHANGE! Any uses of `ASNavigationController` will need to be renamed to `ASDKNavigationController`. We will release 3.1.0 because of this breaking change.
Another Note: This change was based on this PR https://github.com/TextureGroup/Texture/pull/2014. We were slow in merging it and the author has not replied, so I'm making a new one to get this landed.
=> Rename ASNavigationController to ASDKNavigationController to fix name collision

Texture.podspec, ThreeMigrationGuide.md
With the breaking change of renaming ASNavigationController to ASDKNavigationController, we have released a new version of Texture. Please see `ThreeMigrationGuide.md` for how to handle the breaking changes in 3.1.0.
=> [3.1.0] Create new version of Texture

Texture.podspec
- The framework isn't available on tvOS. This causes CocoaPods linting to fail which prevented me from pushing the new release out.
- One way to fix this is to have a different `default_subspecs` for tvOS that doesn't have AssetsLibrary subspec, but per-platform `default_subspecs` doesn't seem to be supported by CocoaPods. So I updated the subspec itself to only depend on the framework for iOS. This means the subspec is empty/useless for tvOS (and other platforms FWIW).
- Tested with `pod spec lint Texture.podspec`.
- Fixes #1992 and part of #1549. Also unblocks 3.1.0 release.
- For the long term, we can remove the subspec entirely when iOS 9 is deprecated (#1828).
=> Remove AssetsLibrary dependency for tvOS

.github/workflows/ci-master-only.yml, .github/workflows/ci-pull-requests-only.yml, .github/workflows/ci.yml, build.sh
It looks like github updated so that `macos-latest` is now macos-11. It can't find Xcode_11_5. Let's try to set the runs-on version explicitly and see if some magic happens.
also allow warnings for podlint because that started failing too
=> Try to fix the CI

Source/Private/ASInternalHelpers.h, Source/Private/ASInternalHelpers.mm
In PR 2032 we added alloc/dealloc texture initialization methods for the case where texture is automatically initializing. However, in doing so we have removed the `ASInitializeFrameworkMainThread` method that clients may already be using.
This PR brings back the `ASInitializeFrameworkMainThread` to live side by side with `ASInitializeFrameworkMainThreadOnConstructor` and `ASInitializeFrameworkMainThreadOnDestructor`. This should keep the old functionality in place for any client using `ASInitializeFrameworkMainThread` directly.
=> Bring back ASInitializeFrameworkMainThread so we don't break the API

Source/Details/ASPINRemoteImageDownloader.mm
As discussed on our slack [thread](https://asyncdisplaykit.slack.com/archives/C0V63R86T/p1622253713035200)  since PINCache have already been optimized we no longer need to trade default size limit, thus I have simply increased the default disk cache limit from the original 20 MB to 50MB to support larger objects in the cache. 
NB: History to why the limit was set to 20MB can be found [here](https://github.com/TextureGroup/Texture/pull/595)
Thanks :)
=> Increase default diskCache byte limit from 20 to 50MB(PINCache default)

Source/TextExperiment/Component/ASTextInput.h
UITextWritingDirection was deprecated in iOS 13 and NSWritingDirection was introduced in iOS 6
=> Switch UITextWritingDirection to NSWritingDirection

Source/ASExperimentalFeatures.h, Source/ASExperimentalFeatures.mm, Source/ASTextNode.mm
While NSCache is thread safe, that alone does not make `rendererForAttributes` thread safe. This experiment will add a lock to `rendererForAttributes` to see how that affects performance/stability. As second experiment will forego the cache altogether to validate that we are getting some value out of having a renderer cache.
=> [ASTextKitRenderer] Adding locking when accessing the text renderer cache

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASCellNode.h, Source/ASCollectionView.mm, Source/ASTableView.mm, Tests/ASCellVisibilityScrollEventTests.m
We have `ASCellNodeVisibilityEvent` events that roughly correlate to the scrollViewDid… delegate methods in UIScrollView. With the current events we get a callback when a user stops dragging a cell, but if the cell decelerates we do not get an event when it comes to a rest. I’ve added  `ASCellNodeVisibilityEventDidStopScrolling` to have both `ASTableView` and `ASCollectionView` send this event to the cells in `_cellsForVisibilityUpdates` in `- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView`.
I created unit tests to ensure that the proper events are being called for the proper scroll delegate methods.
=> [ASCellNodeVisibilityEvent] Add a new event when scrolling stops

Source/Details/_ASDisplayLayer.mm, Source/Layout/ASDimension.h, Tests/ASDisplayLayerTests.mm
There is built in protection around setting invalid bounds for `_ASDisplayLayer`. Let’s extend this to also include protecting against setting an invalid position and an invalid transform.
=> [_ASDisplayLayer] Add protection around setting a layer’s position and transform

Source/ASCellNode.h, Source/ASCollectionNode+Beta.h, Source/ASCollectionNode.h, Source/ASCollectionView.h, Source/ASDisplayNode+Convenience.h, Source/ASDisplayNode+InterfaceState.h, Source/ASDisplayNode+Subclasses.h, Source/ASDisplayNode.h, Source/ASEditableTextNode.h, Source/ASImageNode.h, Source/ASMapNode.h, Source/ASNetworkImageNode.h, Source/ASPagerNode.h, Source/ASTableNode.h, Source/UIResponder+AsyncDisplayKit.h
Initial attempt to mark all methods that are guaranteed to run on main as `NS_SWIFT_UI_ACTOR`.
=> Add NS_SWIFT_UI_ACTOR to methods always called on main

Source/ASDisplayNode.mm, Tests/ASDisplayNodeTests.mm
If a node is already a subnode to a supernode, Inserting it again can lead to a crash.
Here is a simple repro of the crash:
```
ASDisplayNode *subnode = [[ASDisplayNode alloc] init];
ASDisplayNode *supernode = [[ASDisplayNode alloc] init];
[supernode addSubnode:subnode];
// Crash on next line
[supernode insertSubnode:subnode atIndex:1];
```
The issue is that all the checks around subnode array boundaries are done BEFORE `subnode` is removed from its `supernode`. If it happens that the `supernode` is self, then removing the `subnode` causes all our index checks to no longer be valid.
Here is the relevant code:
```
__instanceLock__.lock();
NSUInteger subnodesCount = _subnodes.count;
__instanceLock__.unlock();
////// Here we check our indexes
if (subnodeIndex > subnodesCount || subnodeIndex …
```
=> [ASDisplayNode] Fix a crash in insertSubnode
