Cartfile

Hey,
This PR moves https://github.com/facebook/AsyncDisplayKit/pull/3249 to brand new Texture and addresses the [comment](https://github.com/facebook/AsyncDisplayKit/pull/3249#discussion_r111510098) about beta.9 as well.
Cheers

Bump Cartfile versions to match podspec

---

docs/_docs/layout2-layoutspec-types.md

Missing `[ASInsetLayoutSpec` from ASInsetLayoutSpec creation line.

Missing a word

---

AsyncDisplayKit.xcodeproj/project.pbxproj
CHANGELOG.md

[IGListKit] Add IGListKit headers to public section of Xcode project

---

Texture.podspec

Everything seems to build fine with this version, so I'll
seek clarifying information from the reporter of this bug:
https://github.com/TextureGroup/Texture/issues/25

[Yoga] Increment Yoga version to current, 1.5.0.

---

Source/ASCellNode.h
Source/Details/ASCollectionElement.h
Source/Details/ASDataController.mm

[ASDataController] Avoid asking for size ranges of soon-to-be-delete elements during relayouts

---

Source/AsyncDisplayKit.h

Follow up on #451. This fixes the build failure on master. Not sure how #451 passed in the first place.

Add ASPagerNode+Beta to umbrella header #trivial

---

Source/ASDisplayNode+Layout.mm

[LayoutTransition] Call _locked_constrainedSizeForLayoutPass with the lock actually held #trivial

---

examples/ASCollectionView/Sample/ViewController.m

Fixes the crash reported by @Huang-Libo in #449.

[examples/ASCollectionView] Register supplementary kinds #trivial

---

Source/Private/ASInternalHelpers.m

I wrote this code originally, and wasn't thinking.

Use Nil for "no class" instead of nil #trivial

---

Source/Private/TextExperiment/Component/ASTextDebugOption.m

Fix naming conflict with YYText #trivial

---

Source/ASCollectionView.mm
Source/ASTableView.mm

I assumed that everything in ASCollectionView was main only… it's not :/ This means it's also currently not threadsafe :(

Dispatch batch update to main #trivial

---

AsyncDisplayKit.xcodeproj/project.pbxproj
Tests/ASTabBarControllerTests.m

Add tiny tests for the ASTabBarController
Test the view controller selection with index and UIViewController

[Tests] Introducing tests for the ASTabBarController

---

docs/_docs/resources.md

Awesome talk, @smeis! Please let me know if you want to add anything. We'll land this PR only with your approval.

Add a recent talk by @smeis at CocoaHeadsNL

---

docs/_docs/synchronous-concurrency.md

Correct Synchronous Concurrency Talk Link

---

docs/showcase.md

Opening PR for showcase site update with Vingle icon.
Thanks email feedback @garrettmoon

[Update Showcase] Update Showcase, add Vingle very community

---

docs/showcase.md

Add Blendle to our showcase page

---

Dangerfile

I landed #746 because it showed ✅  for the danger check. However, danger actually failed and Github ignored it. 
This fixes the dangerfile so that it actually works.

Fix the dangerfile

---

docs/showcase.md

Dear mr.moon
Last month, We had presentation about Improvement Vingle Feed Performance with Texture in Seoul, Republic of Korea. also, we posted medium about it
I wanna request update showcase
< Revision history >
- Attached Vingle Tech Talk Medium Post on Showcase 
- Fix [MensXP] table wrong indent on Showcase
Thank you for considering my pull request

[Showcase] Fix mensXP showcase and attach Vingle-Tech-Talk Medium

---

Source/Base/ASAssert.h
Source/Private/ASDefaultPlaybackButton.m

Fixes #875 and https://github.com/facebookarchive/AsyncDisplayKit/issues/3305

Fix ASDISPLAYNODE_ASSERTIONS_ENABLED and ASDefaultPlaybackButton warnings #trivial

---

docs/showcase.md

This change is for adding "iDiva - Beauty & Wedding tips" iOS app to Texture showcase.

Add 'iDiva - Beauty & Wedding tips' to Showcase

---

docs/_docs/containers-overview.md

For preview, please see https://github.com/EverettFavorites/Texture/blob/master/docs/_docs/containers-overview.md

replace ` with code in containers-overview.md

---

docs/showcase.md

@nguyenhuy asked (admittedly awhile back) if it's okay to include my app ([Apollo for Reddit](https://apolloapp.io)) in the [Showcase](http://texturegroup.org/showcase.html), and I'd be honored if you all would be still interested in that. Really appreciate the library, it's at the very core of my app.

Update showcase to include Apollo for Reddit

---

Source/ASCGImageBuffer.h
Source/ASRunLoopQueue.mm
Source/ASTextNode2.mm
Source/Details/ASCollectionFlowLayoutDelegate.m
Source/Private/TextExperiment/Component/ASTextLayout.m

Fixes multiple warnings and a memory leak

Fix warnings and a memory leak #trivial

---

Source/ASCollectionNode.mm

Add showsHorizontal(Vertical)ScrollIndicator property applying from pending state #trivial

---

docs/_docs/layout2-layoutspec-types.md

The original PR [here](https://github.com/TextureGroup/Texture/pull/1005) is kind of a mess. So I closed it and remake a clean PR for it.

Add an introduction for ASCornerLayoutSpec in layout2-layoutspec-types.md #trivial

---

docs/_data/nav_docs.yml
docs/_docs/asrunloopqueue.md
docs/_docs/automatic-layout-containers.md
docs/_docs/layout2-layout-element-properties.md
docs/_docs/team.md

- Remove not existing ASEnvironment
- Fix code highlighting
- Improve tam documentation

Fix multiple documentation issues #trivial

---

Source/ASDisplayNode.mm
Source/Private/ASDisplayNodeInternal.h

These are pretty hot code paths

Reuse interface state delegates when calling out #trivial

---

CHANGELOG.md
Source/ASDisplayNode.mm
Source/ASImageNode.mm
Source/ASMultiplexImageNode.mm
Source/Details/ASRangeController.mm

Improve locking around clearContents

---

examples_extra/Multiplex/Sample/ScreenNode.m

Add missing argument for calling image download completion block #trivial

---

Source/Details/ASPINRemoteImageDownloader.h

This causes our (internal) CI to fail lol

[ASPINRemoteImageDownloader] Fix +setSharedPreconfiguredRemoteImageManager:'s doc #trivial

---

Source/ASCollectionNode.mm

The default values of showsVerticalScrollIndicator and showsHorizontalScrollIndicator should be YES to correspond with the UIKit flags.

Set the default values for showsVerticalScrollIndicator and showsHorizontalScrollIndicator #trivial

---

Source/ASNetworkImageNode.mm

No need anymore as interface state is now handled with the interface state

Use interface state to manage image loading #trivial

---

Source/Base/ASAvailability.h

Defines needs to right at the #

Fix define spaces #trivial

---

Source/ASConfigurationInternal.h
Tests/Common/ASTestCase.h

This makes it easier for conforming UI updates within tests.

Expose test_resetWithConfiguration: for testing #trivial

---

Source/Details/ASThread.h

Initialize mutex assertion variables

---

Source/ASVideoNode.h

Issue is at row 153 of ASVideoNode.h file

Documentation typo, "trying" written two times

---

docs/showcase.md

Added a new app (Bluebird) to the app showcase.

Added Bluebird

---

docs/showcase.md

Bluebird is currently showing as a fourth column.

Move Bluebird to new row.

---

build.sh

Allow setting build.sh SDK and platform w/ env variables

---

Source/ASButtonNode.mm
Source/ASTextNode.h
Source/ASTextNode2.h

(...after the ASDisplayNode's view or layer have been created)

Access thread safe property to avoid assertion 

---

Source/ASImageNode+AnimatedImage.mm
Source/Private/ASImageNode+AnimatedImagePrivate.h

Get rid of file scope initialization that causes a premain startup hit.

Reduce startup time.

---

Source/Private/ASTwoDimensionalArrayUtils.mm

These methods are called on the main thread and will block the first range update so we need to make them as fast as possible.

Optimize ASTwoDimensionalArrayUtils

---

Source/ASDisplayNode+Yoga.mm

... to resolve infinite layout loop.

Resolve root constrained size before informing delegate

---

Source/ASDisplayNode+Layout.mm
Source/ASDisplayNode+Yoga.h
Source/ASDisplayNode+Yoga.mm

Fix warnings around Yoga Categories.

Cleanup Yoga Categories

---

docs/_docs/faq.md

Both of these technologies have their place, no point in being assholes.

Update the FAQ to throw less shade.

---

Source/ASNetworkImageNode.mm

Fix GIF Caching

---

Source/ASDisplayNode+Layout.mm

We could also have an experiment flag for this, but it's in a hot path so currently it's based the Yoga compiler flag.
Further information: https://github.com/TextureGroup/Texture/pull/1361#pullrequestreview-214651005

Only set ASLayoutElementStyle delegate if Yoga is enabled

---

Source/ASCollectionView.mm
Source/ASTableView.mm

Follow up to the #1420 where collection node is sending data/range controller to this API. Removing these calls removes child node leaks in removing collection nodes

[Experiment] Dont forget about these collection view background deallocs

---

Source/Details/ASCollectionElement.mm

Use AS::Mutex in ASCollectionElement

---

Source/ASDisplayNode.h
Source/Private/ASDisplayNode+UIViewBridge.mm
Source/Private/ASDisplayNodeInternal.h
Source/Private/_ASPendingState.mm
Tests/ASDisplayNodeTests.mm

This PR adds support for UIAccessibilityCustomAction propagation through ASPendingState so that it can be picked up by VoiceOver.

[#1451] Add support for UIAccessibilityCustomAction

---

Source/ASImageNode+AnimatedImage.mm
Source/ASImageNode.mm
Source/ASMultiplexImageNode.mm

This is a follow up to https://github.com/TextureGroup/Texture/pull/1420 and https://github.com/TextureGroup/Texture/pull/1424 to cover the rest of the surface area.

Cover the other background dealloc surfaces

---

Source/ASEditableTextNode.mm

Just shuffle some BOOLs around and explicitly declare an ivar so it is grouped with the others.

Shrink ASEditableTextNode by 16 bytes

---

Source/ASButtonNode+Private.h

(It's easier to deal with these as silly oneoffs IMO than to
have them conflated with real work)

Cleanup whitespace #trivial

---

Schemas/configuration.json
Source/ASExperimentalFeatures.h
Source/ASExperimentalFeatures.mm
Source/Details/_ASDisplayViewAccessiblity.mm
Tests/ASConfigurationTests.mm
Tests/ASDisplayViewAccessibilityTests.mm

`ASExperimentalDisableAccessibilityCache` is not in use right now. To reduce legacy code, let's remove it.

Remove ASExperimentalDisableAccessibilityCache

---

Schemas/configuration.json
Source/ASExperimentalFeatures.h
Source/ASExperimentalFeatures.mm
Source/Details/Transactions/_ASAsyncTransactionContainer.mm
Tests/ASConfigurationTests.mm
Tests/ASTransactionTests.mm

Removes #1438 and always enables #1429

Remove ASExperimentalTransactionOperationRetainCycle

---

docs/_docs/development/components.md

[dev docs] Remove redundant page

---

docs/_data/nav_docs.yml
docs/_docs/accessibility.md
docs/_docs/adoption-guide-2-0-beta1.md
docs/_docs/asrunloopqueue.md
docs/_docs/asvisibility.md
docs/_docs/containers-asviewcontroller.md
docs/_docs/faq.md
docs/_docs/intelligent-preloading.md
docs/_docs/layer-backing.md
docs/_docs/layout2-api-sizing.md
docs/_docs/layout2-quickstart.md
docs/_docs/subclassing.md
docs/_docs/uicollectionviewinterop.md

Update docs navigation orders

---

docs/_docs/development/how-to-debug.md
docs/_docs/development/layout-specs.md
docs/_docs/development/threading.md

fix broken image links in docs:
[How to debug issues in Texture](http://texturegroup.org/development/how-to-debug.html)
[Threading](http://texturegroup.org/development/threading.html)
[Layout specs](http://texturegroup.org/development/layout-specs.html)

[Dev docs] fix broken image links

---

Source/Private/_ASCoreAnimationExtras.mm

Use AS_ARRAY_SIZE for array counting, keep its usage consistent in the project.

Use AS_ARRAY_SIZE for array counting

---

Source/ASVideoNode.h

Signed-off-by: Vitalii Kuznetsov <v-blacksmith@hotmail.com>

fix typo in ASVideoNodeDelegate protocol

---

AsyncDisplayKit.xcodeproj/project.pbxproj

Remove duplicate `ASPINRemoteImageDownloader` in the project.

Remove duplicate `ASPINRemoteImageDownloader`

---

Source/ASRunLoopQueue.h

Remove unused `sharedDeallocationQueue` property

Remove unused `sharedDeallocationQueue` property

---

Source/ASRunLoopQueue.mm

Delete unused header in `ASRunLoopQueue`.

Delete unused header in `ASRunLoopQueue`

---

Source/ASControlNode.mm

Delete unused macro in `ASControlNode`.

Delete unused macro in `ASControlNode`

---

Schemas/configuration.json
Tests/ASConfigurationTests.mm

Fix failing ASConfigurationTests

---

Source/TextExperiment/Component/ASTextLayout.mm

Thanks, static analyzer!
Supplants half of #1958.

Remove redundant assignment

---

docs/showcase.md

Adds Remix by Buffer and also removes Facebook. Should resolve #1927. 👍

Docs: Remove Facebook and shift everything around, add Remix by Buffer
